/* 觀念小卡：學生答錯又「不知道錯在哪」時顯示。pt = 重點，ex = 最簡單的例子。 */
window.CARDS = {
  R01: {pt: String.raw`能寫成 \(\frac{p}{q}\)（\(p, q\) 為整數，\(q \ne 0\)）的數就是有理數。整數、有限小數、循環小數都是有理數。`,
        ex: String.raw`\(0.25=\frac{1}{4}\)、\(-3=\frac{-3}{1}\)、\(0.\overline{3}=\frac{1}{3}\) 都是有理數。`},
  R02: {pt: String.raw`設 \(x\) ＝ 這個循環小數，兩邊同乘 10 的次方，讓兩個式子小數點後的循環部分對齊，再<b>相減</b>，循環的部分就消失了，解出 \(x\) 即可。`,
        ex: String.raw`設 \(x=0.1\overline{2}=0.1222\cdots\)<br>\(100x=12.222\cdots\)、\(10x=1.222\cdots\)<br>相減：\(90x=11\) ⇒ \(x=\frac{11}{90}\)。`},
  R03: {pt: String.raw`<b>先約成最簡分數</b>，再看分母的質因數：只有 2 和 5 → 有限小數；還有其他質因數 → 循環小數。`,
        ex: String.raw`\(\frac{3}{12}=\frac{1}{4}\)，分母 \(2^2\) → 有限小數；\(\frac{1}{6}\) 分母有 3 → 循環小數。`},
  R04: {pt: String.raw`任兩個不同的有理數之間，一定還有有理數，而且有無限多個。`,
        ex: String.raw`\(a\)、\(b\) 之間一定有 \(\frac{a+b}{2}\)；所以「比 0 大的最小有理數」不存在。`},
  R05: {pt: String.raw`無理數不能寫成 \(\frac{p}{q}\)，小數不循環也不會結束。常見的有 \(\sqrt{2}\)、\(\sqrt{3}\)、\(\pi\)。<b>根號要先化簡再判斷</b>。`,
        ex: String.raw`\(\sqrt{8}=2\sqrt{2}\) 是無理數；\(\sqrt{\frac{4}{9}}=\frac{2}{3}\) 是有理數；\(0.1010010001\cdots\) 是無理數。`},
  R06: {pt: String.raw`有理數 ± 無理數 ＝ 無理數；不是 0 的有理數 × 無理數 ＝ 無理數。<br>但「無理數和無理數」相加、相乘，結果<b>不一定</b>是無理數。`,
        ex: String.raw`\(\sqrt{2}+(-\sqrt{2})=0\)、\(\sqrt{2}\times\sqrt{2}=2\) 都是有理數；\(0\times\sqrt{2}=0\) 也是。`},
  R07: {pt: String.raw`若 \(a\)、\(b\) 都是<b>有理數</b>，且 \(a+b\sqrt{2}=0\)，則 \(a=b=0\)。<br>同理 \(a+b\sqrt{2}=c+d\sqrt{2}\) ⇒ \(a=c\)、\(b=d\)。`,
        ex: String.raw`\(x\)、\(y\) 為有理數，\((x-1)+(y+2)\sqrt{2}=0\) ⇒ \(x=1\)、\(y=-2\)。`},
  R08: {pt: String.raw`找兩個夾住它的完全平方數，就知道整數部分；要更準就試小數一位的平方。`,
        ex: String.raw`\(9\lt 10\lt 16\) ⇒ \(3\lt\sqrt{10}\lt 4\)；\(3.1^2=9.61\)、\(3.2^2=10.24\) ⇒ \(\sqrt{10}=3.1\cdots\)。`},
  R09: {pt: String.raw`不等式兩邊同乘（或同除）<b>負數</b>，不等號要反向。<br>\(a\gt b\) 不保證 \(a^2\gt b^2\)，要看正負。`,
        ex: String.raw`\(a\lt b\) ⇒ \(-3a\gt -3b\)；\(-2\lt 1\)，但 \((-2)^2\gt 1^2\)。`},
  R10: {pt: String.raw`\((a\pm b)^2=a^2\pm 2ab+b^2\)；\((a+b)(a-b)=a^2-b^2\)。中間的 \(2ab\) 最常被漏掉。`,
        ex: String.raw`\((\sqrt{3}+1)^2=3+2\sqrt{3}+1=4+2\sqrt{3}\)。`},
  R11: {pt: String.raw`\((a+b)^3=a^3+3a^2b+3ab^2+b^3\)<br>\(a^3+b^3=(a+b)(a^2-ab+b^2)\)；\(a^3-b^3=(a-b)(a^2+ab+b^2)\)`,
        ex: String.raw`\(x^3-8=(x-2)(x^2+2x+4)\)。`},
  R12: {pt: String.raw`\(x^2+\frac{1}{x^2}=\left(x+\frac{1}{x}\right)^2-2\)<br>\(x^3+\frac{1}{x^3}=\left(x+\frac{1}{x}\right)^3-3\left(x+\frac{1}{x}\right)\)<br>關鍵是 \(x\cdot\frac{1}{x}=1\)。`,
        ex: String.raw`\(x+\frac{1}{x}=3\) ⇒ \(x^2+\frac{1}{x^2}=9-2=7\)。`},
  R13: {pt: String.raw`把根號裡的平方因數提出來：\(\sqrt{a^2b}=a\sqrt{b}\)（\(a\ge 0\)）。<b>根號裡相同</b>才能合併。`,
        ex: String.raw`\(\sqrt{12}+\sqrt{27}=2\sqrt{3}+3\sqrt{3}=5\sqrt{3}\)；但 \(\sqrt{2}+\sqrt{3}\ne\sqrt{5}\)。`},
  R14: {pt: String.raw`分母是 \(\sqrt{a}\)：上下同乘 \(\sqrt{a}\)。<br>分母是 \(\sqrt{a}+\sqrt{b}\)：上下同乘 \(\sqrt{a}-\sqrt{b}\)，用平方差消掉根號。`,
        ex: String.raw`\(\frac{1}{\sqrt{3}+\sqrt{2}}=\frac{\sqrt{3}-\sqrt{2}}{3-2}=\sqrt{3}-\sqrt{2}\)。`},
  R15: {pt: String.raw`兩個正數比大小，可以都平方再比；或把係數放進根號：\(a\sqrt{b}=\sqrt{a^2b}\)（\(a\gt 0\)）。`,
        ex: String.raw`\(2\sqrt{3}=\sqrt{12}\)、\(3\sqrt{2}=\sqrt{18}\) ⇒ \(2\sqrt{3}\lt 3\sqrt{2}\)。`},
  R16: {pt: String.raw`先把根號前的係數湊成 2，再找兩數「和」與「積」：<br>\(\sqrt{(a+b)\pm 2\sqrt{ab}}=\sqrt{a}\pm\sqrt{b}\)（\(a\gt b\gt 0\)，減號時大的放前面）。`,
        ex: String.raw`\(\sqrt{5+2\sqrt{6}}=\sqrt{3}+\sqrt{2}\)（\(3+2=5\)、\(3\times 2=6\)）；\(\sqrt{4-\sqrt{12}}=\sqrt{4-2\sqrt{3}}=\sqrt{3}-1\)。`},
  R17: {pt: String.raw`\(a, b\) 為正數時 \(\frac{a+b}{2}\ge\sqrt{ab}\)，\(a=b\) 時等號成立。<br>和固定 → 積有最大值；積固定 → 和有最小值。`,
        ex: String.raw`\(x\gt 0\) 時 \(x+\frac{4}{x}\ge 2\sqrt{4}=4\)，\(x=2\) 時有最小值 4。`},

  A01: {pt: String.raw`數線上 \(A(a)\)、\(B(b)\)，\(P\) 在線段 \(AB\) 上且 \(\overline{AP}:\overline{PB}=m:n\)，則 \(P=\frac{na+mb}{m+n}\)（交叉相乘）。中點是 \(\frac{a+b}{2}\)。`,
        ex: String.raw`\(A(1)\)、\(B(7)\)，\(\overline{AP}:\overline{PB}=1:2\) ⇒ \(P=\frac{2\cdot 1+1\cdot 7}{3}=3\)。`},
  A02: {pt: String.raw`\(|a|\) 是 \(a\) 到原點的距離；\(|a-b|\) 是 \(a\)、\(b\) 兩點的距離。`,
        ex: String.raw`\(|x-3|\) 是 \(x\) 到 3 的距離；\(|x+2|=|x-(-2)|\) 是 \(x\) 到 \(-2\) 的距離。`},
  A03: {pt: String.raw`先判斷絕對值裡面的正負：\(\ge 0\) 直接拿掉；\(\lt 0\) 拿掉後整個加負號。`,
        ex: String.raw`\(|\sqrt{2}-2|=2-\sqrt{2}\)（因為 \(\sqrt{2}\lt 2\)）；\(|3-\pi|=\pi-3\)。`},
  A04: {pt: String.raw`\(\sqrt{a^2}=|a|\)，結果一定 \(\ge 0\)，<b>不一定等於 \(a\)</b>。`,
        ex: String.raw`\(\sqrt{(-5)^2}=5\)；\(\sqrt{(\sqrt{3}-\sqrt{5})^2}=|\sqrt{3}-\sqrt{5}|=\sqrt{5}-\sqrt{3}\)。`},
  A05: {pt: String.raw`\(|a|\ge 0\)、\(a^2\ge 0\)、\(\sqrt{a}\ge 0\)。幾個非負的數相加等於 0，每一個都是 0。`,
        ex: String.raw`\(|x-1|+(y+2)^2=0\) ⇒ \(x=1\)、\(y=-2\)。`},
  A06: {pt: String.raw`\(|x-a|=k\)（\(k\gt 0\)）：到 \(a\) 距離為 \(k\) 的點有兩個，\(x=a+k\) 或 \(a-k\)。\(k\lt 0\) 時無解。`,
        ex: String.raw`\(|x-2|=3\) ⇒ \(x=5\) 或 \(x=-1\)。`},
  A07: {pt: String.raw`\(|x-a|\le k\)：到 \(a\) 的距離不超過 \(k\)，夾在中間：\(a-k\le x\le a+k\)。`,
        ex: String.raw`\(|x-1|\le 3\) ⇒ \(-2\le x\le 4\)。`},
  A08: {pt: String.raw`\(|x-a|\ge k\)：到 \(a\) 的距離至少 \(k\)，往兩邊走：\(x\le a-k\) 或 \(x\ge a+k\)。`,
        ex: String.raw`\(|x+1|\ge 2\) ⇒ \(x\le -3\) 或 \(x\ge 1\)。`},
  A09: {pt: String.raw`中括號 \([\ ]\) 包含端點，小括號 \((\ )\) 不包含；\(\infty\) 一定用小括號。`,
        ex: String.raw`\(-1\le x\lt 3\) 寫成 \([-1, 3)\)；\(x\gt 2\) 寫成 \((2, \infty)\)。`},
  A10: {pt: String.raw`「\(a\pm k\)」表示 \(a-k\le x\le a+k\)，也就是 \(|x-a|\le k\)。`,
        ex: String.raw`身高 \(170\pm 2\) 公分 ⇔ \(|x-170|\le 2\) ⇔ \(168\le x\le 172\)。`},

  E01: {pt: String.raw`\(a^m\cdot a^n=a^{m+n}\)、\(\frac{a^m}{a^n}=a^{m-n}\)、\((a^m)^n=a^{mn}\)、\((ab)^n=a^nb^n\)。`,
        ex: String.raw`\(2^3\cdot 2^4=2^7\)（不是 \(2^{12}\)）；\((2^3)^2=2^6\)。`},
  E02: {pt: String.raw`\(a^0=1\)（\(a\ne 0\)）；\(a^{-n}=\frac{1}{a^n}\)。負指數是「倒數」，不是負數。`,
        ex: String.raw`\(2^{-3}=\frac{1}{8}\)；\(\left(\frac{2}{3}\right)^{-2}=\frac{9}{4}\)。`},
  E03: {pt: String.raw`\(x^n=a\) 的實數解：\(n\) 為奇數時恰有一個 \(\sqrt[n]{a}\)；\(n\) 為偶數時，\(a\gt 0\) 有兩個 \(\pm\sqrt[n]{a}\)，\(a\lt 0\) 沒有實數解。<br>\(n\) 為偶數時，\(\sqrt[n]{a}\) 只代表正的那一個。`,
        ex: String.raw`\(\sqrt[3]{-8}=-2\)；\(x^4=16\) ⇒ \(x=\pm 2\)，但 \(\sqrt[4]{16}=2\)。`},
  E04: {pt: String.raw`\(a^{\frac{m}{n}}=\sqrt[n]{a^m}=(\sqrt[n]{a})^m\)（\(a\gt 0\)）：分母是根號的次數，分子是次方。`,
        ex: String.raw`\(8^{\frac{2}{3}}=(\sqrt[3]{8})^2=4\)；\(4^{-\frac{1}{2}}=\frac{1}{2}\)。`},
  E05: {pt: String.raw`底數 \(\gt 0\) 時，指數律對分數指數一樣成立。先把底數化成同一個底，再加減指數。`,
        ex: String.raw`\(\sqrt{2}\cdot\sqrt[3]{2}=2^{\frac{1}{2}+\frac{1}{3}}=2^{\frac{5}{6}}\)；\(9^{\frac{3}{4}}=3^{\frac{3}{2}}=3\sqrt{3}\)。`},
  E06: {pt: String.raw`\(a\gt 0\) 時，\(a^x\) 對所有實數 \(x\) 都有意義，而且 \(a^x\gt 0\)，指數律照樣成立。`,
        ex: String.raw`\(2^{\sqrt{2}}\cdot 2^{\sqrt{2}}=2^{2\sqrt{2}}\)；不論 \(x\) 是多少，\(2^x\) 都是正的。`},
  E07: {pt: String.raw`同底數：底數 \(\gt 1\)，指數大的比較大；底數在 0 和 1 之間，指數大的反而小。<br>不同底數：先化成同底或同指數。`,
        ex: String.raw`\(2^{0.3}\lt 2^{0.5}\)；\(\left(\frac{1}{2}\right)^{0.3}\gt\left(\frac{1}{2}\right)^{0.5}\)；\(2^{30}=8^{10}\lt 9^{10}=3^{20}\)。`},
  E08: {pt: String.raw`因為 \(a^x\cdot a^{-x}=1\)，所以 \(a^{2x}+a^{-2x}=(a^x+a^{-x})^2-2\)，跟 \(x+\frac{1}{x}\) 的題型一樣。`,
        ex: String.raw`\(2^x+2^{-x}=3\) ⇒ \(4^x+4^{-x}=9-2=7\)。`},
  E09: {pt: String.raw`每經過一段時間變成 \(r\) 倍，經過 \(n\) 段後變成 \(r^n\) 倍。半衰期 \(T\)：經過 \(t\) 後剩下 \(\left(\frac{1}{2}\right)^{\frac{t}{T}}\)。`,
        ex: String.raw`細菌每 20 分鐘變 2 倍，1 小時後是 \(2^3=8\) 倍；半衰期 5 年，15 年後剩 \(\frac{1}{8}\)。`},

  L01: {pt: String.raw`科學記號寫成 \(a\times 10^n\)，其中 \(1\le a\lt 10\)、\(n\) 為整數。`,
        ex: String.raw`\(345000=3.45\times 10^5\)；\(0.0072=7.2\times 10^{-3}\)；\(34.5\times 10^4\) 不是科學記號。`},
  L02: {pt: String.raw`有效數字從左邊第一個不是 0 的數字開始算；寫成科學記號後，\(a\) 有幾位就是幾位有效數字。`,
        ex: String.raw`\(0.00340=3.40\times 10^{-3}\)，有 3 位有效數字。`},
  L03: {pt: String.raw`\(a\) 的部分相乘除，10 的次方相加減，最後把 \(a\) 調回 1 到 10 之間。`,
        ex: String.raw`\((4\times 10^3)(5\times 10^6)=20\times 10^9=2\times 10^{10}\)。`},
  L04: {pt: String.raw`\(a\times 10^{-n}\)（\(1\le a\lt 10\)）：小數點後第 \(n\) 位開始不為 0。`,
        ex: String.raw`\(0.0072=7.2\times 10^{-3}\)，小數點後第 3 位是 7。`},
  L05: {pt: String.raw`\(\log a=b\iff 10^b=a\)（\(a\gt 0\)）。log 就是在問「10 的幾次方」。`,
        ex: String.raw`\(\log 1000=3\)、\(\log 0.01=-2\)、\(\log 1=0\)；\(\log 0\) 和 \(\log(-5)\) 沒有意義。`},
  L06: {pt: String.raw`找兩個夾住它的 10 的次方，log 值就夾在兩個整數之間。`,
        ex: String.raw`\(100\lt 350\lt 1000\) ⇒ \(2\lt\log 350\lt 3\)。`},
  L07: {pt: String.raw`數變成 10 倍，log 值加 1：\(\log(a\times 10^n)=\log a+n\)。`,
        ex: String.raw`\(\log 2\approx 0.3010\) ⇒ \(\log 200\approx 2.3010\)、\(\log 0.02\approx 0.3010-2=-1.6990\)。`},
  L08: {pt: String.raw`\(x\gt 1\) 且 \(\log x\) 的整數部分是 \(n\)，則 \(10^n\le x\lt 10^{n+1}\)，\(x\) 是 \(n+1\) 位數。`,
        ex: String.raw`\(\log x=4.7\) ⇒ \(10^4\lt x\lt 10^5\)，\(x\) 是 5 位數。`},
  L09: {pt: String.raw`\(\log 2^n=n\log 2\approx 0.3010n\)，再用位數判斷。`,
        ex: String.raw`\(\log 2^{20}\approx 6.02\) ⇒ \(2^{20}\) 是 7 位數。`},
  L10: {pt: String.raw`\(\log(ab)=\log a+\log b\)；\(\log\frac{a}{b}=\log a-\log b\)（\(a, b\gt 0\)）。<br>注意 \(\log(a+b)\ne\log a+\log b\)。`,
        ex: String.raw`\(\log 6=\log 2+\log 3\approx 0.3010+0.4771=0.7781\)。`},
  L11: {pt: String.raw`\(\log a^n=n\log a\)（\(a\gt 0\)）。`,
        ex: String.raw`\(\log 8=3\log 2\approx 0.9030\)；\(\log\sqrt{10}=\frac{1}{2}\)。`},
  L12: {pt: String.raw`把數拆成 2、3、5、10 的乘除和次方再用對數律；記得 \(\log 5=1-\log 2\)。`,
        ex: String.raw`\(\log 5=\log\frac{10}{2}=1-\log 2\approx 0.6990\)；\(\log 12=2\log 2+\log 3\)。`}
};
