/* 單元03 指數　題庫初稿
   格式同 unit01.js。數學式一律用 LaTeX，行內公式以 \( ... \) 包起來。 */
window.BANK_UNIT03 = [
  // E01 正整數指數的指數律
  {id:"E01-1", tag:"E01", level:"易", type:"tf",
   stem:String.raw`若 \(a\gt 0\)、\(b\gt 0\)，則 \((a^2b^3)^2=a^4b^9\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:[String.raw`把 \((b^3)^2\) 算成 \(b^{3^2}\)`,"次方的次方用加的","只對其中一個字母乘次方"], key:0,
   exp:String.raw`\((a^m)^n=a^{mn}\)：\((a^2b^3)^2=a^{2\times 2}b^{3\times 2}=a^4b^6\)。`},
  {id:"E01-2", tag:"E01", level:"易", type:"mc",
   stem:String.raw`\(2^3\times 2^4=\)？`,
   opts:[String.raw`\(2^7\)`,String.raw`\(2^{12}\)`,String.raw`\(4^7\)`,String.raw`\(4^{12}\)`], ans:[0],
   reasons:["同底數相乘時把指數相乘","把底數也相乘了","指數律記混"], key:0,
   exp:String.raw`同底數相乘，指數相加：\(2^3\times 2^4=2^{3+4}=2^7\)。`},
  {id:"E01-3", tag:"E01", level:"中", type:"mc",
   stem:String.raw`\((-2a^2)^3=\)？`,
   opts:[String.raw`\(-8a^6\)`,String.raw`\(-6a^6\)`,String.raw`\(8a^6\)`,String.raw`\(-8a^5\)`], ans:[0],
   reasons:[String.raw`係數 \(-2\) 沒有三次方，而是乘 \(3\)`,"負數的奇數次方忘了是負的",String.raw`\((a^2)^3\) 的指數用加的`], key:0,
   exp:String.raw`\((-2a^2)^3=(-2)^3\cdot(a^2)^3=-8a^6\)。`},

  // E02 零指數與負整數指數
  {id:"E02-1", tag:"E02", level:"易", type:"tf",
   stem:String.raw`若 \(a\neq 0\)，則 \(a^0=0\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:[String.raw`以為 \(0\) 次方就等於 \(0\)`,String.raw`和「\(0\) 乘任何數都是 \(0\)」搞混`,String.raw`忘了 \(a^0=1\) 的定義`], key:0,
   exp:String.raw`定義 \(a^0=1\)（\(a\neq 0\)）。這樣 \(a^m\div a^m=a^{m-m}=a^0\) 才會等於 \(1\)。`},
  {id:"E02-2", tag:"E02", level:"易", type:"mc",
   stem:String.raw`\(2^{-3}=\)？`,
   opts:[String.raw`\(\dfrac{1}{8}\)`,String.raw`\(-8\)`,String.raw`\(-6\)`,String.raw`\(\dfrac{1}{6}\)`], ans:[0],
   reasons:["把負指數當成負號",String.raw`把 \(2^{-3}\) 算成 \(2\times(-3)\)`,"取倒數後次方算錯"], key:0,
   exp:String.raw`\(a^{-n}=\dfrac{1}{a^n}\)，所以 \(2^{-3}=\dfrac{1}{2^3}=\dfrac{1}{8}\)。`},
  {id:"E02-3", tag:"E02", level:"中", type:"mc",
   stem:String.raw`\(\left(\dfrac{1}{3}\right)^{-2}=\)？`,
   opts:[String.raw`\(9\)`,String.raw`\(\dfrac{1}{9}\)`,String.raw`\(-9\)`,String.raw`\(-\dfrac{1}{9}\)`], ans:[0],
   reasons:["把負指數當成負號","不知道負指數要取倒數","倒數取了兩次又翻回來"], key:1,
   exp:String.raw`\(\left(\dfrac{1}{3}\right)^{-2}=\dfrac{1}{\left(\frac{1}{3}\right)^2}=\dfrac{1}{\frac{1}{9}}=9\)，也就是 \(3^2=9\)。`},

  // E03 n 次方根
  {id:"E03-1", tag:"E03", level:"易", type:"tf",
   stem:String.raw`方程式 \(x^5=2\) 有唯一的正實根 \(\sqrt[5]{2}\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["以為奇數次方程式有兩個實根",String.raw`以為 \(n\) 次方程式就有 \(n\) 個正實根`,String.raw`不熟 \(n\) 次方根的定義`], key:1,
   exp:String.raw`當 \(a\gt 0\)、\(n\ge 2\) 時，\(x^n=a\) 恰有一個正實根，記作 \(\sqrt[n]{a}\)。`},
  {id:"E03-2", tag:"E03", level:"中", type:"mc",
   stem:`下列何者<b>不是</b>實數？`,
   opts:[String.raw`\(\sqrt[3]{-8}\)`,String.raw`\(\sqrt[4]{16}\)`,String.raw`\(\sqrt{-4}\)`,String.raw`\(\sqrt[5]{-1}\)`], ans:[2],
   reasons:["以為負數不能開任何次方根","以為負數開偶次方根也有實數",String.raw`以為 \(\sqrt[3]{-8}\) 不存在`], key:1,
   exp:String.raw`負數可以開奇次方根：\(\sqrt[3]{-8}=-2\)、\(\sqrt[5]{-1}=-1\)；\(\sqrt[4]{16}=2\)。<br>負數開偶次方根在實數中不存在，所以 \(\sqrt{-4}\) 不是實數。`},
  {id:"E03-3", tag:"E03", level:"易", type:"mc",
   stem:String.raw`\(\sqrt[4]{81}=\)？`,
   opts:[String.raw`\(3\)`,String.raw`\(\pm 3\)`,String.raw`\(9\)`,String.raw`\(-3\)`], ans:[0],
   reasons:[String.raw`以為正 \(4\) 次方根要寫 \(\pm\)`,String.raw`把 \(4\) 次方根當成平方根`,"開方後的正負號弄錯"], key:0,
   exp:String.raw`\(3^4=81\)，而 \(\sqrt[4]{81}\) 指的是正的 \(4\) 次方根，所以是 \(3\)。`},

  // E04 有理數指數的定義
  {id:"E04-1", tag:"E04", level:"中", type:"tf",
   stem:String.raw`\(\sqrt[3]{-27}=(-27)^{\frac{1}{3}}\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:["忘了有理數指數的底數必須是正數","以為根號和分數指數一定可以互換",String.raw`把 \(\sqrt[3]{-27}\) 算錯`], key:0,
   exp:String.raw`有理數指數 \(a^{\frac{m}{n}}\) 的定義要求 \(a\gt 0\)，所以 \((-27)^{\frac{1}{3}}\) 沒有定義。<br>（\(\sqrt[3]{-27}=-3\) 本身沒問題，但不能寫成分數指數。）`},
  {id:"E04-2", tag:"E04", level:"易", type:"mc",
   stem:String.raw`\(8^{\frac{2}{3}}=\)？`,
   opts:[String.raw`\(4\)`,String.raw`\(\dfrac{16}{3}\)`,String.raw`\(64\)`,String.raw`\(2\)`], ans:[0],
   reasons:[String.raw`把 \(\dfrac{2}{3}\) 次方當成乘以 \(\dfrac{2}{3}\)`,"只平方，忘了開立方","開立方後忘了平方"], key:0,
   exp:String.raw`\(8^{\frac{2}{3}}=\left(\sqrt[3]{8}\right)^2=2^2=4\)。`},
  {id:"E04-3", tag:"E04", level:"中", type:"mc",
   stem:String.raw`\(27^{-\frac{2}{3}}=\)？`,
   opts:[String.raw`\(\dfrac{1}{9}\)`,String.raw`\(-9\)`,String.raw`\(9\)`,String.raw`\(-18\)`], ans:[0],
   reasons:["把負指數當成負號",String.raw`\(\dfrac{2}{3}\) 次方算錯`,"忘了取倒數"], key:0,
   exp:String.raw`\(27^{-\frac{2}{3}}=\dfrac{1}{27^{\frac{2}{3}}}=\dfrac{1}{(\sqrt[3]{27})^2}=\dfrac{1}{9}\)。`},

  // E05 有理數指數律的化簡
  {id:"E05-1", tag:"E05", level:"易", type:"mc",
   stem:String.raw`若 \(a\gt 0\)，則 \(a^{\frac{1}{2}}\cdot a^{\frac{1}{3}}=\)？`,
   opts:[String.raw`\(a^{\frac{5}{6}}\)`,String.raw`\(a^{\frac{1}{6}}\)`,String.raw`\(a^{\frac{2}{5}}\)`,String.raw`\(a^{\frac{1}{5}}\)`], ans:[0],
   reasons:["相乘時把指數相乘","分數相加時分子加分子、分母加分母","通分算錯"], key:1,
   exp:String.raw`同底數相乘，指數相加：\(\dfrac{1}{2}+\dfrac{1}{3}=\dfrac{5}{6}\)，所以結果是 \(a^{\frac{5}{6}}\)。`},
  {id:"E05-2", tag:"E05", level:"中", type:"mc",
   stem:String.raw`若 \(a\gt 0\)，則 \(\left(a^{\frac{2}{3}}\right)^{\frac{3}{4}}=\)？`,
   opts:[String.raw`\(a^{\frac{1}{2}}\)`,String.raw`\(a^{\frac{17}{12}}\)`,String.raw`\(a^{\frac{8}{9}}\)`,String.raw`\(a^{2}\)`], ans:[0],
   reasons:["次方的次方用加的","分數相乘算錯","把指數相除"], key:0,
   exp:String.raw`\((a^p)^q=a^{pq}\)：\(\dfrac{2}{3}\times\dfrac{3}{4}=\dfrac{1}{2}\)，所以結果是 \(a^{\frac{1}{2}}\)。`},
  {id:"E05-3", tag:"E05", level:"中", type:"num",
   stem:String.raw`\(4^{\frac{3}{2}}\times 8^{-\frac{1}{3}}=\)？`, ans:"4", unitWord:"",
   reasons:[String.raw`把 \(4^{\frac{3}{2}}\) 算成 \(6\)`,String.raw`把 \(8^{-\frac{1}{3}}\) 的負號當成負數`,"沒有化成同底數"], key:1,
   exp:String.raw`\(4^{\frac{3}{2}}=(\sqrt{4})^3=8\)，\(8^{-\frac{1}{3}}=\dfrac{1}{\sqrt[3]{8}}=\dfrac{1}{2}\)。<br>相乘得 \(8\times\dfrac{1}{2}=4\)。`},

  // E06 實數指數與指數律
  {id:"E06-1", tag:"E06", level:"易", type:"tf",
   stem:String.raw`若 \(a\gt 0\)，則 \(a^{\sqrt{2}}\cdot a^{\sqrt{2}}=a^{2\sqrt{2}}\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["以為無理數指數不能用指數律",String.raw`把指數相乘得到 \(a^2\)`,"以為底數要相乘"], key:0,
   exp:String.raw`實數指數一樣適用指數律：\(a^{\sqrt{2}}\cdot a^{\sqrt{2}}=a^{\sqrt{2}+\sqrt{2}}=a^{2\sqrt{2}}\)。`},
  {id:"E06-2", tag:"E06", level:"中", type:"mc",
   stem:String.raw`\(\left(2^{\sqrt{3}}\right)^{\sqrt{3}}=\)？`,
   opts:[String.raw`\(8\)`,String.raw`\(2^{2\sqrt{3}}\)`,String.raw`\(6\)`,String.raw`\(2^{\sqrt{6}}\)`], ans:[0],
   reasons:["次方的次方用加的",String.raw`\(\sqrt{3}\times\sqrt{3}\) 算錯`,"以為無理數指數不能化簡"], key:0,
   exp:String.raw`\(\left(2^{\sqrt{3}}\right)^{\sqrt{3}}=2^{\sqrt{3}\times\sqrt{3}}=2^3=8\)。`},

  // E07 指數比大小
  {id:"E07-1", tag:"E07", level:"難", type:"mc",
   stem:String.raw`設 \(a=2^{30}\)、\(b=3^{20}\)、\(c=5^{10}\)，則大小關係為？`,
   opts:[String.raw`\(c\lt a\lt b\)`,String.raw`\(a\lt b\lt c\)`,String.raw`\(a\lt c\lt b\)`,String.raw`\(b\lt a\lt c\)`], ans:[0],
   reasons:["沒有先化成相同的指數再比","以為底數大的就比較大","指數化簡時算錯"], key:0,
   exp:String.raw`化成相同指數 \(10\)：\(a=(2^3)^{10}=8^{10}\)、\(b=(3^2)^{10}=9^{10}\)、\(c=5^{10}\)。<br>底數 \(5\lt 8\lt 9\)，所以 \(c\lt a\lt b\)。`},
  {id:"E07-2", tag:"E07", level:"易", type:"tf",
   stem:String.raw`\(\left(\dfrac{1}{2}\right)^3\gt \left(\dfrac{1}{2}\right)^5\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["以為指數越大，值就一定越大",String.raw`忘了底數小於 \(1\) 時大小關係會相反`,"次方算錯"], key:1,
   exp:String.raw`\(\left(\dfrac{1}{2}\right)^3=\dfrac{1}{8}\)、\(\left(\dfrac{1}{2}\right)^5=\dfrac{1}{32}\)，所以前者較大。<br>底數在 \(0\) 和 \(1\) 之間時，指數越大，值越小。`},
  {id:"E07-3", tag:"E07", level:"中", type:"mc",
   stem:String.raw`比較 \(\sqrt{2}\) 與 \(\sqrt[3]{3}\) 的大小：`,
   opts:[String.raw`\(\sqrt{2}\lt \sqrt[3]{3}\)`,String.raw`\(\sqrt{2}\gt \sqrt[3]{3}\)`,"兩者相等","無法比較"], ans:[0],
   reasons:[String.raw`沒有同時取 \(6\) 次方再比較`,"以為根號次數越高，值就越大","以為不同次方根不能比較"], key:0,
   exp:String.raw`同時取 \(6\) 次方：\((\sqrt{2})^6=2^3=8\)、\((\sqrt[3]{3})^6=3^2=9\)。<br>\(8\lt 9\)，所以 \(\sqrt{2}\lt \sqrt[3]{3}\)。`},

  // E08 a^x + a^(−x) 型求值
  {id:"E08-1", tag:"E08", level:"中", type:"num",
   stem:String.raw`若 \(a\gt 0\) 且 \(a^x+a^{-x}=4\)，則 \(a^{2x}+a^{-2x}=\)？`, ans:"14", unitWord:"",
   reasons:[String.raw`平方後忘了減 \(2\)`,String.raw`以為平方後直接是 \(16\)`,String.raw`把 \(a^x\cdot a^{-x}\) 算成 \(0\)`], key:0,
   exp:String.raw`\((a^x+a^{-x})^2=a^{2x}+2+a^{-2x}\)（因為 \(a^x\cdot a^{-x}=1\)）。<br>所以 \(a^{2x}+a^{-2x}=16-2=14\)。`},
  {id:"E08-2", tag:"E08", level:"中", type:"tf",
   stem:String.raw`若 \(a\gt 0\)，則 \(a^{3x}+a^{-3x}=(a^x+a^{-x})(a^{2x}-1+a^{-2x})\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["沒有認出這是立方和公式",String.raw`以為中間項應該是 \(+1\)`,String.raw`忘了 \(a^x\cdot a^{-x}=1\)`], key:0,
   exp:String.raw`立方和公式 \(A^3+B^3=(A+B)(A^2-AB+B^2)\)，取 \(A=a^x\)、\(B=a^{-x}\)，\(AB=1\)：<br>\(a^{3x}+a^{-3x}=(a^x+a^{-x})(a^{2x}-1+a^{-2x})\)。`},

  // E09 指數的情境應用
  {id:"E09-1", tag:"E09", level:"易", type:"mc",
   stem:String.raw`某細菌每 \(1\) 小時數量變為原來的 \(2\) 倍。起始有 \(100\) 隻，\(3\) 小時後有幾隻？`,
   opts:[String.raw`\(800\)`,String.raw`\(600\)`,String.raw`\(300\)`,String.raw`\(900\)`], ans:[0],
   reasons:[String.raw`把「每小時 \(2\) 倍」算成 \(2\times 3\) 倍`,String.raw`把倍數和時間相加`,"次方算錯"], key:0,
   exp:String.raw`每小時乘 \(2\)，\(3\) 小時乘了 \(3\) 次：\(100\times 2^3=800\)。`},
  {id:"E09-2", tag:"E09", level:"中", type:"mc",
   stem:String.raw`某細菌每 \(3\) 小時數量變為原來的 \(2\) 倍。經過 \(1\) 小時，數量變為原來的幾倍？`,
   opts:[String.raw`\(2^{\frac{1}{3}}\)`,String.raw`\(\dfrac{2}{3}\)`,String.raw`\(2^3\)`,String.raw`\(3^{\frac{1}{2}}\)`], ans:[0],
   reasons:["把時間比例直接乘上倍數","不會用分數指數表示","把底數和指數弄反"], key:0,
   exp:String.raw`設每小時變為 \(r\) 倍，則 \(r^3=2\)，所以 \(r=\sqrt[3]{2}=2^{\frac{1}{3}}\)。`}
];
