/* 單元03 指數　題庫初稿
   格式同 unit01.js。數學式一律用 LaTeX，行內公式以 \( ... \) 包起來。 */
window.BANK_UNIT03 = [
  // E01 正整數指數的指數律
  {id:"E01-1", tag:"E01", level:"易", type:"tf",
   stem:String.raw`若 \(a\gt 0\)、\(b\gt 0\)，則 \((a^2b^3)^2=a^4b^9\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:[String.raw`把 \((b^3)^2\) 算成 \(b^{3^2}\)`,"次方的次方用加的","只對其中一個字母乘次方"], key:0,
   exp:String.raw`\((a^m)^n=a^{mn}\)：\((a^2b^3)^2=a^{2\times 2}b^{3\times 2}=a^4b^6\)。`},
  {id:"E01-2", tag:"E01", level:"易", type:"mc",
   stem:String.raw`\(2^3\times 2^4=\)？`,
   opts:[String.raw`\(2^7\)`,String.raw`\(2^{12}\)`,String.raw`\(4^7\)`,String.raw`\(4^{12}\)`], ans:[0],
   reasons:["同底數相乘時把指數相乘","把底數也相乘了","指數律記混"], key:0,
   exp:String.raw`同底數相乘，指數相加：\(2^3\times 2^4=2^{3+4}=2^7\)。`},
  {id:"E01-3", tag:"E01", level:"中", type:"mc",
   stem:String.raw`\((-2a^2)^3=\)？`,
   opts:[String.raw`\(-8a^6\)`,String.raw`\(-6a^6\)`,String.raw`\(8a^6\)`,String.raw`\(-8a^5\)`], ans:[0],
   reasons:[String.raw`係數 \(-2\) 沒有三次方，而是乘 \(3\)`,"負數的奇數次方忘了是負的",String.raw`\((a^2)^3\) 的指數用加的`], key:0,
   exp:String.raw`\((-2a^2)^3=(-2)^3\cdot(a^2)^3=-8a^6\)。`},

  // E02 零指數與負整數指數
  {id:"E02-1", tag:"E02", level:"易", type:"tf",
   stem:String.raw`若 \(a\neq 0\)，則 \(a^0=0\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:[String.raw`以為 \(0\) 次方就等於 \(0\)`,String.raw`和「\(0\) 乘任何數都是 \(0\)」搞混`,String.raw`忘了 \(a^0=1\) 的定義`], key:0,
   exp:String.raw`定義 \(a^0=1\)（\(a\neq 0\)）。這樣 \(a^m\div a^m=a^{m-m}=a^0\) 才會等於 \(1\)。`},
  {id:"E02-2", tag:"E02", level:"易", type:"mc",
   stem:String.raw`\(2^{-3}=\)？`,
   opts:[String.raw`\(\dfrac{1}{8}\)`,String.raw`\(-8\)`,String.raw`\(-6\)`,String.raw`\(\dfrac{1}{6}\)`], ans:[0],
   reasons:["把負指數當成負號",String.raw`把 \(2^{-3}\) 算成 \(2\times(-3)\)`,"取倒數後次方算錯"], key:0,
   exp:String.raw`\(a^{-n}=\dfrac{1}{a^n}\)，所以 \(2^{-3}=\dfrac{1}{2^3}=\dfrac{1}{8}\)。`},
  {id:"E02-3", tag:"E02", level:"中", type:"mc",
   stem:String.raw`\(\left(\dfrac{1}{3}\right)^{-2}=\)？`,
   opts:[String.raw`\(9\)`,String.raw`\(\dfrac{1}{9}\)`,String.raw`\(-9\)`,String.raw`\(-\dfrac{1}{9}\)`], ans:[0],
   reasons:["把負指數當成負號","不知道負指數要取倒數","倒數取了兩次又翻回來"], key:1,
   exp:String.raw`\(\left(\dfrac{1}{3}\right)^{-2}=\dfrac{1}{\left(\frac{1}{3}\right)^2}=\dfrac{1}{\frac{1}{9}}=9\)，也就是 \(3^2=9\)。`},

  // E03 n 次方根
  {id:"E03-1", tag:"E03", level:"易", type:"tf",
   stem:String.raw`方程式 \(x^5=2\) 有唯一的正實根 \(\sqrt[5]{2}\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["以為奇數次方程式有兩個實根",String.raw`以為 \(n\) 次方程式就有 \(n\) 個正實根`,String.raw`不熟 \(n\) 次方根的定義`], key:1,
   exp:String.raw`當 \(a\gt 0\)、\(n\ge 2\) 時，\(x^n=a\) 恰有一個正實根，記作 \(\sqrt[n]{a}\)。`},
  {id:"E03-2", tag:"E03", level:"中", type:"mc",
   stem:`下列何者<b>不是</b>實數？`,
   opts:[String.raw`\(\sqrt[3]{-8}\)`,String.raw`\(\sqrt[4]{16}\)`,String.raw`\(\sqrt{-4}\)`,String.raw`\(\sqrt[5]{-1}\)`], ans:[2],
   reasons:["以為負數不能開任何次方根","以為負數開偶次方根也有實數",String.raw`以為 \(\sqrt[3]{-8}\) 不存在`], key:1,
   exp:String.raw`負數可以開奇次方根：\(\sqrt[3]{-8}=-2\)、\(\sqrt[5]{-1}=-1\)；\(\sqrt[4]{16}=2\)。<br>負數開偶次方根在實數中不存在，所以 \(\sqrt{-4}\) 不是實數。`},
  {id:"E03-3", tag:"E03", level:"易", type:"mc",
   stem:String.raw`\(\sqrt[4]{81}=\)？`,
   opts:[String.raw`\(3\)`,String.raw`\(\pm 3\)`,String.raw`\(9\)`,String.raw`\(-3\)`], ans:[0],
   reasons:[String.raw`以為正 \(4\) 次方根要寫 \(\pm\)`,String.raw`把 \(4\) 次方根當成平方根`,"開方後的正負號弄錯"], key:0,
   exp:String.raw`\(3^4=81\)，而 \(\sqrt[4]{81}\) 指的是正的 \(4\) 次方根，所以是 \(3\)。`},

  // E04 有理數指數的定義
  {id:"E04-1", tag:"E04", level:"中", type:"tf",
   stem:String.raw`\(\sqrt[3]{-27}=(-27)^{\frac{1}{3}}\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:["忘了有理數指數的底數必須是正數","以為根號和分數指數一定可以互換",String.raw`把 \(\sqrt[3]{-27}\) 算錯`], key:0,
   exp:String.raw`有理數指數 \(a^{\frac{m}{n}}\) 的定義要求 \(a\gt 0\)，所以 \((-27)^{\frac{1}{3}}\) 沒有定義。<br>（\(\sqrt[3]{-27}=-3\) 本身沒問題，但不能寫成分數指數。）`},
  {id:"E04-2", tag:"E04", level:"易", type:"mc",
   stem:String.raw`\(8^{\frac{2}{3}}=\)？`,
   opts:[String.raw`\(4\)`,String.raw`\(\dfrac{16}{3}\)`,String.raw`\(64\)`,String.raw`\(2\)`], ans:[0],
   reasons:[String.raw`把 \(\dfrac{2}{3}\) 次方當成乘以 \(\dfrac{2}{3}\)`,"只平方，忘了開立方","開立方後忘了平方"], key:0,
   exp:String.raw`\(8^{\frac{2}{3}}=\left(\sqrt[3]{8}\right)^2=2^2=4\)。`},
  {id:"E04-3", tag:"E04", level:"中", type:"mc",
   stem:String.raw`\(27^{-\frac{2}{3}}=\)？`,
   opts:[String.raw`\(\dfrac{1}{9}\)`,String.raw`\(-9\)`,String.raw`\(9\)`,String.raw`\(-18\)`], ans:[0],
   reasons:["把負指數當成負號",String.raw`\(\dfrac{2}{3}\) 次方算錯`,"忘了取倒數"], key:0,
   exp:String.raw`\(27^{-\frac{2}{3}}=\dfrac{1}{27^{\frac{2}{3}}}=\dfrac{1}{(\sqrt[3]{27})^2}=\dfrac{1}{9}\)。`},

  // E05 有理數指數律的化簡
  {id:"E05-1", tag:"E05", level:"易", type:"mc",
   stem:String.raw`若 \(a\gt 0\)，則 \(a^{\frac{1}{2}}\cdot a^{\frac{1}{3}}=\)？`,
   opts:[String.raw`\(a^{\frac{5}{6}}\)`,String.raw`\(a^{\frac{1}{6}}\)`,String.raw`\(a^{\frac{2}{5}}\)`,String.raw`\(a^{\frac{1}{5}}\)`], ans:[0],
   reasons:["相乘時把指數相乘","分數相加時分子加分子、分母加分母","通分算錯"], key:1,
   exp:String.raw`同底數相乘，指數相加：\(\dfrac{1}{2}+\dfrac{1}{3}=\dfrac{5}{6}\)，所以結果是 \(a^{\frac{5}{6}}\)。`},
  {id:"E05-2", tag:"E05", level:"中", type:"mc",
   stem:String.raw`若 \(a\gt 0\)，則 \(\left(a^{\frac{2}{3}}\right)^{\frac{3}{4}}=\)？`,
   opts:[String.raw`\(a^{\frac{1}{2}}\)`,String.raw`\(a^{\frac{17}{12}}\)`,String.raw`\(a^{\frac{8}{9}}\)`,String.raw`\(a^{2}\)`], ans:[0],
   reasons:["次方的次方用加的","分數相乘算錯","把指數相除"], key:0,
   exp:String.raw`\((a^p)^q=a^{pq}\)：\(\dfrac{2}{3}\times\dfrac{3}{4}=\dfrac{1}{2}\)，所以結果是 \(a^{\frac{1}{2}}\)。`},
  {id:"E05-3", tag:"E05", level:"中", type:"num",
   stem:String.raw`\(4^{\frac{3}{2}}\times 8^{-\frac{1}{3}}=\)？`, ans:"4", unitWord:"",
   reasons:[String.raw`把 \(4^{\frac{3}{2}}\) 算成 \(6\)`,String.raw`把 \(8^{-\frac{1}{3}}\) 的負號當成負數`,"沒有化成同底數"], key:1,
   exp:String.raw`\(4^{\frac{3}{2}}=(\sqrt{4})^3=8\)，\(8^{-\frac{1}{3}}=\dfrac{1}{\sqrt[3]{8}}=\dfrac{1}{2}\)。<br>相乘得 \(8\times\dfrac{1}{2}=4\)。`},

  // E06 實數指數與指數律
  {id:"E06-1", tag:"E06", level:"易", type:"tf",
   stem:String.raw`若 \(a\gt 0\)，則 \(a^{\sqrt{2}}\cdot a^{\sqrt{2}}=a^{2\sqrt{2}}\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["以為無理數指數不能用指數律",String.raw`把指數相乘得到 \(a^2\)`,"以為底數要相乘"], key:0,
   exp:String.raw`實數指數一樣適用指數律：\(a^{\sqrt{2}}\cdot a^{\sqrt{2}}=a^{\sqrt{2}+\sqrt{2}}=a^{2\sqrt{2}}\)。`},
  {id:"E06-2", tag:"E06", level:"中", type:"mc",
   stem:String.raw`\(\left(2^{\sqrt{3}}\right)^{\sqrt{3}}=\)？`,
   opts:[String.raw`\(8\)`,String.raw`\(2^{2\sqrt{3}}\)`,String.raw`\(6\)`,String.raw`\(2^{\sqrt{6}}\)`], ans:[0],
   reasons:["次方的次方用加的",String.raw`\(\sqrt{3}\times\sqrt{3}\) 算錯`,"以為無理數指數不能化簡"], key:0,
   exp:String.raw`\(\left(2^{\sqrt{3}}\right)^{\sqrt{3}}=2^{\sqrt{3}\times\sqrt{3}}=2^3=8\)。`},

  // E07 指數比大小
  {id:"E07-1", tag:"E07", level:"難", type:"mc",
   stem:String.raw`設 \(a=2^{30}\)、\(b=3^{20}\)、\(c=5^{10}\)，則大小關係為？`,
   opts:[String.raw`\(c\lt a\lt b\)`,String.raw`\(a\lt b\lt c\)`,String.raw`\(a\lt c\lt b\)`,String.raw`\(b\lt a\lt c\)`], ans:[0],
   reasons:["沒有先化成相同的指數再比","以為底數大的就比較大","指數化簡時算錯"], key:0,
   exp:String.raw`化成相同指數 \(10\)：\(a=(2^3)^{10}=8^{10}\)、\(b=(3^2)^{10}=9^{10}\)、\(c=5^{10}\)。<br>底數 \(5\lt 8\lt 9\)，所以 \(c\lt a\lt b\)。`},
  {id:"E07-2", tag:"E07", level:"易", type:"tf",
   stem:String.raw`\(\left(\dfrac{1}{2}\right)^3\gt \left(\dfrac{1}{2}\right)^5\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["以為指數越大，值就一定越大",String.raw`忘了底數小於 \(1\) 時大小關係會相反`,"次方算錯"], key:1,
   exp:String.raw`\(\left(\dfrac{1}{2}\right)^3=\dfrac{1}{8}\)、\(\left(\dfrac{1}{2}\right)^5=\dfrac{1}{32}\)，所以前者較大。<br>底數在 \(0\) 和 \(1\) 之間時，指數越大，值越小。`},
  {id:"E07-3", tag:"E07", level:"中", type:"mc",
   stem:String.raw`比較 \(\sqrt{2}\) 與 \(\sqrt[3]{3}\) 的大小：`,
   opts:[String.raw`\(\sqrt{2}\lt \sqrt[3]{3}\)`,String.raw`\(\sqrt{2}\gt \sqrt[3]{3}\)`,"兩者相等","無法比較"], ans:[0],
   reasons:[String.raw`沒有同時取 \(6\) 次方再比較`,"以為根號次數越高，值就越大","以為不同次方根不能比較"], key:0,
   exp:String.raw`同時取 \(6\) 次方：\((\sqrt{2})^6=2^3=8\)、\((\sqrt[3]{3})^6=3^2=9\)。<br>\(8\lt 9\)，所以 \(\sqrt{2}\lt \sqrt[3]{3}\)。`},

  // E08 a^x + a^(−x) 型求值
  {id:"E08-1", tag:"E08", level:"中", type:"num",
   stem:String.raw`若 \(a\gt 0\) 且 \(a^x+a^{-x}=4\)，則 \(a^{2x}+a^{-2x}=\)？`, ans:"14", unitWord:"",
   reasons:[String.raw`平方後忘了減 \(2\)`,String.raw`以為平方後直接是 \(16\)`,String.raw`把 \(a^x\cdot a^{-x}\) 算成 \(0\)`], key:0,
   exp:String.raw`\((a^x+a^{-x})^2=a^{2x}+2+a^{-2x}\)（因為 \(a^x\cdot a^{-x}=1\)）。<br>所以 \(a^{2x}+a^{-2x}=16-2=14\)。`},
  {id:"E08-2", tag:"E08", level:"中", type:"tf",
   stem:String.raw`若 \(a\gt 0\)，則 \(a^{3x}+a^{-3x}=(a^x+a^{-x})(a^{2x}-1+a^{-2x})\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["沒有認出這是立方和公式",String.raw`以為中間項應該是 \(+1\)`,String.raw`忘了 \(a^x\cdot a^{-x}=1\)`], key:0,
   exp:String.raw`立方和公式 \(A^3+B^3=(A+B)(A^2-AB+B^2)\)，取 \(A=a^x\)、\(B=a^{-x}\)，\(AB=1\)：<br>\(a^{3x}+a^{-3x}=(a^x+a^{-x})(a^{2x}-1+a^{-2x})\)。`},

  // E09 指數的情境應用
  {id:"E09-1", tag:"E09", level:"易", type:"mc",
   stem:String.raw`某細菌每 \(1\) 小時數量變為原來的 \(2\) 倍。起始有 \(100\) 隻，\(3\) 小時後有幾隻？`,
   opts:[String.raw`\(800\)`,String.raw`\(600\)`,String.raw`\(300\)`,String.raw`\(900\)`], ans:[0],
   reasons:[String.raw`把「每小時 \(2\) 倍」算成 \(2\times 3\) 倍`,String.raw`把倍數和時間相加`,"次方算錯"], key:0,
   exp:String.raw`每小時乘 \(2\)，\(3\) 小時乘了 \(3\) 次：\(100\times 2^3=800\)。`},
  {id:"E09-2", tag:"E09", level:"中", type:"mc",
   stem:String.raw`某細菌每 \(3\) 小時數量變為原來的 \(2\) 倍。經過 \(1\) 小時，數量變為原來的幾倍？`,
   opts:[String.raw`\(2^{\frac{1}{3}}\)`,String.raw`\(\dfrac{2}{3}\)`,String.raw`\(2^3\)`,String.raw`\(3^{\frac{1}{2}}\)`], ans:[0],
   reasons:["把時間比例直接乘上倍數","不會用分數指數表示","把底數和指數弄反"], key:0,
   exp:String.raw`設每小時變為 \(r\) 倍，則 \(r^3=2\)，所以 \(r=\sqrt[3]{2}=2^{\frac{1}{3}}\)。`},

  /* ---------- 第二批（擴充至 300 題） ---------- */
  // E01
  {id:"E01-4", tag:"E01", level:"易", type:"mc",
   stem:String.raw`若 \(a\neq 0\)，則 \(a^5\div a^2=\)？`,
   opts:[String.raw`\(a^3\)`,String.raw`\(a^{2.5}\)`,String.raw`\(a^7\)`,String.raw`\(a^{10}\)`], ans:[0],
   reasons:["同底數相除時把指數相除","同底數相除時把指數相加","不熟指數律"], key:0,
   exp:String.raw`同底數相除，指數相減：\(a^5\div a^2=a^{5-2}=a^3\)。`},
  {id:"E01-5", tag:"E01", level:"易", type:"tf",
   stem:String.raw`\((ab)^3=a^3b^3\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["以為次方只作用在其中一個字母","把乘法和加法的情況搞混","不熟指數律"], key:0,
   exp:String.raw`\((ab)^n=a^nb^n\)，所以 \((ab)^3=a^3b^3\)。（注意加法不行：\((a+b)^3\neq a^3+b^3\)。）`},
  {id:"E01-6", tag:"E01", level:"中", type:"mc",
   stem:String.raw`\((2^3)^2\times 2^4\div 2^5=\)？`,
   opts:[String.raw`\(2^5\)`,String.raw`\(2^4\)`,String.raw`\(2^{24}\)`,String.raw`\(2^{9}\)`], ans:[0],
   reasons:[String.raw`\((2^3)^2\) 算成 \(2^5\)`,"相除時指數用減法弄錯","把次方的次方用乘再乘"], key:0,
   exp:String.raw`\((2^3)^2=2^6\)，所以原式 \(=2^{6+4-5}=2^5\)。`},
  {id:"E01-7", tag:"E01", level:"易", type:"num",
   stem:String.raw`\(2^{10}=\)？`, ans:"1024", unitWord:"",
   reasons:[String.raw`算成 \(2\times 10\)`,"乘到一半漏乘一次",String.raw`記成 \(1000\)`], key:0,
   exp:String.raw`\(2^{10}=2^5\times 2^5=32\times 32=1024\)。`},
  {id:"E01-8", tag:"E01", level:"難", type:"num",
   stem:String.raw`若 \(3^x=5\)，則 \(9^{x+1}=\)？`, ans:"225", unitWord:"",
   reasons:[String.raw`沒有把 \(9\) 寫成 \(3^2\)`,String.raw`\(9^{x+1}\) 拆成 \(9^x+9\)`,String.raw`只算到 \(9^x=25\) 就停了`], key:0,
   exp:String.raw`\(9^{x+1}=9^x\times 9=(3^x)^2\times 9=25\times 9=225\)。`},

  // E02
  {id:"E02-4", tag:"E02", level:"易", type:"mc",
   stem:String.raw`\(5^0+5^{-1}=\)？`,
   opts:[String.raw`\(\dfrac{6}{5}\)`,String.raw`\(\dfrac{1}{5}\)`,String.raw`\(0\)`,String.raw`\(-4\)`], ans:[0],
   reasons:[String.raw`以為 \(5^0=0\)`,"把負指數當成負號","忘了零指數等於 1"], key:0,
   exp:String.raw`\(5^0=1\)、\(5^{-1}=\dfrac{1}{5}\)，相加得 \(\dfrac{6}{5}\)。`},
  {id:"E02-5", tag:"E02", level:"易", type:"tf",
   stem:String.raw`\((-3)^{-2}=\dfrac{1}{9}\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["以為負指數會讓答案變負","以為負數的偶次方是負的","取倒數時算錯"], key:1,
   exp:String.raw`\((-3)^{-2}=\dfrac{1}{(-3)^2}=\dfrac{1}{9}\)。`},
  {id:"E02-6", tag:"E02", level:"中", type:"mc",
   stem:String.raw`\(\left(2^{-1}+3^{-1}\right)^{-1}=\)？`,
   opts:[String.raw`\(\dfrac{6}{5}\)`,String.raw`\(5\)`,String.raw`\(\dfrac{5}{6}\)`,String.raw`\(\dfrac{1}{5}\)`], ans:[0],
   reasons:[String.raw`以為 \((a+b)^{-1}=a^{-1}+b^{-1}\)，變成 \(2+3\)`,"最後忘了再取一次倒數","分數相加算錯"], key:0,
   exp:String.raw`\(2^{-1}+3^{-1}=\dfrac{1}{2}+\dfrac{1}{3}=\dfrac{5}{6}\)，再取倒數得 \(\dfrac{6}{5}\)。`},
  {id:"E02-7", tag:"E02", level:"中", type:"mc",
   stem:String.raw`若 \(a\neq 0\)、\(b\neq 0\)，化簡 \(\dfrac{a^{-2}b^{3}}{a^{3}b^{-1}}=\)？`,
   opts:[String.raw`\(\dfrac{b^4}{a^5}\)`,String.raw`\(\dfrac{b^2}{a}\)`,String.raw`\(a^5b^4\)`,String.raw`\(\dfrac{b^4}{a}\)`], ans:[0],
   reasons:["負指數移到分母時忘了變號","相除時指數相減的方向弄反","把 b 的指數相加錯"], key:0,
   exp:String.raw`\(a^{-2-3}b^{3-(-1)}=a^{-5}b^4=\dfrac{b^4}{a^5}\)。`},
  {id:"E02-8", tag:"E02", level:"中", type:"num",
   stem:String.raw`\((0.5)^{-3}+(0.25)^{-1}=\)？`, ans:"12", unitWord:"",
   reasons:["把負指數當成負號",String.raw`沒有把 \(0.5\) 看成 \(\dfrac{1}{2}\)`,"取倒數後次方算錯"], key:1,
   exp:String.raw`\((0.5)^{-3}=\left(\dfrac{1}{2}\right)^{-3}=2^3=8\)，\((0.25)^{-1}=4\)，相加得 \(12\)。`},

  // E03
  {id:"E03-4", tag:"E03", level:"易", type:"mc",
   stem:String.raw`\(\sqrt[3]{-27}=\)？`,
   opts:[String.raw`\(-3\)`,String.raw`\(3\)`,String.raw`\(\pm 3\)`,"不存在"], ans:[0],
   reasons:["以為負數不能開立方根","以為立方根要寫正負","開方後正負號弄錯"], key:0,
   exp:String.raw`\((-3)^3=-27\)，所以 \(\sqrt[3]{-27}=-3\)。負數可以開奇次方根。`},
  {id:"E03-5", tag:"E03", level:"易", type:"tf",
   stem:String.raw`\(\sqrt{16}=\pm 4\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:[String.raw`把「\(16\) 的平方根」和「\(\sqrt{16}\)」搞混`,String.raw`以為根號一定要寫 \(\pm\)`,"不熟根號的定義"], key:0,
   exp:String.raw`\(16\) 的平方根是 \(\pm 4\)，但符號 \(\sqrt{16}\) 只代表正的那一個，所以 \(\sqrt{16}=4\)。`},
  {id:"E03-6", tag:"E03", level:"中", type:"mc",
   stem:String.raw`方程式 \(x^4=16\) 的實數解為？`,
   opts:[String.raw`\(x=2\) 或 \(x=-2\)`,String.raw`\(x=2\)`,String.raw`\(x=\pm 4\)`,String.raw`\(x=4\)`], ans:[0],
   reasons:["只寫出正的解",String.raw`把 \(4\) 次方根當成平方根`,String.raw`把 \(16\div 4\) 當成答案`], key:0,
   exp:String.raw`\(x^4=16\) 的實數解是 \(\pm\sqrt[4]{16}=\pm 2\)。偶次方程式的正實數會有一正一負兩個實數解。`},
  {id:"E03-7", tag:"E03", level:"難", type:"mc",
   stem:String.raw`\(\sqrt[6]{(-2)^6}=\)？`,
   opts:[String.raw`\(2\)`,String.raw`\(-2\)`,String.raw`\(\pm 2\)`,String.raw`\(64\)`], ans:[0],
   reasons:[String.raw`以為根號和次方可以直接抵消，得到 \(-2\)`,"以為偶次方根要寫正負","只算了根號裡面"], key:0,
   exp:String.raw`\((-2)^6=64\)，而 \(\sqrt[6]{64}\) 是正的 \(6\) 次方根，等於 \(2\)。<br>偶次方根：\(\sqrt[n]{a^n}=|a|\)。`},
  {id:"E03-8", tag:"E03", level:"中", type:"mc",
   stem:String.raw`下列何者是 \(64\) 的所有實數 \(6\) 次方根？`,
   opts:[String.raw`\(2\) 與 \(-2\)`,String.raw`\(2\)`,String.raw`\(8\) 與 \(-8\)`,String.raw`\(\sqrt[6]{64}\) 與 \(\sqrt[3]{64}\)`], ans:[0],
   reasons:[String.raw`把「\(6\) 次方根」和「\(\sqrt[6]{\ }\)」搞混，只取正的`,"把 6 次方根當成平方根","以為兩個不同的根號都是答案"], key:0,
   exp:String.raw`\(x^6=64\) 的實數解是 \(\pm 2\)，所以 \(64\) 的實數 \(6\) 次方根是 \(2\) 與 \(-2\)；符號 \(\sqrt[6]{64}\) 只代表正的 \(2\)。`},

  // E04
  {id:"E04-4", tag:"E04", level:"易", type:"mc",
   stem:String.raw`\(9^{\frac{1}{2}}=\)？`,
   opts:[String.raw`\(3\)`,String.raw`\(4.5\)`,String.raw`\(81\)`,String.raw`\(\dfrac{1}{3}\)`], ans:[0],
   reasons:[String.raw`把 \(\dfrac{1}{2}\) 次方當成除以 \(2\)`,"把開方當成平方","把分數指數當成負指數"], key:0,
   exp:String.raw`\(9^{\frac{1}{2}}=\sqrt{9}=3\)。`},
  {id:"E04-5", tag:"E04", level:"易", type:"mc",
   stem:String.raw`若 \(a\gt 0\)，則 \(\sqrt[3]{a^2}\) 寫成指數形式為？`,
   opts:[String.raw`\(a^{\frac{2}{3}}\)`,String.raw`\(a^{\frac{3}{2}}\)`,String.raw`\(a^{6}\)`,String.raw`\(a^{-\frac{2}{3}}\)`], ans:[0],
   reasons:["分子分母放反了","把根號次數和次方相乘","以為根號要變成負指數"], key:0,
   exp:String.raw`\(\sqrt[n]{a^m}=a^{\frac{m}{n}}\)，所以 \(\sqrt[3]{a^2}=a^{\frac{2}{3}}\)。`},
  {id:"E04-6", tag:"E04", level:"中", type:"mc",
   stem:String.raw`\(16^{\frac{3}{4}}=\)？`,
   opts:[String.raw`\(8\)`,String.raw`\(12\)`,String.raw`\(4\)`,String.raw`\(64\)`], ans:[0],
   reasons:[String.raw`把 \(\dfrac{3}{4}\) 次方當成乘以 \(\dfrac{3}{4}\)`,"只開方忘了再三次方","先三次方再開方時算錯"], key:0,
   exp:String.raw`\(16^{\frac{3}{4}}=\left(\sqrt[4]{16}\right)^3=2^3=8\)。`},
  {id:"E04-7", tag:"E04", level:"中", type:"mc",
   stem:String.raw`\(\left(\dfrac{1}{8}\right)^{-\frac{2}{3}}=\)？`,
   opts:[String.raw`\(4\)`,String.raw`\(\dfrac{1}{4}\)`,String.raw`\(-4\)`,String.raw`\(16\)`], ans:[0],
   reasons:["負指數忘了取倒數","把負指數當成負號","開立方後次方算錯"], key:0,
   exp:String.raw`\(\left(\dfrac{1}{8}\right)^{-\frac{2}{3}}=8^{\frac{2}{3}}=\left(\sqrt[3]{8}\right)^2=4\)。`},
  {id:"E04-8", tag:"E04", level:"難", type:"num",
   stem:String.raw`\(32^{0.6}=\)？`, ans:"8", unitWord:"",
   reasons:[String.raw`沒想到把 \(0.6\) 寫成 \(\dfrac{3}{5}\)`,String.raw`把 \(32^{0.6}\) 算成 \(32\times 0.6\)`,"開 5 次方根後次方算錯"], key:0,
   exp:String.raw`\(0.6=\dfrac{3}{5}\)，\(32^{\frac{3}{5}}=\left(\sqrt[5]{32}\right)^3=2^3=8\)。`},

  // E05
  {id:"E05-4", tag:"E05", level:"易", type:"mc",
   stem:String.raw`若 \(a\gt 0\)，則 \(a^{\frac{1}{2}}\cdot a^{\frac{1}{2}}=\)？`,
   opts:[String.raw`\(a\)`,String.raw`\(a^{\frac{1}{4}}\)`,String.raw`\(2a^{\frac{1}{2}}\)`,String.raw`\(a^2\)`], ans:[0],
   reasons:["相乘時把指數相乘","把相乘當成相加","不熟分數指數"], key:0,
   exp:String.raw`指數相加：\(\dfrac{1}{2}+\dfrac{1}{2}=1\)，所以結果是 \(a\)。也就是 \(\sqrt{a}\cdot\sqrt{a}=a\)。`},
  {id:"E05-5", tag:"E05", level:"中", type:"mc",
   stem:String.raw`若 \(a,b\gt 0\)，則 \(\left(a^{\frac{1}{3}}b^{\frac{1}{2}}\right)^6=\)？`,
   opts:[String.raw`\(a^2b^3\)`,String.raw`\(a^{\frac{1}{18}}b^{\frac{1}{12}}\)`,String.raw`\(a^6b^6\)`,String.raw`\(a^3b^2\)`], ans:[0],
   reasons:["次方的次方用了除法","只對其中一個字母乘次方","分數乘整數算錯"], key:0,
   exp:String.raw`\(\left(a^{\frac{1}{3}}\right)^6=a^2\)、\(\left(b^{\frac{1}{2}}\right)^6=b^3\)，所以結果是 \(a^2b^3\)。`},
  {id:"E05-6", tag:"E05", level:"難", type:"mc",
   stem:String.raw`若 \(a\gt 0\)，則 \(\dfrac{\sqrt{a}\cdot\sqrt[3]{a}}{\sqrt[6]{a}}=\)？`,
   opts:[String.raw`\(a^{\frac{2}{3}}\)`,String.raw`\(a\)`,String.raw`\(a^{\frac{1}{2}}\)`,String.raw`\(a^{\frac{1}{36}}\)`], ans:[0],
   reasons:["沒有先把根號都化成分數指數","分數通分算錯","相除時指數相減的方向弄反"], key:1,
   exp:String.raw`\(a^{\frac{1}{2}+\frac{1}{3}-\frac{1}{6}}=a^{\frac{3+2-1}{6}}=a^{\frac{4}{6}}=a^{\frac{2}{3}}\)。`},
  {id:"E05-7", tag:"E05", level:"難", type:"num",
   stem:String.raw`\(\left(\sqrt{2}\cdot\sqrt[3]{4}\cdot\sqrt[6]{2}\right)^3=\)？`, ans:"16", unitWord:"",
   reasons:[String.raw`沒有把 \(\sqrt[3]{4}\) 寫成 \(2^{\frac{2}{3}}\)`,"分數指數相加算錯","最後三次方算錯"], key:0,
   exp:String.raw`\(2^{\frac{1}{2}}\cdot 2^{\frac{2}{3}}\cdot 2^{\frac{1}{6}}=2^{\frac{3+4+1}{6}}=2^{\frac{4}{3}}\)，三次方得 \(2^4=16\)。`},

  // E06
  {id:"E06-3", tag:"E06", level:"易", type:"tf",
   stem:String.raw`\(2^{\sqrt{2}}\cdot 2^{-\sqrt{2}}=1\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["以為無理數指數不能用指數律",String.raw`以為結果是 \(0\)`,"把負指數當成負號"], key:1,
   exp:String.raw`\(2^{\sqrt{2}+(-\sqrt{2})}=2^0=1\)。`},
  {id:"E06-4", tag:"E06", level:"中", type:"mc",
   stem:String.raw`\(\left(3^{\sqrt{2}}\right)^{\sqrt{8}}=\)？`,
   opts:[String.raw`\(81\)`,String.raw`\(3^{\sqrt{10}}\)`,String.raw`\(3^{2\sqrt{2}}\)`,String.raw`\(3^{16}\)`], ans:[0],
   reasons:["次方的次方用加的",String.raw`\(\sqrt{2}\times\sqrt{8}\) 算錯`,"以為無理數指數不能化簡"], key:1,
   exp:String.raw`\(\sqrt{2}\times\sqrt{8}=\sqrt{16}=4\)，所以結果是 \(3^4=81\)。`},
  {id:"E06-5", tag:"E06", level:"易", type:"mc",
   stem:String.raw`\(5^{1+\sqrt{3}}\div 5^{\sqrt{3}}=\)？`,
   opts:[String.raw`\(5\)`,String.raw`\(5^{\sqrt{3}}\)`,String.raw`\(1\)`,String.raw`\(5^{1+2\sqrt{3}}\)`], ans:[0],
   reasons:["相除時把指數相加","以為無理數指數不能相減","指數相減後算錯"], key:0,
   exp:String.raw`\(5^{(1+\sqrt{3})-\sqrt{3}}=5^1=5\)。`},

  // E07
  {id:"E07-4", tag:"E07", level:"易", type:"tf",
   stem:String.raw`\(2^{10}\gt 10^3\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:[String.raw`以為底數 \(10\) 比較大，結果就比較大`,String.raw`\(2^{10}\) 算錯`,"不會比較不同底數的次方"], key:0,
   exp:String.raw`\(2^{10}=1024\gt 1000=10^3\)。`},
  {id:"E07-5", tag:"E07", level:"中", type:"mc",
   stem:String.raw`設 \(a=2^{0.5}\)、\(b=2^{0.3}\)、\(c=2^{-1}\)，則大小關係為？`,
   opts:[String.raw`\(c\lt b\lt a\)`,String.raw`\(a\lt b\lt c\)`,String.raw`\(b\lt a\lt c\)`,String.raw`\(c\lt a\lt b\)`], ans:[0],
   reasons:["底數大於 1 時，大小關係判斷反了","把負指數當成比較大","沒注意到底數相同可以直接比指數"], key:0,
   exp:String.raw`底數 \(2\gt 1\)，指數越大值越大：\(-1\lt 0.3\lt 0.5\)，所以 \(c\lt b\lt a\)。`},
  {id:"E07-6", tag:"E07", level:"中", type:"mc",
   stem:String.raw`將 \((0.5)^{2}\)、\((0.5)^{-1}\)、\((0.5)^{0}\) 由小到大排列：`,
   opts:[String.raw`\((0.5)^{2}\lt(0.5)^{0}\lt(0.5)^{-1}\)`,String.raw`\((0.5)^{-1}\lt(0.5)^{0}\lt(0.5)^{2}\)`,String.raw`\((0.5)^{0}\lt(0.5)^{2}\lt(0.5)^{-1}\)`,String.raw`\((0.5)^{2}\lt(0.5)^{-1}\lt(0.5)^{0}\)`], ans:[0],
   reasons:["忘了底數小於 1 時，指數越大值越小",String.raw`以為 \((0.5)^0=0\)`,"把負指數當成負數"], key:0,
   exp:String.raw`\((0.5)^2=0.25\)、\((0.5)^0=1\)、\((0.5)^{-1}=2\)，所以由小到大如第一個選項。`},
  {id:"E07-7", tag:"E07", level:"難", type:"mc",
   stem:String.raw`設 \(a=3^{40}\)、\(b=4^{30}\)、\(c=5^{20}\)，則大小關係為？`,
   opts:[String.raw`\(c\lt b\lt a\)`,String.raw`\(a\lt b\lt c\)`,String.raw`\(b\lt c\lt a\)`,String.raw`\(c\lt a\lt b\)`], ans:[0],
   reasons:["沒有化成相同的指數再比","以為底數大的就比較大","化成相同指數時算錯"], key:1,
   exp:String.raw`都化成 \(10\) 次方：\(a=(3^4)^{10}=81^{10}\)、\(b=(4^3)^{10}=64^{10}\)、\(c=(5^2)^{10}=25^{10}\)。<br>\(25\lt 64\lt 81\)，所以 \(c\lt b\lt a\)。`},
  {id:"E07-8", tag:"E07", level:"難", type:"mc",
   stem:String.raw`設 \(a=2^{\frac{1}{2}}\)、\(b=3^{\frac{1}{3}}\)、\(c=5^{\frac{1}{5}}\)，則大小關係為？`,
   opts:[String.raw`\(c\lt a\lt b\)`,String.raw`\(a\lt b\lt c\)`,String.raw`\(c\lt b\lt a\)`,String.raw`\(a\lt c\lt b\)`], ans:[0],
   reasons:[String.raw`沒有同時取 \(30\) 次方再比較`,"以為底數越大值就越大","次方計算錯誤"], key:0,
   exp:String.raw`同取 \(30\) 次方：\(a^{30}=2^{15}=32768\)、\(b^{30}=3^{10}=59049\)、\(c^{30}=5^6=15625\)。<br>所以 \(c\lt a\lt b\)。`},

  // E08
  {id:"E08-3", tag:"E08", level:"中", type:"num",
   stem:String.raw`若 \(a\gt 0\) 且 \(a^{\frac{1}{2}}+a^{-\frac{1}{2}}=3\)，則 \(a+a^{-1}=\)？`, ans:"7", unitWord:"",
   reasons:[String.raw`平方後忘了減 \(2\)`,String.raw`以為平方後直接是 \(9\)`,String.raw`把 \(a^{\frac{1}{2}}\cdot a^{-\frac{1}{2}}\) 算錯`], key:0,
   exp:String.raw`平方：\(a+2+a^{-1}=9\)，所以 \(a+a^{-1}=7\)。`},
  {id:"E08-4", tag:"E08", level:"中", type:"mc",
   stem:String.raw`若 \(2^x+2^{-x}=3\)，則 \(4^x+4^{-x}=\)？`,
   opts:[String.raw`\(7\)`,String.raw`\(9\)`,String.raw`\(11\)`,String.raw`\(5\)`], ans:[0],
   reasons:[String.raw`平方後忘了減 \(2\)`,String.raw`沒想到 \(4^x=(2^x)^2\)`,"平方展開時中間項算錯"], key:0,
   exp:String.raw`\(4^x+4^{-x}=(2^x+2^{-x})^2-2=9-2=7\)。`},
  {id:"E08-5", tag:"E08", level:"難", type:"mc",
   stem:String.raw`若 \(a\gt 0\) 且 \(a^{2x}=3\)，則 \(\dfrac{a^{3x}+a^{-3x}}{a^{x}+a^{-x}}=\)？`,
   opts:[String.raw`\(\dfrac{7}{3}\)`,String.raw`\(3\)`,String.raw`\(\dfrac{10}{3}\)`,String.raw`\(2\)`], ans:[0],
   reasons:["沒想到用立方和公式約分","約分後中間項正負號弄錯",String.raw`\(a^{-2x}\) 算錯`], key:0,
   exp:String.raw`立方和公式：分子 \(=(a^x+a^{-x})(a^{2x}-1+a^{-2x})\)，約分後得 \(a^{2x}-1+a^{-2x}=3-1+\dfrac{1}{3}=\dfrac{7}{3}\)。`},
  {id:"E08-6", tag:"E08", level:"中", type:"num",
   stem:String.raw`若 \(x\gt 0\) 且 \(x^{\frac{1}{2}}-x^{-\frac{1}{2}}=2\)，則 \(x+x^{-1}=\)？`, ans:"6", unitWord:"",
   reasons:[String.raw`平方後中間項應該是 \(-2\)，要加回 \(2\)`,String.raw`直接把 \(2\) 平方`,String.raw`以為要減 \(2\)`], key:0,
   exp:String.raw`平方：\(x-2+x^{-1}=4\)，所以 \(x+x^{-1}=6\)。`},

  // E09
  {id:"E09-3", tag:"E09", level:"易", type:"mc",
   stem:String.raw`某存款每年本利和變為前一年的 \(1.1\) 倍。本金 \(10000\) 元，\(2\) 年後本利和為多少元？`,
   opts:[String.raw`\(12100\)`,String.raw`\(12000\)`,String.raw`\(11000\)`,String.raw`\(12210\)`], ans:[0],
   reasons:["每年都只用本金算利息（單利）","只算了 1 年","乘法算錯"], key:0,
   exp:String.raw`\(10000\times 1.1^2=10000\times 1.21=12100\)。`},
  {id:"E09-4", tag:"E09", level:"中", type:"mc",
   stem:String.raw`某放射性物質每 \(5\) 年剩下原來的一半。經過 \(20\) 年後，剩下原來的幾分之幾？`,
   opts:[String.raw`\(\dfrac{1}{16}\)`,String.raw`\(\dfrac{1}{4}\)`,String.raw`\(\dfrac{1}{8}\)`,String.raw`\(\dfrac{1}{20}\)`], ans:[0],
   reasons:["半衰的次數算錯","把剩下的比例用減法算","把年數直接當成分母"], key:0,
   exp:String.raw`\(20\) 年經過 \(4\) 次半衰期：\(\left(\dfrac{1}{2}\right)^4=\dfrac{1}{16}\)。`},
  {id:"E09-5", tag:"E09", level:"中", type:"mc",
   stem:String.raw`某細菌每 \(2\) 小時數量變為原來的 \(3\) 倍。經過 \(5\) 小時，數量變為原來的幾倍？`,
   opts:[String.raw`\(9\sqrt{3}\)`,String.raw`\(\dfrac{15}{2}\)`,String.raw`\(3^5\)`,String.raw`\(3^{\frac{2}{5}}\)`], ans:[0],
   reasons:["把時間比例直接乘上倍數",String.raw`指數寫成 \(\dfrac{2}{5}\)，分子分母放反`,"把每小時當成一個週期"], key:1,
   exp:String.raw`\(5\) 小時是 \(\dfrac{5}{2}\) 個週期：\(3^{\frac{5}{2}}=3^2\cdot 3^{\frac{1}{2}}=9\sqrt{3}\)。`},
  {id:"E09-6", tag:"E09", level:"難", type:"mc",
   stem:String.raw`某細菌每小時數量變為原來的 \(2\) 倍。若 \(10\) 小時後細菌恰好裝滿容器，則幾小時後恰好裝滿一半？`,
   opts:[String.raw`\(9\)`,String.raw`\(5\)`,String.raw`\(8\)`,String.raw`\(9.5\)`], ans:[0],
   reasons:["直覺以為一半的時間就是一半的量","倍增的方向想反了","把倍增當成每小時增加固定的量"], key:1,
   exp:String.raw`每小時變 \(2\) 倍，所以裝滿前 \(1\) 小時（第 \(9\) 小時）剛好是一半。`},
  {id:"E09-7", tag:"E09", level:"易", type:"tf",
   stem:String.raw`一張紙對折 \(n\) 次後，厚度變為原來的 \(2^n\) 倍。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["以為是 2n 倍","以為是 n² 倍","不會把重複倍增寫成指數"], key:0,
   exp:String.raw`每對折一次厚度變 \(2\) 倍，對折 \(n\) 次就是 \(2\times 2\times\cdots\times 2=2^n\) 倍。`}
];
