/* 單元02 絕對值　題庫初稿
   格式同 unit01.js。數學式一律用 LaTeX，行內公式以 \( ... \) 包起來。 */
window.BANK_UNIT02 = [
  // A01 數線上的分點公式
  {id:"A01-1", tag:"A01", level:"中", type:"mc",
   stem:String.raw`數線上 \(A(-2)\)、\(B(8)\)，點 \(P\) 在 \(\overline{AB}\) 上且 \(\overline{AP}:\overline{PB}=2:3\)，則 \(P\) 的坐標為？`,
   opts:[String.raw`\(2\)`,String.raw`\(4\)`,String.raw`\(3\)`,String.raw`\(6\)`], ans:[0],
   reasons:[String.raw`\(m:n\) 對應的端點對調`,"直接取了中點",String.raw`分母沒有用 \(m+n\)`], key:0,
   exp:String.raw`分點公式：\(x=\dfrac{n\cdot a+m\cdot b}{m+n}=\dfrac{3\cdot(-2)+2\cdot 8}{5}=\dfrac{10}{5}=2\)。<br>（靠近 \(A\) 的比例是 \(2\)，所以 \(P\) 離 \(A\) 比較近。）`},
  {id:"A01-2", tag:"A01", level:"中", type:"mc",
   stem:String.raw`數線上 \(A(1)\)、\(B(13)\)，點 \(P\) 在 \(\overline{AB}\) 上且 \(\overline{AP}=3\overline{PB}\)，則 \(P\) 的坐標為？`,
   opts:[String.raw`\(10\)`,String.raw`\(4\)`,String.raw`\(7\)`,String.raw`\(12\)`], ans:[0],
   reasons:[String.raw`把 \(\overline{AP}=3\overline{PB}\) 寫成 \(\overline{AP}:\overline{PB}=1:3\)`,"分點公式的權重放錯端點","直接取了中點"], key:0,
   exp:String.raw`\(\overline{AP}:\overline{PB}=3:1\)，所以 \(x=\dfrac{1\cdot 1+3\cdot 13}{3+1}=\dfrac{40}{4}=10\)。`},

  // A02 絕對值的幾何意義
  {id:"A02-1", tag:"A02", level:"易", type:"tf",
   stem:String.raw`數線上 \(A(a)\) 與 \(B(-4)\) 的距離為 \(|a+4|\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:[String.raw`把 \(|a+4|\) 看成到 \(4\) 的距離`,String.raw`以為距離一定要寫成 \(|a-4|\)`,"忘了距離是兩坐標相減再取絕對值"], key:0,
   exp:String.raw`\(\overline{AB}=|a-(-4)|=|a+4|\)。`},
  {id:"A02-2", tag:"A02", level:"易", type:"mc",
   stem:String.raw`\(|x-3|\) 的幾何意義是？`,
   opts:[String.raw`數線上 \(x\) 到 \(3\) 的距離`,String.raw`數線上 \(x\) 到 \(-3\) 的距離`,String.raw`數線上 \(x\) 到原點的距離減 \(3\)`,String.raw`\(x\) 與 \(3\) 的和`], ans:[0],
   reasons:[String.raw`把 \(|x-3|\) 當成到 \(-3\) 的距離`,"以為絕對值只是「把負號拿掉」","忘了距離是兩坐標相減"], key:0,
   exp:String.raw`\(|x-a|\) 表示數線上點 \(x\) 與點 \(a\) 的距離，所以 \(|x-3|\) 是 \(x\) 到 \(3\) 的距離。`},
  {id:"A02-3", tag:"A02", level:"易", type:"tf",
   stem:String.raw`在數線上，到點 \(A(a)\) 的距離等於 \(1\) 的點恰有兩個。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["只想到右邊的那個點","以為距離方程式只有一個解",String.raw`忘了 \(|x-a|=1\) 有兩個解`], key:0,
   exp:String.raw`\(|x-a|=1\Rightarrow x=a+1\) 或 \(x=a-1\)，左右各一個，恰有兩點。`},

  // A03 絕對值的代數意義與化簡
  {id:"A03-1", tag:"A03", level:"中", type:"mc",
   stem:String.raw`已知 \(x\lt 1\)，化簡 \(|x-1|+(x-1)=\)？`,
   opts:[String.raw`\(0\)`,String.raw`\(2x-2\)`,String.raw`\(-2x+2\)`,String.raw`\(2\)`], ans:[0],
   reasons:["沒有先判斷 x − 1 的正負就直接去掉絕對值","去絕對值時只把一部分變號",String.raw`把 \(x\lt 1\) 當成 \(x-1\gt 0\)`], key:0,
   exp:String.raw`\(x\lt 1\Rightarrow x-1\lt 0\)，所以 \(|x-1|=-(x-1)\)。<br>原式 \(=-(x-1)+(x-1)=0\)。`},
  {id:"A03-2", tag:"A03", level:"中", type:"mc",
   stem:String.raw`若 \(-2\lt x\lt 3\)，化簡 \(|x+2|+|x-3|=\)？`,
   opts:[String.raw`\(5\)`,String.raw`\(2x-1\)`,String.raw`\(-2x+1\)`,String.raw`\(1\)`], ans:[0],
   reasons:["兩個絕對值都直接拿掉，沒有判斷正負",String.raw`\(x-3\) 的正負判斷錯`,"合併同類項算錯"], key:1,
   exp:String.raw`\(x+2\gt 0\)、\(x-3\lt 0\)，所以原式 \(=(x+2)+(3-x)=5\)。<br>幾何意義：\(x\) 在 \(-2\) 與 \(3\) 之間時，到兩點的距離和就是兩點間的距離 \(5\)。`},

  // A04 √(a²) = |a|
  {id:"A04-1", tag:"A04", level:"易", type:"tf",
   stem:String.raw`\(\sqrt{(\sqrt{3}-\sqrt{5})^2}=\sqrt{3}-\sqrt{5}\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:[String.raw`忘了 \(\sqrt{a^2}=|a|\)`,String.raw`沒有先判斷 \(\sqrt{3}-\sqrt{5}\) 是負數`,"以為根號和平方可以直接抵消"], key:0,
   exp:String.raw`\(\sqrt{3}\lt \sqrt{5}\)，所以 \(\sqrt{3}-\sqrt{5}\lt 0\)。<br>\(\sqrt{(\sqrt{3}-\sqrt{5})^2}=|\sqrt{3}-\sqrt{5}|=\sqrt{5}-\sqrt{3}\)。`},
  {id:"A04-2", tag:"A04", level:"中", type:"mc",
   stem:String.raw`若 \(x\lt 0\)，則 \(\sqrt{x^2}+|x|=\)？`,
   opts:[String.raw`\(-2x\)`,String.raw`\(2x\)`,String.raw`\(0\)`,String.raw`\(x^2\)`], ans:[0],
   reasons:[String.raw`以為 \(\sqrt{x^2}=x\)`,String.raw`忘了 \(x\lt 0\) 時 \(|x|=-x\)`,"以為兩項會互相抵消"], key:0,
   exp:String.raw`\(\sqrt{x^2}=|x|\)，而 \(x\lt 0\) 時 \(|x|=-x\)。<br>原式 \(=-x+(-x)=-2x\)（是正數）。`},

  // A05 絕對值的非負性
  {id:"A05-1", tag:"A05", level:"易", type:"tf",
   stem:String.raw`若 \(a\)、\(b\) 為實數，且 \(|a-1|+|b+2|=0\)，則 \(a=1\)、\(b=-2\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["不知道絕對值一定大於或等於 0","以為兩個絕對值可以一正一負互相抵消","解出來的正負號弄錯"], key:1,
   exp:String.raw`\(|a-1|\ge 0\)、\(|b+2|\ge 0\)，兩個非負數相加等於 \(0\)，只能兩個都是 \(0\)。<br>所以 \(a=1\)、\(b=-2\)。`},
  {id:"A05-2", tag:"A05", level:"中", type:"mc",
   stem:String.raw`若實數 \(x\)、\(y\) 滿足 \(|x-2|+(y+3)^2=0\)，則 \(x+y=\)？`,
   opts:[String.raw`\(-1\)`,String.raw`\(5\)`,String.raw`\(1\)`,String.raw`\(-5\)`], ans:[0],
   reasons:["忘了平方和絕對值都大於或等於 0","移項時正負號弄錯","以為有無限多組解"], key:1,
   exp:String.raw`兩項都 \(\ge 0\) 且和為 \(0\)，所以 \(x-2=0\)、\(y+3=0\)。<br>\(x=2\)、\(y=-3\)，\(x+y=-1\)。`},

  // A06 含絕對值的一次方程式
  {id:"A06-1", tag:"A06", level:"易", type:"mc",
   stem:String.raw`方程式 \(|x-3|=5\) 的解為？`,
   opts:[String.raw`\(x=8\) 或 \(x=-2\)`,String.raw`\(x=8\)`,String.raw`\(x=-8\) 或 \(x=2\)`,String.raw`\(x=\pm 5\)`], ans:[0],
   reasons:["只解出一個，漏掉負的那個",String.raw`把 \(x-3=-5\) 解錯`,String.raw`以為解就是 \(\pm 5\)`], key:0,
   exp:String.raw`\(|x-3|=5\Rightarrow x-3=5\) 或 \(x-3=-5\)，得 \(x=8\) 或 \(x=-2\)。<br>幾何意義：到 \(3\) 的距離為 \(5\) 的點。`},
  {id:"A06-2", tag:"A06", level:"中", type:"tf",
   stem:String.raw`方程式 \(|2x+1|=-3\) 的解為 \(x=1\) 或 \(x=-2\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:["沒注意到絕對值不可能等於負數",String.raw`直接把 \(-3\) 拆成 \(\pm 3\) 來解`,"以為無解就是 x = 0"], key:0,
   exp:String.raw`絕對值一定 \(\ge 0\)，不可能等於 \(-3\)，所以方程式無解。`},
  {id:"A06-3", tag:"A06", level:"中", type:"num",
   stem:String.raw`方程式 \(|x-5|=3\) 的所有解的和是多少？`, ans:"10", unitWord:"",
   reasons:["只解出一個解",String.raw`把 \(x-5=-3\) 解錯`,String.raw`把 \(3\) 當成解`], key:0,
   exp:String.raw`\(x-5=3\) 或 \(x-5=-3\)，得 \(x=8\) 或 \(x=2\)，和為 \(10\)。<br>（兩解對稱於 \(5\)，所以和一定是 \(2\times 5\)。）`},

  // A07 |x − a| ≤ k（夾在中間）
  {id:"A07-1", tag:"A07", level:"易", type:"mc",
   stem:String.raw`不等式 \(|x+2|\le 3\) 的解為？`,
   opts:[String.raw`\(-5\le x\le 1\)`,String.raw`\(-1\le x\le 5\)`,String.raw`\(x\le 1\)`,String.raw`\(x\le -5\) 或 \(x\ge 1\)`], ans:[0],
   reasons:[String.raw`把 \(|x+2|\) 看成到 \(2\) 的距離，中心放錯`,"只取一邊的不等式","把「夾在中間」和「分在兩邊」搞反"], key:0,
   exp:String.raw`\(|x+2|\le 3\Rightarrow -3\le x+2\le 3\Rightarrow -5\le x\le 1\)。<br>幾何意義：到 \(-2\) 的距離不超過 \(3\)。`},
  {id:"A07-2", tag:"A07", level:"中", type:"mc",
   stem:String.raw`不等式 \(|2x-1|\lt 5\) 的解為？`,
   opts:[String.raw`\(-2\lt x\lt 3\)`,String.raw`\(-3\lt x\lt 2\)`,String.raw`\(x\lt 3\)`,String.raw`\(-2\le x\le 3\)`], ans:[0],
   reasons:["同除以 2 時沒有每一邊都除","移項時正負號弄錯",String.raw`把 \(\lt \) 和 \(\le\) 搞混`], key:1,
   exp:String.raw`\(-5\lt 2x-1\lt 5\Rightarrow -4\lt 2x\lt 6\Rightarrow -2\lt x\lt 3\)。`},
  {id:"A07-3", tag:"A07", level:"中", type:"num",
   stem:String.raw`滿足 \(|x-4|\le 3\) 的整數 \(x\) 共有幾個？`, ans:"7", unitWord:"個",
   reasons:[String.raw`端點 \(1\) 和 \(7\) 沒有算進去`,String.raw`以為個數就是 \(2\times 3=6\)`,"中心點算錯"], key:1,
   exp:String.raw`\(|x-4|\le 3\Rightarrow 1\le x\le 7\)，整數有 \(1,2,\dots,7\)，共 \(7\) 個。`},

  // A08 |x − a| ≥ k（分在兩邊）
  {id:"A08-1", tag:"A08", level:"易", type:"tf",
   stem:String.raw`化簡 \(|x-3|\ge 2\)，可得 \(x-3\ge\pm 2\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:[String.raw`不知道 \(\ge\) 要拆成「或」的兩個不等式`,"把「或」寫成「且」",String.raw`以為 \(\pm\) 可以直接放進不等式`], key:0,
   exp:String.raw`\(|x-3|\ge 2\Rightarrow x-3\ge 2\) 或 \(x-3\le -2\)，即 \(x\ge 5\) 或 \(x\le 1\)。`},
  {id:"A08-2", tag:"A08", level:"中", type:"mc",
   stem:String.raw`不等式 \(|x-1|\gt 4\) 的解為？`,
   opts:[String.raw`\(x\gt 5\) 或 \(x\lt -3\)`,String.raw`\(-3\lt x\lt 5\)`,String.raw`\(x\gt 5\)`,String.raw`\(x\gt 5\) 且 \(x\lt -3\)`], ans:[0],
   reasons:["把「分在兩邊」寫成「夾在中間」","「或」誤寫成「且」","只取了一邊"], key:0,
   exp:String.raw`到 \(1\) 的距離大於 \(4\)：\(x-1\gt 4\) 或 \(x-1\lt -4\)，即 \(x\gt 5\) 或 \(x\lt -3\)。`},

  // A09 區間記號
  {id:"A09-1", tag:"A09", level:"易", type:"tf",
   stem:String.raw`\(-2\lt x\le 5\) 可記作 \((-2,5]\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["小括號和中括號的意義搞反","以為端點不能一邊包含、一邊不包含","不熟區間記號"], key:0,
   exp:String.raw`不含端點用小括號、含端點用中括號：\(-2\) 不含、\(5\) 含，記作 \((-2,5]\)。`},
  {id:"A09-2", tag:"A09", level:"易", type:"mc",
   stem:String.raw`\(x\ge 3\) 用區間表示為？`,
   opts:[String.raw`\([3,\infty)\)`,String.raw`\((3,\infty)\)`,String.raw`\([3,\infty]\)`,String.raw`\((-\infty,3]\)`], ans:[0],
   reasons:[String.raw`\(\infty\) 用了中括號`,"包含端點卻用了小括號","方向寫反"], key:0,
   exp:String.raw`含 \(3\) 用中括號；\(\infty\) 不是一個數，一定用小括號：\([3,\infty)\)。`},

  // A10 誤差範圍的表示
  {id:"A10-1", tag:"A10", level:"易", type:"mc",
   stem:String.raw`食品標示「請保存於 \(18\pm 2^{\circ}\mathrm{C}\)」，保存溫度 \(x\) 的範圍可表示為？`,
   opts:[String.raw`\(|x-18|\le 2\)`,String.raw`\(|x+18|\le 2\)`,String.raw`\(|x-2|\le 18\)`,String.raw`\(|x-18|\ge 2\)`], ans:[0],
   reasons:["中心和誤差的位置寫反",String.raw`把 \(x-18\) 寫成 \(x+18\)`,"不等號方向弄反"], key:0,
   exp:String.raw`\(18\pm 2\) 表示與 \(18\) 的差距不超過 \(2\)：\(|x-18|\le 2\)，即 \(16\le x\le 20\)。`},
  {id:"A10-2", tag:"A10", level:"中", type:"mc",
   stem:String.raw`不等式 \(|x-a|\le b\) 的解為 \(3\le x\le 11\)，則 \(a+b=\)？`,
   opts:[String.raw`\(11\)`,String.raw`\(15\)`,String.raw`\(7\)`,String.raw`\(14\)`], ans:[0],
   reasons:[String.raw`把區間長度 \(8\) 當成 \(b\)`,"中點算錯",String.raw`把 \(a\)、\(b\) 弄反`], key:0,
   exp:String.raw`中心 \(a=\dfrac{3+11}{2}=7\)，半徑 \(b=\dfrac{11-3}{2}=4\)，所以 \(a+b=11\)。`},

  /* ---------- 第二批（擴充至 300 題） ---------- */
  // A01
  {id:"A01-3", tag:"A01", level:"易", type:"mc",
   stem:String.raw`數線上 \(A(-3)\)、\(B(9)\)，則 \(\overline{AB}\) 中點的坐標為？`,
   opts:[String.raw`\(3\)`,String.raw`\(6\)`,String.raw`\(-6\)`,String.raw`\(12\)`], ans:[0],
   reasons:["中點公式算成兩坐標相減再除以 2","忘了除以 2",String.raw`\(-3\) 的正負號弄錯`], key:0,
   exp:String.raw`中點坐標 \(=\dfrac{-3+9}{2}=3\)。`},
  {id:"A01-4", tag:"A01", level:"中", type:"mc",
   stem:String.raw`數線上 \(A(2)\)、\(B(14)\)，點 \(P\) 在 \(\overline{AB}\) 上且 \(\overline{AP}:\overline{PB}=1:2\)，則 \(P\) 的坐標為？`,
   opts:[String.raw`\(6\)`,String.raw`\(10\)`,String.raw`\(8\)`,String.raw`\(4\)`], ans:[0],
   reasons:[String.raw`\(m:n\) 對應的端點對調`,"直接取了中點",String.raw`分母沒有用 \(m+n\)`], key:0,
   exp:String.raw`\(x=\dfrac{2\cdot 2+1\cdot 14}{1+2}=\dfrac{18}{3}=6\)。也可以想成：\(\overline{AB}=12\)，\(P\) 從 \(A\) 往右走 \(\dfrac{1}{3}\times 12=4\)。`},
  {id:"A01-5", tag:"A01", level:"難", type:"mc",
   stem:String.raw`數線上 \(A(a)\)、\(B(b)\)，點 \(P(4)\) 在 \(\overline{AB}\) 上且 \(\overline{AP}:\overline{PB}=1:3\)，又 \(\overline{AB}\) 的中點為 \(10\)，則 \(b=\)？`,
   opts:[String.raw`\(22\)`,String.raw`\(18\)`,String.raw`\(-2\)`,String.raw`\(14\)`], ans:[0],
   reasons:["分點公式的權重放反","聯立方程式解錯",String.raw`算出 \(a\) 就停了，把 \(a\) 當成答案`], key:0,
   exp:String.raw`分點：\(\dfrac{3a+b}{4}=4\Rightarrow 3a+b=16\)；中點：\(a+b=20\)。<br>相減得 \(2a=-4\)，\(a=-2\)，所以 \(b=22\)。`},
  {id:"A01-6", tag:"A01", level:"中", type:"num",
   stem:String.raw`數線上 \(A(-4)\)、\(B(16)\)，點 \(P\) 在 \(\overline{AB}\) 上且 \(\overline{AP}:\overline{PB}=3:1\)，則 \(P\) 的坐標為？`, ans:"11", unitWord:"",
   reasons:["分點公式的權重放反",String.raw`\(-4\) 的正負號弄錯`,String.raw`分母沒有用 \(m+n\)`], key:0,
   exp:String.raw`\(x=\dfrac{1\cdot(-4)+3\cdot 16}{4}=\dfrac{44}{4}=11\)。`},

  // A02
  {id:"A02-4", tag:"A02", level:"易", type:"mc",
   stem:String.raw`數線上 \(A(-5)\) 與 \(B(3)\) 的距離為？`,
   opts:[String.raw`\(8\)`,String.raw`\(2\)`,String.raw`\(-8\)`,String.raw`\(15\)`], ans:[0],
   reasons:[String.raw`算成 \(-5+3\) 再取絕對值`,"忘了距離一定是正的","把兩坐標相乘"], key:0,
   exp:String.raw`\(\overline{AB}=|3-(-5)|=8\)。`},
  {id:"A02-5", tag:"A02", level:"易", type:"mc",
   stem:String.raw`\(|x+1|\) 表示數線上點 \(x\) 到哪一點的距離？`,
   opts:[String.raw`\(-1\)`,String.raw`\(1\)`,String.raw`\(0\)`,String.raw`\(x+1\)`], ans:[0],
   reasons:[String.raw`看到 \(+1\) 就以為是到 \(1\) 的距離`,"以為絕對值只是把負號拿掉","不熟絕對值的幾何意義"], key:0,
   exp:String.raw`\(|x+1|=|x-(-1)|\)，是 \(x\) 到 \(-1\) 的距離。`},
  {id:"A02-6", tag:"A02", level:"難", type:"num",
   stem:String.raw`數線上到 \(A(-3)\) 與 \(B(5)\) 的距離和為 \(12\) 的點有兩個，其中坐標較大的點坐標是多少？`, ans:"7", unitWord:"",
   reasons:[String.raw`只考慮 \(A\)、\(B\) 之間的點`,"列式時絕對值的正負號弄錯","把距離和當成距離差"], key:0,
   exp:String.raw`\(A\)、\(B\) 之間的點距離和都是 \(8\)，所以點在兩側。<br>在 \(B\) 右側：\((x+3)+(x-5)=12\Rightarrow x=7\)。（左側的點是 \(-5\)。）`},
  {id:"A02-7", tag:"A02", level:"中", type:"num",
   stem:String.raw`\(|x-1|+|x-4|\) 的最小值是多少？`, ans:"3", unitWord:"",
   reasons:[String.raw`以為最小值是 \(0\)`,"沒有用「到兩點距離和」的幾何意義","把兩點距離算錯"], key:0,
   exp:String.raw`\(|x-1|+|x-4|\) 是 \(x\) 到 \(1\) 和到 \(4\) 的距離和。<br>\(x\) 在 \(1\) 與 \(4\) 之間時最小，等於兩點距離 \(3\)。`},

  // A03
  {id:"A03-3", tag:"A03", level:"易", type:"tf",
   stem:String.raw`\(|-7|=-7\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:["以為絕對值會保留負號","不熟絕對值的定義","把絕對值和相反數搞混"], key:0,
   exp:String.raw`絕對值一定 \(\ge 0\)，\(|-7|=7\)。`},
  {id:"A03-4", tag:"A03", level:"中", type:"mc",
   stem:String.raw`若 \(x\gt 3\)，化簡 \(|x-3|+|x+1|=\)？`,
   opts:[String.raw`\(2x-2\)`,String.raw`\(4\)`,String.raw`\(-2x+2\)`,String.raw`\(2x+4\)`], ans:[0],
   reasons:["沒有判斷正負就直接去絕對值","有一個絕對值去掉時多加了負號","合併同類項算錯"], key:1,
   exp:String.raw`\(x\gt 3\) 時，\(x-3\gt 0\)、\(x+1\gt 0\)，原式 \(=(x-3)+(x+1)=2x-2\)。`},
  {id:"A03-5", tag:"A03", level:"難", type:"mc",
   stem:String.raw`若 \(a\lt 0\lt b\)，化簡 \(|a|+|b|-|a-b|=\)？`,
   opts:[String.raw`\(0\)`,String.raw`\(2b\)`,String.raw`\(-2a\)`,String.raw`\(2a-2b\)`], ans:[0],
   reasons:[String.raw`\(a-b\) 的正負判斷錯`,String.raw`以為 \(|a|=a\)`,"去絕對值後正負號整理錯"], key:0,
   exp:String.raw`\(|a|=-a\)、\(|b|=b\)，而 \(a-b\lt 0\)，所以 \(|a-b|=b-a\)。<br>原式 \(=-a+b-(b-a)=0\)。`},
  {id:"A03-6", tag:"A03", level:"中", type:"num",
   stem:String.raw`若 \(1\lt x\lt 4\)，化簡 \(|x-1|+|x-4|\) 的結果是多少？`, ans:"3", unitWord:"",
   reasons:[String.raw`\(x-4\) 的正負判斷錯`,"兩個絕對值都直接拿掉","合併時算錯"], key:0,
   exp:String.raw`\(x-1\gt 0\)、\(x-4\lt 0\)，原式 \(=(x-1)+(4-x)=3\)。`},

  // A04
  {id:"A04-3", tag:"A04", level:"易", type:"tf",
   stem:String.raw`\(\sqrt{(-5)^2}=5\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:[String.raw`以為 \(\sqrt{a^2}=a\)，答案應該是 \(-5\)`,"根號和平方的順序搞混","以為根號裡不能有負數"], key:0,
   exp:String.raw`\(\sqrt{(-5)^2}=\sqrt{25}=5=|-5|\)。`},
  {id:"A04-4", tag:"A04", level:"中", type:"mc",
   stem:String.raw`若 \(1\lt x\lt 3\)，則 \(\sqrt{(x-1)^2}+\sqrt{(x-3)^2}=\)？`,
   opts:[String.raw`\(2\)`,String.raw`\(2x-4\)`,String.raw`\(4-2x\)`,String.raw`\(-2\)`], ans:[0],
   reasons:[String.raw`以為 \(\sqrt{(x-3)^2}=x-3\)`,String.raw`忘了 \(\sqrt{a^2}=|a|\)`,"去絕對值時正負號弄錯"], key:0,
   exp:String.raw`原式 \(=|x-1|+|x-3|=(x-1)+(3-x)=2\)。`},
  {id:"A04-5", tag:"A04", level:"難", type:"mc",
   stem:String.raw`\(\sqrt{4-2\sqrt{3}}+\sqrt{(1-\sqrt{3})^2}=\)？`,
   opts:[String.raw`\(2\sqrt{3}-2\)`,String.raw`\(0\)`,String.raw`\(2-2\sqrt{3}\)`,String.raw`\(2\)`], ans:[0],
   reasons:[String.raw`把 \(\sqrt{(1-\sqrt{3})^2}\) 直接寫成 \(1-\sqrt{3}\)`,"雙重根式大小順序寫反","兩部分都寫成負數"], key:0,
   exp:String.raw`\(\sqrt{4-2\sqrt{3}}=\sqrt{3}-1\)；\(\sqrt{(1-\sqrt{3})^2}=|1-\sqrt{3}|=\sqrt{3}-1\)。<br>相加得 \(2\sqrt{3}-2\)。`},

  // A05
  {id:"A05-3", tag:"A05", level:"易", type:"tf",
   stem:String.raw`對任意實數 \(a\)，\(|a|\ge 0\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["以為負數的絕對值是負的","不熟絕對值的定義",String.raw`以為 \(a=0\) 時不成立`], key:0,
   exp:String.raw`絕對值表示到原點的距離，一定 \(\ge 0\)，\(a=0\) 時等於 \(0\)。`},
  {id:"A05-4", tag:"A05", level:"中", type:"mc",
   stem:String.raw`若實數 \(x\)、\(y\) 滿足 \(|x-3|+|y+1|=0\)，則 \(xy=\)？`,
   opts:[String.raw`\(-3\)`,String.raw`\(3\)`,String.raw`\(0\)`,String.raw`\(-2\)`], ans:[0],
   reasons:[String.raw`\(y\) 的正負號抓錯`,"不知道兩個絕對值都要等於 0","乘法算錯"], key:0,
   exp:String.raw`兩個非負數相加為 \(0\)，只能 \(x-3=0\)、\(y+1=0\)。<br>\(x=3\)、\(y=-1\)，\(xy=-3\)。`},
  {id:"A05-5", tag:"A05", level:"中", type:"num",
   stem:String.raw`若實數 \(a\)、\(b\) 滿足 \(|a-2b|+(b-3)^2=0\)，則 \(a+b=\)？`, ans:"9", unitWord:"",
   reasons:["不知道平方和絕對值都要等於 0","先求出 b 後，代回時算錯",String.raw`把 \(a-2b=0\) 解成 \(a=\dfrac{b}{2}\)`], key:0,
   exp:String.raw`\(b-3=0\Rightarrow b=3\)；\(a-2b=0\Rightarrow a=6\)。所以 \(a+b=9\)。`},

  // A06
  {id:"A06-4", tag:"A06", level:"易", type:"mc",
   stem:String.raw`方程式 \(|x|=4\) 的解為？`,
   opts:[String.raw`\(x=4\) 或 \(x=-4\)`,String.raw`\(x=4\)`,String.raw`\(x=-4\)`,"無解"], ans:[0],
   reasons:["只寫出正的解","以為絕對值方程式只有一個解","不熟絕對值的意義"], key:0,
   exp:String.raw`到原點距離為 \(4\) 的點有兩個：\(x=4\) 或 \(x=-4\)。`},
  {id:"A06-5", tag:"A06", level:"中", type:"mc",
   stem:String.raw`方程式 \(|2x-1|=7\) 的解為？`,
   opts:[String.raw`\(x=4\) 或 \(x=-3\)`,String.raw`\(x=4\)`,String.raw`\(x=3\) 或 \(x=-4\)`,String.raw`\(x=\pm 7\)`], ans:[0],
   reasons:["只解出一個，漏掉負的那個","移項時正負號弄錯",String.raw`以為解就是 \(\pm 7\)`], key:0,
   exp:String.raw`\(2x-1=7\Rightarrow x=4\)；\(2x-1=-7\Rightarrow x=-3\)。`},
  {id:"A06-6", tag:"A06", level:"易", type:"tf",
   stem:String.raw`方程式 \(|x+3|=0\) 恰有一個解 \(x=-3\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["以為絕對值方程式一定有兩個解","把解算成 3","以為等於 0 就無解"], key:0,
   exp:String.raw`\(|x+3|=0\) 只有在 \(x+3=0\) 時成立，所以恰有一解 \(x=-3\)。`},
  {id:"A06-7", tag:"A06", level:"難", type:"mc",
   stem:String.raw`方程式 \(|x-1|=|x+5|\) 的解為？`,
   opts:[String.raw`\(x=-2\)`,String.raw`\(x=2\)`,String.raw`\(x=-3\)`,"無解"], ans:[0],
   reasons:["沒想到可以用「到兩點距離相等」來解","分段討論時正負號弄錯","以為兩個不同的絕對值不可能相等"], key:0,
   exp:String.raw`\(|x-1|=|x+5|\) 表示 \(x\) 到 \(1\) 和到 \(-5\) 的距離相等，所以 \(x\) 是兩點的中點：\(\dfrac{1+(-5)}{2}=-2\)。`},
  {id:"A06-8", tag:"A06", level:"難", type:"num",
   stem:String.raw`方程式 \(|x-2|+|x+1|=5\) 的所有解的和是多少？`, ans:"1", unitWord:"",
   reasons:["只找到一側的解","分段時沒有討論區間","把距離和算成距離差"], key:0,
   exp:String.raw`\(x\) 到 \(2\) 和到 \(-1\) 的距離和為 \(5\)，兩點間距離是 \(3\)，所以 \(x\) 在兩側。<br>\(x\gt 2\)：\(2x-1=5\Rightarrow x=3\)；\(x\lt -1\)：\(-2x+1=5\Rightarrow x=-2\)。和為 \(1\)。`},

  // A07
  {id:"A07-4", tag:"A07", level:"易", type:"mc",
   stem:String.raw`不等式 \(|x|\lt 3\) 的解為？`,
   opts:[String.raw`\(-3\lt x\lt 3\)`,String.raw`\(x\lt 3\)`,String.raw`\(x\lt -3\) 或 \(x\gt 3\)`,String.raw`\(0\lt x\lt 3\)`], ans:[0],
   reasons:["只取一邊","把「夾在中間」和「分在兩邊」搞反","忘了負數那一側"], key:0,
   exp:String.raw`到原點距離小於 \(3\)：\(-3\lt x\lt 3\)。`},
  {id:"A07-5", tag:"A07", level:"中", type:"mc",
   stem:String.raw`不等式 \(|3-x|\le 4\) 的解為？`,
   opts:[String.raw`\(-1\le x\le 7\)`,String.raw`\(-7\le x\le 1\)`,String.raw`\(x\le 7\)`,String.raw`\(1\le x\le 7\)`], ans:[0],
   reasons:[String.raw`把 \(3-x\) 的負號處理錯，中心放到 \(-3\)`,"只取一邊","移項算錯"], key:0,
   exp:String.raw`\(|3-x|=|x-3|\le 4\Rightarrow -4\le x-3\le 4\Rightarrow -1\le x\le 7\)。`},
  {id:"A07-6", tag:"A07", level:"中", type:"num",
   stem:String.raw`滿足 \(|2x+1|\le 5\) 的整數 \(x\) 共有幾個？`, ans:"6", unitWord:"個",
   reasons:["端點沒有算進去","同除以 2 時沒有每一邊都除","移項時正負號弄錯"], key:0,
   exp:String.raw`\(-5\le 2x+1\le 5\Rightarrow -3\le x\le 2\)，整數有 \(-3,-2,-1,0,1,2\)，共 \(6\) 個。`},
  {id:"A07-7", tag:"A07", level:"難", type:"mc",
   stem:String.raw`若不等式 \(|x-a|\lt 3\) 的解為 \(-1\lt x\lt b\)，則 \(a+b=\)？`,
   opts:[String.raw`\(7\)`,String.raw`\(5\)`,String.raw`\(8\)`,String.raw`\(3\)`], ans:[0],
   reasons:[String.raw`以為 \(a\) 就是左端點 \(-1\)`,"中心和半徑的關係搞錯","算出 a 後代錯"], key:0,
   exp:String.raw`\(|x-a|\lt 3\Rightarrow a-3\lt x\lt a+3\)。<br>\(a-3=-1\Rightarrow a=2\)，\(b=a+3=5\)，所以 \(a+b=7\)。`},
  {id:"A07-8", tag:"A07", level:"難", type:"num",
   stem:String.raw`若不等式 \(|2x-a|\le b\) 的解為 \(-1\le x\le 4\)，則 \(a+b=\)？`, ans:"8", unitWord:"",
   reasons:[String.raw`忘了 \(2x\) 的範圍要先乘 \(2\)`,"把中心和半徑弄反","聯立時算錯"], key:0,
   exp:String.raw`\(-1\le x\le 4\Rightarrow -2\le 2x\le 8\)。<br>\(|2x-a|\le b\) 表示 \(2x\) 以 \(a\) 為中心、半徑 \(b\)：\(a=\dfrac{-2+8}{2}=3\)、\(b=5\)，所以 \(a+b=8\)。`},

  // A08
  {id:"A08-3", tag:"A08", level:"易", type:"mc",
   stem:String.raw`不等式 \(|x|\gt 2\) 的解為？`,
   opts:[String.raw`\(x\gt 2\) 或 \(x\lt -2\)`,String.raw`\(-2\lt x\lt 2\)`,String.raw`\(x\gt 2\)`,String.raw`\(x\gt 2\) 且 \(x\lt -2\)`], ans:[0],
   reasons:["把「分在兩邊」寫成「夾在中間」","只取了一邊","「或」誤寫成「且」"], key:0,
   exp:String.raw`到原點距離大於 \(2\)：\(x\gt 2\) 或 \(x\lt -2\)。`},
  {id:"A08-4", tag:"A08", level:"中", type:"mc",
   stem:String.raw`不等式 \(|2x-3|\ge 5\) 的解為？`,
   opts:[String.raw`\(x\ge 4\) 或 \(x\le -1\)`,String.raw`\(-1\le x\le 4\)`,String.raw`\(x\ge 4\)`,String.raw`\(x\ge 1\) 或 \(x\le -4\)`], ans:[0],
   reasons:["把「分在兩邊」寫成「夾在中間」","只取了一邊","移項時正負號弄錯"], key:0,
   exp:String.raw`\(2x-3\ge 5\Rightarrow x\ge 4\)；\(2x-3\le -5\Rightarrow x\le -1\)。`},
  {id:"A08-5", tag:"A08", level:"難", type:"num",
   stem:String.raw`同時滿足 \(|x-3|\ge 2\) 與 \(|x|\le 6\) 的整數 \(x\) 共有幾個？`, ans:"10", unitWord:"個",
   reasons:[String.raw`\(|x-3|\ge 2\) 解成「夾在中間」`,"排除時把端點 1 和 5 也扣掉","整數個數數錯"], key:1,
   exp:String.raw`\(|x|\le 6\)：\(-6\le x\le 6\)，共 \(13\) 個整數。<br>\(|x-3|\ge 2\) 要排除 \(1\lt x\lt 5\)，也就是 \(2,3,4\)，剩 \(10\) 個。`},

  // A09
  {id:"A09-3", tag:"A09", level:"易", type:"mc",
   stem:String.raw`區間 \([-1,4)\) 表示？`,
   opts:[String.raw`\(-1\le x\lt 4\)`,String.raw`\(-1\lt x\le 4\)`,String.raw`\(-1\le x\le 4\)`,String.raw`\(-1\lt x\lt 4\)`], ans:[0],
   reasons:["中括號和小括號的意義弄反","以為兩邊都包含端點","不熟區間記號"], key:0,
   exp:String.raw`中括號包含端點、小括號不包含：\([-1,4)\) 是 \(-1\le x\lt 4\)。`},
  {id:"A09-4", tag:"A09", level:"易", type:"tf",
   stem:String.raw`區間 \((-\infty,2]\) 包含 \(2\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["中括號和小括號的意義弄反",String.raw`看到 \(\infty\) 就以為都不含端點`,"不熟區間記號"], key:0,
   exp:String.raw`\((-\infty,2]\) 表示 \(x\le 2\)，右端是中括號，包含 \(2\)。`},
  {id:"A09-5", tag:"A09", level:"中", type:"mc",
   stem:String.raw`不等式 \(|x-1|\ge 3\) 的解，用區間表示為？`,
   opts:[String.raw`\((-\infty,-2]\cup[4,\infty)\)`,String.raw`\([-2,4]\)`,String.raw`\((-\infty,-2)\cup(4,\infty)\)`,String.raw`\((-\infty,-2]\cup[4,\infty]\)`], ans:[0],
   reasons:[String.raw`\(\ge\) 包含端點卻用了小括號`,"把「分在兩邊」寫成一個區間",String.raw`\(\infty\) 用了中括號`], key:0,
   exp:String.raw`\(x-1\ge 3\) 或 \(x-1\le -3\)，即 \(x\ge 4\) 或 \(x\le -2\)。<br>區間：\((-\infty,-2]\cup[4,\infty)\)。`},

  // A10
  {id:"A10-3", tag:"A10", level:"易", type:"mc",
   stem:String.raw`某零件長度標示為 \(50\pm 0.2\) 毫米，則合格長度 \(x\) 的範圍為？`,
   opts:[String.raw`\(49.8\le x\le 50.2\)`,String.raw`\(49.98\le x\le 50.02\)`,String.raw`\(50\le x\le 50.2\)`,String.raw`\(48\le x\le 52\)`], ans:[0],
   reasons:["小數點位置算錯","只往一個方向加減誤差","把 0.2 當成 2"], key:0,
   exp:String.raw`\(50-0.2\le x\le 50+0.2\)，即 \(49.8\le x\le 50.2\)，也就是 \(|x-50|\le 0.2\)。`},
  {id:"A10-4", tag:"A10", level:"易", type:"mc",
   stem:String.raw`\(|x-20|\le 0.5\) 可以用下列哪一種方式表示？`,
   opts:[String.raw`\(20\pm 0.5\)`,String.raw`\(0.5\pm 20\)`,String.raw`\(-20\pm 0.5\)`,String.raw`\(20\pm 1\)`], ans:[0],
   reasons:["中心和誤差的位置寫反","中心的正負號弄錯","把誤差乘了 2"], key:0,
   exp:String.raw`\(|x-20|\le 0.5\) 表示 \(x\) 與 \(20\) 的差距不超過 \(0.5\)，即 \(20\pm 0.5\)。`},
  {id:"A10-5", tag:"A10", level:"中", type:"mc",
   stem:String.raw`人體正常體溫約在 \(35^{\circ}\mathrm{C}\) 到 \(38^{\circ}\mathrm{C}\) 之間，用 \(|x-a|\le b\) 表示時為？`,
   opts:[String.raw`\(|x-36.5|\le 1.5\)`,String.raw`\(|x-35|\le 3\)`,String.raw`\(|x-38|\le 3\)`,String.raw`\(|x-36.5|\le 3\)`], ans:[0],
   reasons:["把範圍的端點當成中心",String.raw`把區間長度 \(3\) 當成 \(b\)`,"中點算錯"], key:1,
   exp:String.raw`中心 \(a=\dfrac{35+38}{2}=36.5\)，半徑 \(b=\dfrac{38-35}{2}=1.5\)：\(|x-36.5|\le 1.5\)。`}
];
