/* 單元02 絕對值　題庫初稿
   格式同 unit01.js。數學式一律用 LaTeX，行內公式以 \( ... \) 包起來。 */
window.BANK_UNIT02 = [
  // A01 數線上的分點公式
  {id:"A01-1", tag:"A01", level:"中", type:"mc",
   stem:String.raw`數線上 \(A(-2)\)、\(B(8)\)，點 \(P\) 在 \(\overline{AB}\) 上且 \(\overline{AP}:\overline{PB}=2:3\)，則 \(P\) 的坐標為？`,
   opts:[String.raw`\(2\)`,String.raw`\(4\)`,String.raw`\(3\)`,String.raw`\(6\)`], ans:[0],
   reasons:[String.raw`\(m:n\) 對應的端點對調`,"直接取了中點",String.raw`分母沒有用 \(m+n\)`], key:0,
   exp:String.raw`分點公式：\(x=\dfrac{n\cdot a+m\cdot b}{m+n}=\dfrac{3\cdot(-2)+2\cdot 8}{5}=\dfrac{10}{5}=2\)。<br>（靠近 \(A\) 的比例是 \(2\)，所以 \(P\) 離 \(A\) 比較近。）`},
  {id:"A01-2", tag:"A01", level:"中", type:"mc",
   stem:String.raw`數線上 \(A(1)\)、\(B(13)\)，點 \(P\) 在 \(\overline{AB}\) 上且 \(\overline{AP}=3\overline{PB}\)，則 \(P\) 的坐標為？`,
   opts:[String.raw`\(10\)`,String.raw`\(4\)`,String.raw`\(7\)`,String.raw`\(12\)`], ans:[0],
   reasons:[String.raw`把 \(\overline{AP}=3\overline{PB}\) 寫成 \(\overline{AP}:\overline{PB}=1:3\)`,"分點公式的權重放錯端點","直接取了中點"], key:0,
   exp:String.raw`\(\overline{AP}:\overline{PB}=3:1\)，所以 \(x=\dfrac{1\cdot 1+3\cdot 13}{3+1}=\dfrac{40}{4}=10\)。`},

  // A02 絕對值的幾何意義
  {id:"A02-1", tag:"A02", level:"易", type:"tf",
   stem:String.raw`數線上 \(A(a)\) 與 \(B(-4)\) 的距離為 \(|a+4|\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:[String.raw`把 \(|a+4|\) 看成到 \(4\) 的距離`,String.raw`以為距離一定要寫成 \(|a-4|\)`,"忘了距離是兩坐標相減再取絕對值"], key:0,
   exp:String.raw`\(\overline{AB}=|a-(-4)|=|a+4|\)。`},
  {id:"A02-2", tag:"A02", level:"易", type:"mc",
   stem:String.raw`\(|x-3|\) 的幾何意義是？`,
   opts:[String.raw`數線上 \(x\) 到 \(3\) 的距離`,String.raw`數線上 \(x\) 到 \(-3\) 的距離`,String.raw`數線上 \(x\) 到原點的距離減 \(3\)`,String.raw`\(x\) 與 \(3\) 的和`], ans:[0],
   reasons:[String.raw`把 \(|x-3|\) 當成到 \(-3\) 的距離`,"以為絕對值只是「把負號拿掉」","忘了距離是兩坐標相減"], key:0,
   exp:String.raw`\(|x-a|\) 表示數線上點 \(x\) 與點 \(a\) 的距離，所以 \(|x-3|\) 是 \(x\) 到 \(3\) 的距離。`},
  {id:"A02-3", tag:"A02", level:"易", type:"tf",
   stem:String.raw`在數線上，到點 \(A(a)\) 的距離等於 \(1\) 的點恰有兩個。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["只想到右邊的那個點","以為距離方程式只有一個解",String.raw`忘了 \(|x-a|=1\) 有兩個解`], key:0,
   exp:String.raw`\(|x-a|=1\Rightarrow x=a+1\) 或 \(x=a-1\)，左右各一個，恰有兩點。`},

  // A03 絕對值的代數意義與化簡
  {id:"A03-1", tag:"A03", level:"中", type:"mc",
   stem:String.raw`已知 \(x\lt 1\)，化簡 \(|x-1|+(x-1)=\)？`,
   opts:[String.raw`\(0\)`,String.raw`\(2x-2\)`,String.raw`\(-2x+2\)`,String.raw`\(2\)`], ans:[0],
   reasons:["沒有先判斷 x − 1 的正負就直接去掉絕對值","去絕對值時只把一部分變號",String.raw`把 \(x\lt 1\) 當成 \(x-1\gt 0\)`], key:0,
   exp:String.raw`\(x\lt 1\Rightarrow x-1\lt 0\)，所以 \(|x-1|=-(x-1)\)。<br>原式 \(=-(x-1)+(x-1)=0\)。`},
  {id:"A03-2", tag:"A03", level:"中", type:"mc",
   stem:String.raw`若 \(-2\lt x\lt 3\)，化簡 \(|x+2|+|x-3|=\)？`,
   opts:[String.raw`\(5\)`,String.raw`\(2x-1\)`,String.raw`\(-2x+1\)`,String.raw`\(1\)`], ans:[0],
   reasons:["兩個絕對值都直接拿掉，沒有判斷正負",String.raw`\(x-3\) 的正負判斷錯`,"合併同類項算錯"], key:1,
   exp:String.raw`\(x+2\gt 0\)、\(x-3\lt 0\)，所以原式 \(=(x+2)+(3-x)=5\)。<br>幾何意義：\(x\) 在 \(-2\) 與 \(3\) 之間時，到兩點的距離和就是兩點間的距離 \(5\)。`},

  // A04 √(a²) = |a|
  {id:"A04-1", tag:"A04", level:"易", type:"tf",
   stem:String.raw`\(\sqrt{(\sqrt{3}-\sqrt{5})^2}=\sqrt{3}-\sqrt{5}\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:[String.raw`忘了 \(\sqrt{a^2}=|a|\)`,String.raw`沒有先判斷 \(\sqrt{3}-\sqrt{5}\) 是負數`,"以為根號和平方可以直接抵消"], key:0,
   exp:String.raw`\(\sqrt{3}\lt \sqrt{5}\)，所以 \(\sqrt{3}-\sqrt{5}\lt 0\)。<br>\(\sqrt{(\sqrt{3}-\sqrt{5})^2}=|\sqrt{3}-\sqrt{5}|=\sqrt{5}-\sqrt{3}\)。`},
  {id:"A04-2", tag:"A04", level:"中", type:"mc",
   stem:String.raw`若 \(x\lt 0\)，則 \(\sqrt{x^2}+|x|=\)？`,
   opts:[String.raw`\(-2x\)`,String.raw`\(2x\)`,String.raw`\(0\)`,String.raw`\(x^2\)`], ans:[0],
   reasons:[String.raw`以為 \(\sqrt{x^2}=x\)`,String.raw`忘了 \(x\lt 0\) 時 \(|x|=-x\)`,"以為兩項會互相抵消"], key:0,
   exp:String.raw`\(\sqrt{x^2}=|x|\)，而 \(x\lt 0\) 時 \(|x|=-x\)。<br>原式 \(=-x+(-x)=-2x\)（是正數）。`},

  // A05 絕對值的非負性
  {id:"A05-1", tag:"A05", level:"易", type:"tf",
   stem:String.raw`若 \(a\)、\(b\) 為實數，且 \(|a-1|+|b+2|=0\)，則 \(a=1\)、\(b=-2\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["不知道絕對值一定大於或等於 0","以為兩個絕對值可以一正一負互相抵消","解出來的正負號弄錯"], key:1,
   exp:String.raw`\(|a-1|\ge 0\)、\(|b+2|\ge 0\)，兩個非負數相加等於 \(0\)，只能兩個都是 \(0\)。<br>所以 \(a=1\)、\(b=-2\)。`},
  {id:"A05-2", tag:"A05", level:"中", type:"mc",
   stem:String.raw`若實數 \(x\)、\(y\) 滿足 \(|x-2|+(y+3)^2=0\)，則 \(x+y=\)？`,
   opts:[String.raw`\(-1\)`,String.raw`\(5\)`,String.raw`\(1\)`,String.raw`\(-5\)`], ans:[0],
   reasons:["忘了平方和絕對值都大於或等於 0","移項時正負號弄錯","以為有無限多組解"], key:1,
   exp:String.raw`兩項都 \(\ge 0\) 且和為 \(0\)，所以 \(x-2=0\)、\(y+3=0\)。<br>\(x=2\)、\(y=-3\)，\(x+y=-1\)。`},

  // A06 含絕對值的一次方程式
  {id:"A06-1", tag:"A06", level:"易", type:"mc",
   stem:String.raw`方程式 \(|x-3|=5\) 的解為？`,
   opts:[String.raw`\(x=8\) 或 \(x=-2\)`,String.raw`\(x=8\)`,String.raw`\(x=-8\) 或 \(x=2\)`,String.raw`\(x=\pm 5\)`], ans:[0],
   reasons:["只解出一個，漏掉負的那個",String.raw`把 \(x-3=-5\) 解錯`,String.raw`以為解就是 \(\pm 5\)`], key:0,
   exp:String.raw`\(|x-3|=5\Rightarrow x-3=5\) 或 \(x-3=-5\)，得 \(x=8\) 或 \(x=-2\)。<br>幾何意義：到 \(3\) 的距離為 \(5\) 的點。`},
  {id:"A06-2", tag:"A06", level:"中", type:"tf",
   stem:String.raw`方程式 \(|2x+1|=-3\) 的解為 \(x=1\) 或 \(x=-2\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:["沒注意到絕對值不可能等於負數",String.raw`直接把 \(-3\) 拆成 \(\pm 3\) 來解`,"以為無解就是 x = 0"], key:0,
   exp:String.raw`絕對值一定 \(\ge 0\)，不可能等於 \(-3\)，所以方程式無解。`},
  {id:"A06-3", tag:"A06", level:"中", type:"num",
   stem:String.raw`方程式 \(|x-5|=3\) 的所有解的和是多少？`, ans:"10", unitWord:"",
   reasons:["只解出一個解",String.raw`把 \(x-5=-3\) 解錯`,String.raw`把 \(3\) 當成解`], key:0,
   exp:String.raw`\(x-5=3\) 或 \(x-5=-3\)，得 \(x=8\) 或 \(x=2\)，和為 \(10\)。<br>（兩解對稱於 \(5\)，所以和一定是 \(2\times 5\)。）`},

  // A07 |x − a| ≤ k（夾在中間）
  {id:"A07-1", tag:"A07", level:"易", type:"mc",
   stem:String.raw`不等式 \(|x+2|\le 3\) 的解為？`,
   opts:[String.raw`\(-5\le x\le 1\)`,String.raw`\(-1\le x\le 5\)`,String.raw`\(x\le 1\)`,String.raw`\(x\le -5\) 或 \(x\ge 1\)`], ans:[0],
   reasons:[String.raw`把 \(|x+2|\) 看成到 \(2\) 的距離，中心放錯`,"只取一邊的不等式","把「夾在中間」和「分在兩邊」搞反"], key:0,
   exp:String.raw`\(|x+2|\le 3\Rightarrow -3\le x+2\le 3\Rightarrow -5\le x\le 1\)。<br>幾何意義：到 \(-2\) 的距離不超過 \(3\)。`},
  {id:"A07-2", tag:"A07", level:"中", type:"mc",
   stem:String.raw`不等式 \(|2x-1|\lt 5\) 的解為？`,
   opts:[String.raw`\(-2\lt x\lt 3\)`,String.raw`\(-3\lt x\lt 2\)`,String.raw`\(x\lt 3\)`,String.raw`\(-2\le x\le 3\)`], ans:[0],
   reasons:["同除以 2 時沒有每一邊都除","移項時正負號弄錯",String.raw`把 \(\lt \) 和 \(\le\) 搞混`], key:1,
   exp:String.raw`\(-5\lt 2x-1\lt 5\Rightarrow -4\lt 2x\lt 6\Rightarrow -2\lt x\lt 3\)。`},
  {id:"A07-3", tag:"A07", level:"中", type:"num",
   stem:String.raw`滿足 \(|x-4|\le 3\) 的整數 \(x\) 共有幾個？`, ans:"7", unitWord:"個",
   reasons:[String.raw`端點 \(1\) 和 \(7\) 沒有算進去`,String.raw`以為個數就是 \(2\times 3=6\)`,"中心點算錯"], key:1,
   exp:String.raw`\(|x-4|\le 3\Rightarrow 1\le x\le 7\)，整數有 \(1,2,\dots,7\)，共 \(7\) 個。`},

  // A08 |x − a| ≥ k（分在兩邊）
  {id:"A08-1", tag:"A08", level:"易", type:"tf",
   stem:String.raw`化簡 \(|x-3|\ge 2\)，可得 \(x-3\ge\pm 2\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:[String.raw`不知道 \(\ge\) 要拆成「或」的兩個不等式`,"把「或」寫成「且」",String.raw`以為 \(\pm\) 可以直接放進不等式`], key:0,
   exp:String.raw`\(|x-3|\ge 2\Rightarrow x-3\ge 2\) 或 \(x-3\le -2\)，即 \(x\ge 5\) 或 \(x\le 1\)。`},
  {id:"A08-2", tag:"A08", level:"中", type:"mc",
   stem:String.raw`不等式 \(|x-1|\gt 4\) 的解為？`,
   opts:[String.raw`\(x\gt 5\) 或 \(x\lt -3\)`,String.raw`\(-3\lt x\lt 5\)`,String.raw`\(x\gt 5\)`,String.raw`\(x\gt 5\) 且 \(x\lt -3\)`], ans:[0],
   reasons:["把「分在兩邊」寫成「夾在中間」","「或」誤寫成「且」","只取了一邊"], key:0,
   exp:String.raw`到 \(1\) 的距離大於 \(4\)：\(x-1\gt 4\) 或 \(x-1\lt -4\)，即 \(x\gt 5\) 或 \(x\lt -3\)。`},

  // A09 區間記號
  {id:"A09-1", tag:"A09", level:"易", type:"tf",
   stem:String.raw`\(-2\lt x\le 5\) 可記作 \((-2,5]\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["小括號和中括號的意義搞反","以為端點不能一邊包含、一邊不包含","不熟區間記號"], key:0,
   exp:String.raw`不含端點用小括號、含端點用中括號：\(-2\) 不含、\(5\) 含，記作 \((-2,5]\)。`},
  {id:"A09-2", tag:"A09", level:"易", type:"mc",
   stem:String.raw`\(x\ge 3\) 用區間表示為？`,
   opts:[String.raw`\([3,\infty)\)`,String.raw`\((3,\infty)\)`,String.raw`\([3,\infty]\)`,String.raw`\((-\infty,3]\)`], ans:[0],
   reasons:[String.raw`\(\infty\) 用了中括號`,"包含端點卻用了小括號","方向寫反"], key:0,
   exp:String.raw`含 \(3\) 用中括號；\(\infty\) 不是一個數，一定用小括號：\([3,\infty)\)。`},

  // A10 誤差範圍的表示
  {id:"A10-1", tag:"A10", level:"易", type:"mc",
   stem:String.raw`食品標示「請保存於 \(18\pm 2^{\circ}\mathrm{C}\)」，保存溫度 \(x\) 的範圍可表示為？`,
   opts:[String.raw`\(|x-18|\le 2\)`,String.raw`\(|x+18|\le 2\)`,String.raw`\(|x-2|\le 18\)`,String.raw`\(|x-18|\ge 2\)`], ans:[0],
   reasons:["中心和誤差的位置寫反",String.raw`把 \(x-18\) 寫成 \(x+18\)`,"不等號方向弄反"], key:0,
   exp:String.raw`\(18\pm 2\) 表示與 \(18\) 的差距不超過 \(2\)：\(|x-18|\le 2\)，即 \(16\le x\le 20\)。`},
  {id:"A10-2", tag:"A10", level:"中", type:"mc",
   stem:String.raw`不等式 \(|x-a|\le b\) 的解為 \(3\le x\le 11\)，則 \(a+b=\)？`,
   opts:[String.raw`\(11\)`,String.raw`\(15\)`,String.raw`\(7\)`,String.raw`\(14\)`], ans:[0],
   reasons:[String.raw`把區間長度 \(8\) 當成 \(b\)`,"中點算錯",String.raw`把 \(a\)、\(b\) 弄反`], key:0,
   exp:String.raw`中心 \(a=\dfrac{3+11}{2}=7\)，半徑 \(b=\dfrac{11-3}{2}=4\)，所以 \(a+b=11\)。`}
];
