/* 單元01 實數　題庫初稿（34 題）
   數學式一律用 LaTeX，行內公式以 \( ... \) 包起來。
   欄位：id 題號、tag 觀念代碼、level 難度（易／中／難）、type（tf 是非 / mc 單選 / multi 多選 / num 數字填充）、
   stem 題幹、opts 選項、ans 正解（選項編號從 0 開始；num 題為數字字串）、
   reasons 答錯時追問的錯因、key 最常見錯因的編號、exp 解析。
   stuck（全班卡關比例）上線後由實際作答資料計算，這裡先留空。 */
window.BANK_UNIT01 = [
  // R01 有理數的定義與組成
  {id:"R01-1", tag:"R01", level:"易", type:"tf",
   stem:String.raw`循環小數都是有理數。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["以為無限小數都不是有理數","把循環小數和不循環的無限小數搞混","忘了循環小數可以化成分數"], key:0,
   exp:String.raw`循環小數都能化成 \(\dfrac{p}{q}\) 的形式，所以是有理數。<br>只有不循環的無限小數才是無理數。`},
  {id:"R01-2", tag:"R01", level:"中", type:"multi",
   stem:String.raw`<span class="k">多選</span>下列哪些是有理數？`,
   opts:[String.raw`\(0.\overline{12}\)`,String.raw`\(\sqrt{9}\)`,String.raw`\(\dfrac{\pi}{2}\)`,String.raw`\(-3.14\)`,String.raw`\(\sqrt{2}+1\)`], ans:[0,1,3],
   reasons:["以為有根號的數一定是無理數","以為循環小數不是有理數",String.raw`把 \(\dfrac{\pi}{2}\) 當成分數`], key:0,
   exp:String.raw`\(0.\overline{12}=\dfrac{12}{99}\)、\(\sqrt{9}=3\)、\(-3.14=-\dfrac{314}{100}\) 都是有理數。<br>\(\pi\) 是無理數，\(\dfrac{\pi}{2}\) 也是無理數；\(\sqrt{2}+1\) 是無理數。`},

  // R02 循環小數化為分數
  {id:"R02-1", tag:"R02", level:"易", type:"mc",
   stem:String.raw`\(0.\overline{36}=\)？`,
   opts:[String.raw`\(\dfrac{4}{11}\)`,String.raw`\(\dfrac{9}{25}\)`,String.raw`\(\dfrac{2}{5}\)`,String.raw`\(\dfrac{4}{111}\)`], ans:[0],
   reasons:[String.raw`當成有限小數 \(0.36\) 來化`,String.raw`分母寫成 \(90\)`,String.raw`分母的 \(9\) 寫錯個數`], key:0,
   exp:String.raw`設 \(x=0.\overline{36}\)，則 \(100x=36.\overline{36}\)。<br>相減得 \(99x=36\)，所以 \(x=\dfrac{36}{99}=\dfrac{4}{11}\)。`},
  {id:"R02-2", tag:"R02", level:"中", type:"mc",
   stem:String.raw`\(1.2\overline{3}=\)？`,
   opts:[String.raw`\(\dfrac{37}{30}\)`,String.raw`\(\dfrac{41}{33}\)`,String.raw`\(\dfrac{37}{33}\)`,String.raw`\(\dfrac{123}{100}\)`], ans:[0],
   reasons:[String.raw`分母應該用 \(90\)，寫成了 \(99\)`,String.raw`沒有先把不循環的 \(2\) 處理掉`,String.raw`當成有限小數 \(1.23\)`], key:0,
   exp:String.raw`設 \(x=1.2\overline{3}\)，則 \(100x=123.\overline{3}\)、\(10x=12.\overline{3}\)。<br>相減得 \(90x=111\)，所以 \(x=\dfrac{111}{90}=\dfrac{37}{30}\)。`},
  {id:"R02-3", tag:"R02", level:"中", type:"tf",
   stem:String.raw`\(0.\overline{9}=1\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:[String.raw`以為 \(0.999\cdots\) 永遠比 \(1\) 小一點點`,"不知道循環小數可以化成分數","以為無限小數不可能等於整數"], key:0,
   exp:String.raw`設 \(x=0.\overline{9}\)，則 \(10x=9.\overline{9}\)。<br>相減得 \(9x=9\)，所以 \(x=1\)。`},
  {id:"R02-4", tag:"R02", level:"中", type:"tf",
   stem:String.raw`\(0.\overline{38}+0.\overline{62}=1\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:["把循環小數當成有限小數相加","沒有先化成分數再相加","以為循環的部分會互相抵消"], key:0,
   exp:String.raw`\(0.\overline{38}+0.\overline{62}=\dfrac{38}{99}+\dfrac{62}{99}=\dfrac{100}{99}\)，比 \(1\) 大。`},

  // R03 有限小數的判別
  {id:"R03-1", tag:"R03", level:"中", type:"mc",
   stem:`下列哪一個分數可以化成有限小數？`,
   opts:[String.raw`\(\dfrac{7}{12}\)`,String.raw`\(\dfrac{9}{24}\)`,String.raw`\(\dfrac{5}{14}\)`,String.raw`\(\dfrac{11}{30}\)`], ans:[1],
   reasons:["沒有先約成最簡分數","以為分母是偶數就一定是有限小數",String.raw`忘了最簡分數的分母只能有 \(2\)、\(5\) 兩種質因數`], key:0,
   exp:String.raw`\(\dfrac{9}{24}=\dfrac{3}{8}\)，分母 \(8=2^3\) 只含質因數 \(2\)，可化成有限小數 \(0.375\)。<br>其他三個約到最簡後，分母含有 \(3\) 或 \(7\)。`},
  {id:"R03-2", tag:"R03", level:"中", type:"tf",
   stem:String.raw`\(\dfrac{21}{75}\) 可以化成有限小數。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:[String.raw`看到分母 \(75\) 含 \(3\) 就判斷不行，沒有先約分`,String.raw`把 \(25\) 的質因數算錯`,String.raw`以為有限小數的分母只能是 \(10\) 的次方`], key:0,
   exp:String.raw`\(\dfrac{21}{75}=\dfrac{7}{25}\)，分母 \(25=5^2\)，所以可化成有限小數 \(0.28\)。<br>判斷前一定要先約成最簡分數。`},

  // R04 有理數的稠密性
  {id:"R04-1", tag:"R04", level:"易", type:"tf",
   stem:String.raw`在 \(0\) 和 \(0.001\) 之間有無限多個有理數。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["以為兩個很接近的數之間沒有其他有理數","只把有理數想成整數或簡單分數","不知道有理數的稠密性"], key:2,
   exp:String.raw`任意兩個相異有理數之間，一定還有有理數（例如兩數的平均），這叫做有理數的稠密性。<br>一直取平均就能找到無限多個。`},
  {id:"R04-2", tag:"R04", level:"中", type:"mc",
   stem:String.raw`下列哪一個數介於 \(\dfrac{1}{4}\) 與 \(\dfrac{1}{3}\) 之間？`,
   opts:[String.raw`\(\dfrac{2}{7}\)`,String.raw`\(\dfrac{1}{5}\)`,String.raw`\(\dfrac{3}{8}\)`,String.raw`\(\dfrac{2}{5}\)`], ans:[0],
   reasons:["以為分母越大，數就越大","沒有通分或化成小數就直接比",String.raw`把 \(\dfrac{1}{4}\) 和 \(\dfrac{1}{3}\) 的大小弄反`], key:1,
   exp:String.raw`\(\dfrac{1}{4}=0.25\)、\(\dfrac{1}{3}\approx 0.333\)，而 \(\dfrac{2}{7}\approx 0.286\) 在兩者之間。<br>其他選項：\(0.2\)、\(0.375\)、\(0.4\) 都不在範圍內。`},

  // R05 無理數的判別
  {id:"R05-1", tag:"R05", level:"中", type:"multi",
   stem:String.raw`<span class="k">多選</span>下列哪些是無理數？`,
   opts:[String.raw`\(\sqrt{16}\)`,String.raw`\(\sqrt{12}\)`,String.raw`\(3.\overline{14}\)`,String.raw`\(\pi-3\)`,String.raw`\(\sqrt{\dfrac{4}{9}}\)`], ans:[1,3],
   reasons:[String.raw`把 \(\sqrt{16}\) 這種完全平方數也當成無理數`,String.raw`以為 \(\pi-3\) 減掉整數後變成有理數`,"以為根號裡是分數就一定是無理數"], key:0,
   exp:String.raw`\(\sqrt{16}=4\)、\(3.\overline{14}\) 是循環小數、\(\sqrt{\dfrac{4}{9}}=\dfrac{2}{3}\)，都是有理數。<br>\(\sqrt{12}=2\sqrt{3}\) 與 \(\pi-3\) 是無理數。`},

  // R06 有理數與無理數的運算
  {id:"R06-1", tag:"R06", level:"易", type:"tf",
   stem:String.raw`若 \(a\) 為有理數、\(b\) 為無理數，則 \(ab\) 必為無理數。`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:[String.raw`忽略 \(a=0\) 的情況`,"以為無理數乘任何數都是無理數","把加法的性質套到乘法"], key:0,
   exp:String.raw`反例：取 \(a=0\)，則 \(ab=0\) 是有理數。<br>（當 \(a\neq 0\) 時，\(ab\) 才一定是無理數。）`},
  {id:"R06-2", tag:"R06", level:"易", type:"tf",
   stem:`兩個無理數的和必為無理數。`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:["沒想到兩個無理數可以互相抵消","以為無理數加無理數一定還是無理數",String.raw`只用 \(\sqrt{2}+\sqrt{3}\) 這種例子判斷`], key:0,
   exp:String.raw`反例：\(\sqrt{2}+(-\sqrt{2})=0\)，結果是有理數。`},
  {id:"R06-3", tag:"R06", level:"中", type:"tf",
   stem:String.raw`若 \(a\) 為有理數、\(b\) 為無理數，則 \(a+b\) 必為無理數。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["以為可能剛好抵消成有理數",String.raw`把乘法的反例 \(a=0\) 套到加法`,"不會用反證法判斷"], key:1,
   exp:String.raw`假設 \(a+b=c\) 是有理數，則 \(b=c-a\) 是兩個有理數相減，也是有理數，與 \(b\) 是無理數矛盾。<br>所以 \(a+b\) 必為無理數。`},

  // R07 a + b√2 = 0（係數比較）
  {id:"R07-1", tag:"R07", level:"中", type:"mc",
   stem:String.raw`若 \(a\)、\(b\) 為有理數，且 \((a-1)+(b+2)\sqrt{2}=0\)，則 \(a+b=\)？`,
   opts:[String.raw`\(-1\)`,String.raw`\(3\)`,String.raw`\(1\)`,String.raw`\(-3\)`], ans:[0],
   reasons:[String.raw`忘了 \(a\)、\(b\) 是有理數才能比較係數`,"移項時正負號弄錯",String.raw`把 \(\sqrt{2}\) 的係數和有理數部分搞混`], key:1,
   exp:String.raw`因為 \(a-1\)、\(b+2\) 都是有理數，所以 \(a-1=0\) 且 \(b+2=0\)。<br>得 \(a=1\)、\(b=-2\)，\(a+b=-1\)。`},
  {id:"R07-2", tag:"R07", level:"難", type:"mc",
   stem:String.raw`若 \(a\)、\(b\) 為有理數，且 \((2+\sqrt{2})a+(1-\sqrt{2})b=5+\sqrt{2}\)，則數對 \((a,b)=\)？`,
   opts:[String.raw`\((2,1)\)`,String.raw`\((1,3)\)`,String.raw`\((3,-1)\)`,String.raw`\((1,2)\)`], ans:[0],
   reasons:[String.raw`展開後沒有把有理數部分和 \(\sqrt{2}\) 部分分開整理`,String.raw`\(\sqrt{2}\) 部分的係數正負號弄錯`,"聯立方程式解錯"], key:0,
   exp:String.raw`整理成 \((2a+b)+(a-b)\sqrt{2}=5+\sqrt{2}\)。<br>比較係數：\(2a+b=5\)、\(a-b=1\)，解得 \(a=2\)、\(b=1\)。`},

  // R08 根號的近似與估計
  {id:"R08-1", tag:"R08", level:"易", type:"mc",
   stem:String.raw`\(\sqrt{7}\) 介於下列哪兩個數之間？`,
   opts:[String.raw`\(2.5\) 與 \(2.6\)`,String.raw`\(2.6\) 與 \(2.7\)`,String.raw`\(2.7\) 與 \(2.8\)`,String.raw`\(3.4\) 與 \(3.5\)`], ans:[1],
   reasons:["平方後比大小算錯",String.raw`把 \(\sqrt{7}\) 和 \(7\div 2\) 搞混`,"沒有用平方來夾"], key:0,
   exp:String.raw`\(2.6^2=6.76\)、\(2.7^2=7.29\)，而 \(6.76\lt 7\lt 7.29\)。<br>所以 \(2.6\lt \sqrt{7}\lt 2.7\)。`},

  // R09 實數的運算性質與次序
  {id:"R09-1", tag:"R09", level:"易", type:"tf",
   stem:String.raw`若 \(a\lt b\)，則 \(-2a\lt -2b\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:["乘以負數時忘了不等號要變向","以為不等式兩邊同乘任何數都不變號",String.raw`把 \(a\)、\(b\) 的大小弄反`], key:0,
   exp:String.raw`不等式兩邊同乘負數，不等號要變向：\(a\lt b\Rightarrow -2a\gt -2b\)。`},
  {id:"R09-2", tag:"R09", level:"中", type:"tf",
   stem:String.raw`若 \(a\lt b\)，則 \(\dfrac{2a+b}{3}\gt \dfrac{a+2b}{3}\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:["沒有相減比較就直接判斷",String.raw`以為 \(a\) 的係數比較大，結果就比較大`,"相減時正負號弄錯"], key:1,
   exp:String.raw`相減：\(\dfrac{2a+b}{3}-\dfrac{a+2b}{3}=\dfrac{a-b}{3}\lt 0\)。<br>所以 \(\dfrac{2a+b}{3}\lt \dfrac{a+2b}{3}\)。`},

  // R10 乘法公式
  {id:"R10-1", tag:"R10", level:"易", type:"mc",
   stem:String.raw`\((2x-3y)^2=\)？`,
   opts:[String.raw`\(4x^2-12xy+9y^2\)`,String.raw`\(4x^2-9y^2\)`,String.raw`\(4x^2+9y^2\)`,String.raw`\(4x^2-6xy+9y^2\)`], ans:[0],
   reasons:[String.raw`以為 \((a-b)^2=a^2-b^2\)`,"中間項忘了乘 2","正負號弄錯"], key:0,
   exp:String.raw`\((a-b)^2=a^2-2ab+b^2\)。<br>\((2x-3y)^2=(2x)^2-2(2x)(3y)+(3y)^2=4x^2-12xy+9y^2\)。`},
  {id:"R10-2", tag:"R10", level:"中", type:"mc",
   stem:String.raw`若 \(a+b+c=5\)，\(ab+bc+ca=6\)，則 \(a^2+b^2+c^2=\)？`,
   opts:[String.raw`\(13\)`,String.raw`\(19\)`,String.raw`\(37\)`,String.raw`\(25\)`], ans:[0],
   reasons:[String.raw`忘了 \((a+b+c)^2\) 有交叉項`,"交叉項沒有乘 2","移項時把減號寫成加號"], key:1,
   exp:String.raw`\((a+b+c)^2=a^2+b^2+c^2+2(ab+bc+ca)\)。<br>\(25=a^2+b^2+c^2+12\)，所以 \(a^2+b^2+c^2=13\)。`},

  // R11 和差立方、立方和與立方差
  {id:"R11-1", tag:"R11", level:"易", type:"mc",
   stem:String.raw`\((x-2)(x^2+2x+4)=\)？`,
   opts:[String.raw`\(x^3-8\)`,String.raw`\(x^3+8\)`,String.raw`\(x^3-6x^2+12x-8\)`,String.raw`\(x^3-4\)`], ans:[0],
   reasons:["立方差與立方和的符號記反","把立方差公式和差的立方公式搞混","展開時漏乘"], key:0,
   exp:String.raw`立方差公式：\((a-b)(a^2+ab+b^2)=a^3-b^3\)。<br>這裡 \(a=x\)、\(b=2\)，結果是 \(x^3-8\)。`},
  {id:"R11-2", tag:"R11", level:"中", type:"mc",
   stem:String.raw`\((a+2b)^3=\)？`,
   opts:[String.raw`\(a^3+6a^2b+12ab^2+8b^3\)`,String.raw`\(a^3+8b^3\)`,String.raw`\(a^3+6a^2b+6ab^2+8b^3\)`,String.raw`\(a^3+3a^2b+3ab^2+8b^3\)`], ans:[0],
   reasons:[String.raw`以為 \((a+b)^3=a^3+b^3\)`,String.raw`係數 \(3\) 沒有和 \(2b\) 的次方一起乘`,"中間項的係數算錯"], key:1,
   exp:String.raw`\((a+b)^3=a^3+3a^2b+3ab^2+b^3\)，把 \(b\) 換成 \(2b\)：<br>\(a^3+3a^2(2b)+3a(2b)^2+(2b)^3=a^3+6a^2b+12ab^2+8b^3\)。`},

  // R12 x + 1/x 型求值
  {id:"R12-1", tag:"R12", level:"中", type:"num",
   stem:String.raw`若 \(x+\dfrac{1}{x}=3\)，則 \(x^2+\dfrac{1}{x^2}=\)？`, ans:"7", unitWord:"",
   reasons:[String.raw`平方後忘了減 \(2\)`,String.raw`把 \(\left(x+\dfrac{1}{x}\right)^2\) 直接當成 \(x^2+\dfrac{1}{x^2}\)`,String.raw`把 \(3^2\) 算成 \(6\)`], key:0,
   exp:String.raw`\(x^2+\dfrac{1}{x^2}=\left(x+\dfrac{1}{x}\right)^2-2=9-2=7\)。`},
  {id:"R12-2", tag:"R12", level:"難", type:"num",
   stem:String.raw`若 \(x+\dfrac{1}{x}=3\)，則 \(x^3+\dfrac{1}{x^3}=\)？`, ans:"18", unitWord:"",
   reasons:[String.raw`少減了 \(3\left(x+\dfrac{1}{x}\right)\)`,"把立方和公式記錯",String.raw`直接把 \(3\) 立方得 \(27\)`], key:0,
   exp:String.raw`\(x^3+\dfrac{1}{x^3}=\left(x+\dfrac{1}{x}\right)^3-3\left(x+\dfrac{1}{x}\right)=27-9=18\)。`},

  // R13 根式化簡與四則運算
  {id:"R13-1", tag:"R13", level:"易", type:"mc",
   stem:String.raw`\(\sqrt{12}+\sqrt{75}-\sqrt{27}=\)？`,
   opts:[String.raw`\(4\sqrt{3}\)`,String.raw`\(\sqrt{60}\)`,String.raw`\(2\sqrt{15}\)`,String.raw`\(6\sqrt{3}\)`], ans:[0],
   reasons:[String.raw`以為 \(\sqrt{a}+\sqrt{b}=\sqrt{a+b}\)`,"根號化簡時提出來的數算錯","沒有化成同類根式就合併"], key:0,
   exp:String.raw`\(\sqrt{12}=2\sqrt{3}\)、\(\sqrt{75}=5\sqrt{3}\)、\(\sqrt{27}=3\sqrt{3}\)。<br>\(2\sqrt{3}+5\sqrt{3}-3\sqrt{3}=4\sqrt{3}\)。`},
  {id:"R13-2", tag:"R13", level:"易", type:"tf",
   stem:String.raw`\(\sqrt{9+16}=\sqrt{9}+\sqrt{16}\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:["以為根號可以對加法拆開","根號的值算錯",String.raw`把乘法的性質 \(\sqrt{ab}=\sqrt{a}\sqrt{b}\) 套到加法`], key:2,
   exp:String.raw`左邊 \(\sqrt{25}=5\)，右邊 \(3+4=7\)，不相等。<br>根號只能對乘除拆開：\(\sqrt{ab}=\sqrt{a}\sqrt{b}\)，加減不行。`},

  // R14 分母有理化
  {id:"R14-1", tag:"R14", level:"易", type:"mc",
   stem:String.raw`\(\dfrac{2}{\sqrt{5}+\sqrt{3}}=\)？`,
   opts:[String.raw`\(\sqrt{5}-\sqrt{3}\)`,String.raw`\(\sqrt{5}+\sqrt{3}\)`,String.raw`\(\dfrac{\sqrt{5}-\sqrt{3}}{4}\)`,String.raw`\(2(\sqrt{5}-\sqrt{3})\)`], ans:[0],
   reasons:["乘的共軛式符號弄反",String.raw`分母算成 \(5+3\)`,"分子沒有一起乘"], key:1,
   exp:String.raw`分子分母同乘 \(\sqrt{5}-\sqrt{3}\)：<br>\(\dfrac{2(\sqrt{5}-\sqrt{3})}{5-3}=\sqrt{5}-\sqrt{3}\)。`},
  {id:"R14-2", tag:"R14", level:"中", type:"mc",
   stem:String.raw`\(\dfrac{1}{2-\sqrt{3}}+\dfrac{1}{2+\sqrt{3}}=\)？`,
   opts:[String.raw`\(4\)`,String.raw`\(2\sqrt{3}\)`,String.raw`\(1\)`,String.raw`\(\dfrac{4}{7}\)`], ans:[0],
   reasons:[String.raw`分母算成 \(4+3=7\)`,"根號部分沒有抵消，反而相加","有理化時分子忘了一起乘"], key:0,
   exp:String.raw`\(\dfrac{1}{2-\sqrt{3}}=\dfrac{2+\sqrt{3}}{4-3}=2+\sqrt{3}\)，同理 \(\dfrac{1}{2+\sqrt{3}}=2-\sqrt{3}\)。<br>相加得 \(4\)。`},

  // R15 根式比大小
  {id:"R15-1", tag:"R15", level:"難", type:"mc",
   stem:String.raw`設 \(a=\sqrt{2}+\sqrt{11}\)，\(b=\sqrt{3}+\sqrt{10}\)，\(c=\sqrt{6}+\sqrt{7}\)，則大小關係為？`,
   opts:[String.raw`\(a\lt b\lt c\)`,String.raw`\(c\lt b\lt a\)`,String.raw`\(a=b=c\)`,String.raw`\(b\lt a\lt c\)`], ans:[0],
   reasons:[String.raw`看到根號內加起來都是 \(13\) 就以為相等`,"平方後交叉項比錯","沒有先平方再比較"], key:0,
   exp:String.raw`平方：\(a^2=13+2\sqrt{22}\)、\(b^2=13+2\sqrt{30}\)、\(c^2=13+2\sqrt{42}\)。<br>因為 \(22\lt 30\lt 42\)，且 \(a,b,c\) 都是正數，所以 \(a\lt b\lt c\)。`},

  // R16 雙重根式
  {id:"R16-1", tag:"R16", level:"中", type:"mc",
   stem:String.raw`\(\sqrt{7-2\sqrt{10}}=\)？`,
   opts:[String.raw`\(\sqrt{5}-\sqrt{2}\)`,String.raw`\(\sqrt{2}-\sqrt{5}\)`,String.raw`\(\sqrt{7}-\sqrt{10}\)`,String.raw`\(\sqrt{5}+\sqrt{2}\)`], ans:[0],
   reasons:["大小順序寫反，結果變成負數","以為可以直接把根號拆開",String.raw`找錯兩數（和為 \(7\)、積為 \(10\)）`], key:0,
   exp:String.raw`找兩數和為 \(7\)、積為 \(10\)：\(5\) 和 \(2\)。<br>\(\sqrt{7-2\sqrt{10}}=\sqrt{(\sqrt{5}-\sqrt{2})^2}=\sqrt{5}-\sqrt{2}\)（大的在前，結果才是正數）。`},
  {id:"R16-2", tag:"R16", level:"難", type:"mc",
   stem:String.raw`\(\sqrt{4+\sqrt{12}}=\)？`,
   opts:[String.raw`\(\sqrt{3}+1\)`,String.raw`\(\sqrt{3}-1\)`,String.raw`\(2+\sqrt{3}\)`,String.raw`\(1+\sqrt{2}\)`], ans:[0],
   reasons:[String.raw`沒先把 \(\sqrt{12}\) 寫成 \(2\sqrt{3}\)`,String.raw`找錯兩數（和為 \(4\)、積為 \(3\)）`,"正負號寫錯"], key:0,
   exp:String.raw`\(\sqrt{12}=2\sqrt{3}\)，所以 \(\sqrt{4+2\sqrt{3}}\)。<br>兩數和為 \(4\)、積為 \(3\)：\(3\) 和 \(1\)，結果是 \(\sqrt{3}+1\)。`},

  // R17 算幾不等式
  {id:"R17-1", tag:"R17", level:"中", type:"mc",
   stem:String.raw`若 \(a\gt 0\)、\(b\gt 0\)，且 \(ab=16\)，則 \(a+b\) 的最小值為？`,
   opts:[String.raw`\(8\)`,String.raw`\(4\)`,String.raw`\(16\)`,String.raw`\(32\)`], ans:[0],
   reasons:[String.raw`寫成 \(a+b\ge\sqrt{ab}\)，忘了乘 \(2\)`,String.raw`忘了 \(a\)、\(b\) 要是正數才能用`,String.raw`等號成立條件 \(a=b\) 沒有用上`], key:0,
   exp:String.raw`由算幾不等式：\(\dfrac{a+b}{2}\ge\sqrt{ab}=4\)，所以 \(a+b\ge 8\)。<br>當 \(a=b=4\) 時等號成立，最小值為 \(8\)。`},
  {id:"R17-2", tag:"R17", level:"難", type:"mc",
   stem:String.raw`若 \(a\gt 0\)、\(b\gt 0\)，且 \(ab=8\)，則 \(a+2b\) 的最小值為？`,
   opts:[String.raw`\(8\)`,String.raw`\(4\sqrt{2}\)`,String.raw`\(6\)`,String.raw`\(16\)`], ans:[0],
   reasons:[String.raw`把 \(a\) 和 \(2b\) 的乘積算成 \(ab=8\)`,String.raw`忘了乘 \(2\)`,"等號成立條件寫錯"], key:0,
   exp:String.raw`把 \(a\) 和 \(2b\) 看成兩個正數：\(\dfrac{a+2b}{2}\ge\sqrt{a\cdot 2b}=\sqrt{16}=4\)，所以 \(a+2b\ge 8\)。<br>當 \(a=2b\)，即 \(a=4\)、\(b=2\) 時等號成立。`},

  /* ---------- 第二批（擴充至 300 題） ---------- */
  // R01
  {id:"R01-3", tag:"R01", level:"易", type:"tf",
   stem:`所有整數都是有理數。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["以為有理數只包含分數","不知道整數可以寫成分母為 1 的分數","把有理數和小數搞混"], key:1,
   exp:String.raw`任何整數 \(n\) 都可以寫成 \(\dfrac{n}{1}\)，所以整數都是有理數。`},
  {id:"R01-4", tag:"R01", level:"易", type:"mc",
   stem:`下列何者<b>不是</b>有理數？`,
   opts:[String.raw`\(-\dfrac{7}{3}\)`,String.raw`\(0\)`,String.raw`\(\sqrt{0.25}\)`,String.raw`\(\sqrt{0.4}\)`], ans:[3],
   reasons:["以為有根號的數一定是無理數",String.raw`以為 \(0\) 不是有理數`,"沒有把小數化成分數再判斷能不能開方"], key:2,
   exp:String.raw`\(\sqrt{0.25}=0.5\) 是有理數；\(0.4=\dfrac{2}{5}\)，分子分母都不是完全平方數，\(\sqrt{0.4}\) 是無理數。`},
  {id:"R01-5", tag:"R01", level:"中", type:"multi",
   stem:String.raw`<span class="k">多選</span>下列哪些數可以寫成 \(\dfrac{p}{q}\)（\(p\)、\(q\) 為整數，\(q\neq 0\)）的形式？`,
   opts:[String.raw`\(1.\overline{2}\)`,String.raw`\(3.1415\)`,String.raw`\(\pi\)`,String.raw`\(\sqrt{1.44}\)`,String.raw`\(0.1010010001\cdots\)（1 之間的 0 逐次多一個）`], ans:[0,1,3],
   reasons:["以為有規律的無限小數就是循環小數",String.raw`以為 \(\pi\) 就是 \(3.1415\)`,"以為有根號的數一定是無理數"], key:0,
   exp:String.raw`\(1.\overline{2}=\dfrac{11}{9}\)、\(3.1415=\dfrac{31415}{10000}\)、\(\sqrt{1.44}=1.2\) 都是有理數。<br>\(\pi\) 是無理數；最後一個雖然有規律，但不循環，也是無理數。`},

  // R02
  {id:"R02-5", tag:"R02", level:"易", type:"mc",
   stem:String.raw`\(0.\overline{7}=\)？`,
   opts:[String.raw`\(\dfrac{7}{9}\)`,String.raw`\(\dfrac{7}{10}\)`,String.raw`\(\dfrac{7}{99}\)`,String.raw`\(\dfrac{77}{100}\)`], ans:[0],
   reasons:[String.raw`當成有限小數 \(0.7\) 來化`,String.raw`循環節只有 1 位，分母卻寫成 \(99\)`,"不熟循環小數化分數的方法"], key:0,
   exp:String.raw`設 \(x=0.\overline{7}\)，則 \(10x=7.\overline{7}\)，相減得 \(9x=7\)，\(x=\dfrac{7}{9}\)。`},
  {id:"R02-6", tag:"R02", level:"中", type:"num",
   stem:String.raw`將 \(0.\overline{27}\) 化成最簡分數 \(\dfrac{a}{b}\)，則 \(a+b=\)？`, ans:"14", unitWord:"",
   reasons:[String.raw`沒有約分，算成 \(27+99\)`,String.raw`分母寫成 \(100\)`,"約分時算錯"], key:0,
   exp:String.raw`\(0.\overline{27}=\dfrac{27}{99}=\dfrac{3}{11}\)，所以 \(a+b=3+11=14\)。`},
  {id:"R02-7", tag:"R02", level:"難", type:"num",
   stem:String.raw`已知 \(\dfrac{1}{7}=0.\overline{142857}\)，則小數點後第 \(100\) 位數字是多少？`, ans:"8", unitWord:"",
   reasons:["用除法的商而不是餘數來找位置","餘數對應到循環節的位置數錯","循環節的位數算錯"], key:0,
   exp:String.raw`循環節 \(142857\) 共 \(6\) 位，\(100=6\times 16+4\)，餘數 \(4\)。<br>所以第 \(100\) 位是循環節的第 \(4\) 個數字：\(8\)。`},
  {id:"R02-8", tag:"R02", level:"易", type:"tf",
   stem:String.raw`\(0.\overline{5}\gt 0.5\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:[String.raw`以為 \(0.\overline{5}\) 和 \(0.5\) 一樣`,"不會比較循環小數的大小",String.raw`以為 \(0.\overline{5}\) 比較小`], key:0,
   exp:String.raw`\(0.\overline{5}=0.555\cdots=\dfrac{5}{9}\)，比 \(0.5=\dfrac{1}{2}\) 大。`},

  // R03
  {id:"R03-3", tag:"R03", level:"易", type:"tf",
   stem:String.raw`\(\dfrac{3}{40}\) 可以化成有限小數。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:[String.raw`把 \(40\) 的質因數分解錯`,String.raw`以為分母一定要是 \(10\) 的次方`,"不熟有限小數的判別方法"], key:0,
   exp:String.raw`\(40=2^3\times 5\)，只含質因數 \(2\) 和 \(5\)，所以 \(\dfrac{3}{40}=0.075\) 是有限小數。`},
  {id:"R03-4", tag:"R03", level:"中", type:"mc",
   stem:`下列哪一個分數化成小數後是<b>循環小數</b>？`,
   opts:[String.raw`\(\dfrac{7}{8}\)`,String.raw`\(\dfrac{9}{12}\)`,String.raw`\(\dfrac{7}{15}\)`,String.raw`\(\dfrac{13}{50}\)`], ans:[2],
   reasons:["沒有先約分就判斷",String.raw`以為分母是 \(5\) 的倍數就一定是有限小數`,"分母的質因數分解錯"], key:1,
   exp:String.raw`\(\dfrac{9}{12}=\dfrac{3}{4}\) 是有限小數；\(\dfrac{7}{15}\) 已是最簡分數，分母 \(15=3\times 5\) 含 \(3\)，所以是循環小數。`},
  {id:"R03-5", tag:"R03", level:"難", type:"num",
   stem:String.raw`若 \(n\) 為正整數且 \(1\le n\le 20\)，使 \(\dfrac{n}{60}\) 可化成有限小數的 \(n\) 共有幾個？`, ans:"6", unitWord:"個",
   reasons:[String.raw`沒想到 \(n\) 要能約掉分母的 \(3\)`,"漏算或多算了某些倍數",String.raw`以為分母 \(60\) 含 \(3\)，所以全部都不行`], key:0,
   exp:String.raw`\(60=2^2\times 3\times 5\)，要約掉質因數 \(3\)，\(n\) 必須是 \(3\) 的倍數。<br>\(n=3,6,9,12,15,18\)，共 \(6\) 個。`},

  // R04
  {id:"R04-3", tag:"R04", level:"易", type:"tf",
   stem:`任意兩個相異的有理數之間，恰好有一個有理數。`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:["以為只有兩數的平均數一個","不知道有理數的稠密性","把「至少一個」看成「恰好一個」"], key:1,
   exp:String.raw`兩個相異有理數之間有<b>無限多個</b>有理數（可以一直取平均數），不是只有一個。`},
  {id:"R04-4", tag:"R04", level:"中", type:"mc",
   stem:String.raw`介於 \(\dfrac{1}{3}\) 與 \(\dfrac{1}{2}\) 之間（不含兩端），且分母為 \(30\) 的分數有幾個？`,
   opts:[String.raw`\(4\)`,String.raw`\(5\)`,String.raw`\(6\)`,String.raw`\(3\)`], ans:[0],
   reasons:["把兩個端點也算進去","通分時算錯","數個數時算錯"], key:0,
   exp:String.raw`\(\dfrac{1}{3}=\dfrac{10}{30}\)、\(\dfrac{1}{2}=\dfrac{15}{30}\)，之間有 \(\dfrac{11}{30},\dfrac{12}{30},\dfrac{13}{30},\dfrac{14}{30}\)，共 \(4\) 個。`},
  {id:"R04-5", tag:"R04", level:"中", type:"tf",
   stem:`任意兩個相異的實數之間，一定有有理數。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["以為稠密性只適用於兩個有理數之間","以為兩個無理數之間可能沒有有理數","不熟實數在數線上的性質"], key:0,
   exp:String.raw`有理數在數線上是稠密的：不論兩個實數多接近，中間都找得到有理數（例如取適當位數的有限小數）。`},

  // R05
  {id:"R05-2", tag:"R05", level:"易", type:"tf",
   stem:String.raw`\(\sqrt{0.09}\) 是無理數。`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:["以為有根號的數一定是無理數",String.raw`把 \(\sqrt{0.09}\) 算錯`,"沒有先化成分數判斷"], key:0,
   exp:String.raw`\(\sqrt{0.09}=0.3\)，是有理數。`},
  {id:"R05-3", tag:"R05", level:"中", type:"multi",
   stem:String.raw`<span class="k">多選</span>下列哪些是無理數？`,
   opts:[String.raw`\(\sqrt{8}-\sqrt{2}\)`,String.raw`\(\sqrt{18}\div\sqrt{2}\)`,String.raw`\((\sqrt{3})^2\)`,String.raw`\(\sqrt{2}+\sqrt{3}\)`,String.raw`\(\dfrac{\sqrt{12}}{\sqrt{3}}\)`], ans:[0,3],
   reasons:["沒有先化簡就判斷","以為含根號的運算結果一定是無理數","以為根號相減一定會變成有理數"], key:0,
   exp:String.raw`\(\sqrt{8}-\sqrt{2}=2\sqrt{2}-\sqrt{2}=\sqrt{2}\)，無理數；\(\sqrt{18}\div\sqrt{2}=3\)、\((\sqrt{3})^2=3\)、\(\dfrac{\sqrt{12}}{\sqrt{3}}=2\) 都是有理數；\(\sqrt{2}+\sqrt{3}\) 是無理數。`},
  {id:"R05-4", tag:"R05", level:"難", type:"mc",
   stem:String.raw`若 \(n\) 為正整數，且 \(\sqrt{n}\) 介於 \(2\) 和 \(6\) 之間（不含兩端）並且是無理數，則這樣的 \(n\) 有幾個？`,
   opts:[String.raw`\(28\)`,String.raw`\(31\)`,String.raw`\(32\)`,String.raw`\(27\)`], ans:[0],
   reasons:[String.raw`忘了扣掉 \(9\)、\(16\)、\(25\) 這些完全平方數`,String.raw`把端點 \(4\) 或 \(36\) 算進去`,"計算個數時算錯"], key:0,
   exp:String.raw`\(2\lt\sqrt{n}\lt 6\Rightarrow 4\lt n\lt 36\)，\(n=5,6,\dots,35\) 共 \(31\) 個。<br>其中 \(9,16,25\) 開根號是整數，要扣掉，剩 \(28\) 個。`},

  // R06
  {id:"R06-4", tag:"R06", level:"易", type:"tf",
   stem:`兩個有理數的和一定是有理數。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["不熟有理數的運算封閉性","以為相加可能變成無理數","把有理數和整數搞混"], key:0,
   exp:String.raw`\(\dfrac{a}{b}+\dfrac{c}{d}=\dfrac{ad+bc}{bd}\)，結果仍是分數形式，所以是有理數。`},
  {id:"R06-5", tag:"R06", level:"中", type:"tf",
   stem:`兩個無理數的乘積必為無理數。`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:["沒想到無理數相乘可能變成整數",String.raw`只用 \(\sqrt{2}\times\sqrt{3}\) 這種例子判斷`,"以為無理數的運算結果一定是無理數"], key:0,
   exp:String.raw`反例：\(\sqrt{2}\times\sqrt{2}=2\)，結果是有理數。`},
  {id:"R06-6", tag:"R06", level:"中", type:"multi",
   stem:String.raw`<span class="k">多選</span>設 \(a\) 為有理數、\(b\) 為無理數，下列哪些<b>必為</b>無理數？`,
   opts:[String.raw`\(a+b\)`,String.raw`\(ab\)`,String.raw`\(b^2\)`,String.raw`\(a-b\)`,String.raw`\(2b\)`], ans:[0,3,4],
   reasons:[String.raw`忽略 \(a=0\) 的情況`,"以為無理數平方還是無理數","以為乘上有理數就可能變成有理數"], key:0,
   exp:String.raw`\(a\pm b\) 一定是無理數；\(2b\) 是非零有理數乘無理數，也是無理數。<br>\(ab\) 在 \(a=0\) 時為 \(0\)；\(b^2\) 在 \(b=\sqrt{2}\) 時為 \(2\)，都不一定。`},

  // R07
  {id:"R07-3", tag:"R07", level:"中", type:"mc",
   stem:String.raw`若 \(a\)、\(b\) 為有理數，且 \(a+b\sqrt{3}=4-2\sqrt{3}\)，則 \(a-b=\)？`,
   opts:[String.raw`\(6\)`,String.raw`\(2\)`,String.raw`\(-6\)`,String.raw`\(4\)`], ans:[0],
   reasons:[String.raw`\(b\) 的正負號抓錯`,String.raw`把 \(a\)、\(b\) 對調`,"忘了要用有理數比較係數"], key:0,
   exp:String.raw`比較係數：\(a=4\)、\(b=-2\)，所以 \(a-b=4-(-2)=6\)。`},
  {id:"R07-4", tag:"R07", level:"難", type:"mc",
   stem:String.raw`若 \(a\)、\(b\) 為有理數，且 \((a+\sqrt{2})(1+b\sqrt{2})=5+3\sqrt{2}\)，則下列何者可能是數對 \((a,b)\)？`,
   opts:[String.raw`\((1,2)\)`,String.raw`\((2,1)\)`,String.raw`\((3,1)\)`,String.raw`\((1,3)\)`], ans:[0],
   reasons:[String.raw`展開時漏了 \(\sqrt{2}\times b\sqrt{2}=2b\) 這一項`,String.raw`有理數部分和 \(\sqrt{2}\) 部分整理錯`,"解聯立方程式時算錯"], key:0,
   exp:String.raw`展開：\((a+2b)+(ab+1)\sqrt{2}=5+3\sqrt{2}\)，得 \(a+2b=5\)、\(ab=2\)。<br>代入 \(a=5-2b\)：\(2b^2-5b+2=0\)，\(b=2\) 或 \(\dfrac{1}{2}\)。選項中只有 \((1,2)\) 符合。`},
  {id:"R07-5", tag:"R07", level:"中", type:"tf",
   stem:String.raw`若 \(a\)、\(b\) 為實數，且 \(a+b\sqrt{2}=0\)，則 \(a=b=0\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:[String.raw`忘了這個性質要求 \(a\)、\(b\) 是有理數`,"以為實數和有理數一樣","不會舉反例"], key:0,
   exp:String.raw`反例：\(a=\sqrt{2}\)、\(b=-1\)，則 \(a+b\sqrt{2}=0\)，但 \(a\)、\(b\) 都不是 \(0\)。<br>這個性質只在 \(a\)、\(b\) 為有理數時成立。`},

  // R08
  {id:"R08-2", tag:"R08", level:"易", type:"mc",
   stem:String.raw`\(\sqrt{30}\) 最接近下列哪個整數？`,
   opts:[String.raw`\(5\)`,String.raw`\(6\)`,String.raw`\(15\)`,String.raw`\(4\)`], ans:[0],
   reasons:[String.raw`把 \(\sqrt{30}\) 當成 \(30\div 2\)`,"平方算錯",String.raw`看到 \(30\) 介於 \(25\) 和 \(36\) 之間就直接選比較大的`], key:2,
   exp:String.raw`\(5^2=25\)、\(6^2=36\)，\(30\) 離 \(25\) 比較近（\(5.5^2=30.25\)），所以 \(\sqrt{30}\approx 5.48\)，最接近 \(5\)。`},
  {id:"R08-3", tag:"R08", level:"中", type:"mc",
   stem:String.raw`已知 \(\sqrt{2}\approx 1.414\)，則 \(\sqrt{200}\approx\)？`,
   opts:[String.raw`\(14.14\)`,String.raw`\(141.4\)`,String.raw`\(2.828\)`,String.raw`\(28.28\)`], ans:[0],
   reasons:[String.raw`不會把 \(\sqrt{200}\) 化成 \(10\sqrt{2}\)`,"小數點位置放錯",String.raw`當成 \(2\sqrt{2}\)`], key:0,
   exp:String.raw`\(\sqrt{200}=\sqrt{100\times 2}=10\sqrt{2}\approx 14.14\)。`},
  {id:"R08-4", tag:"R08", level:"中", type:"mc",
   stem:String.raw`已知 \(\sqrt{3}\approx 1.732\)，則 \(\dfrac{1}{\sqrt{3}}\approx\)？`,
   opts:[String.raw`\(0.577\)`,String.raw`\(1.732\)`,String.raw`\(0.333\)`,String.raw`\(0.866\)`], ans:[0],
   reasons:[String.raw`不知道可以先有理化成 \(\dfrac{\sqrt{3}}{3}\)`,String.raw`把 \(\dfrac{1}{\sqrt{3}}\) 當成 \(\dfrac{1}{3}\)`,"除法算錯"], key:0,
   exp:String.raw`\(\dfrac{1}{\sqrt{3}}=\dfrac{\sqrt{3}}{3}\approx\dfrac{1.732}{3}\approx 0.577\)。`},
  {id:"R08-5", tag:"R08", level:"易", type:"tf",
   stem:String.raw`\(3\lt\sqrt{10}\lt 4\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["不會用平方來夾範圍","平方算錯",String.raw`以為 \(\sqrt{10}\) 是 \(5\)`], key:0,
   exp:String.raw`\(3^2=9\lt 10\lt 16=4^2\)，所以 \(3\lt\sqrt{10}\lt 4\)。`},

  // R09
  {id:"R09-3", tag:"R09", level:"易", type:"tf",
   stem:String.raw`若 \(a\gt b\) 且 \(c\gt 0\)，則 \(ac\gt bc\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["以為乘任何數都要變號","把 c 的正負弄反","不熟不等式的乘法性質"], key:0,
   exp:String.raw`不等式兩邊同乘<b>正數</b>，不等號方向不變。`},
  {id:"R09-4", tag:"R09", level:"中", type:"tf",
   stem:String.raw`若 \(a\gt b\)，則 \(a^2\gt b^2\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:["忘了負數平方後大小可能顛倒","以為兩邊同時平方不等號不變","只用正數的例子判斷"], key:0,
   exp:String.raw`反例：\(a=1\)、\(b=-2\)，\(a\gt b\)，但 \(a^2=1\lt 4=b^2\)。`},
  {id:"R09-5", tag:"R09", level:"難", type:"mc",
   stem:String.raw`若 \(-2\lt x\lt 1\)，則 \(x^2\) 的範圍為？`,
   opts:[String.raw`\(0\le x^2\lt 4\)`,String.raw`\(1\lt x^2\lt 4\)`,String.raw`\(-4\lt x^2\lt 1\)`,String.raw`\(0\lt x^2\lt 4\)`], ans:[0],
   reasons:["直接把兩個端點平方",String.raw`忘了 \(x\) 可以等於 \(0\)`,String.raw`以為 \(x^2\) 可能是負的`], key:0,
   exp:String.raw`\(x\) 可以取到 \(0\)，此時 \(x^2=0\)；\(x\) 越接近 \(-2\)，\(x^2\) 越接近 \(4\)（但取不到）。<br>所以 \(0\le x^2\lt 4\)。`},

  // R10
  {id:"R10-3", tag:"R10", level:"易", type:"mc",
   stem:String.raw`\((x+5)(x-5)=\)？`,
   opts:[String.raw`\(x^2-25\)`,String.raw`\(x^2+25\)`,String.raw`\(x^2-10x-25\)`,String.raw`\(x^2-10\)`], ans:[0],
   reasons:["平方差公式記錯","常數項的正負號弄錯","把 5 的平方算成 10"], key:0,
   exp:String.raw`平方差公式：\((a+b)(a-b)=a^2-b^2\)，所以 \((x+5)(x-5)=x^2-25\)。`},
  {id:"R10-4", tag:"R10", level:"易", type:"tf",
   stem:String.raw`\((a+b)^2=a^2+b^2\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[1],
   reasons:[String.raw`忘了中間項 \(2ab\)`,"以為平方可以分配到每一項","展開時漏乘"], key:0,
   exp:String.raw`\((a+b)^2=a^2+2ab+b^2\)。例如 \((1+1)^2=4\)，但 \(1^2+1^2=2\)。`},
  {id:"R10-5", tag:"R10", level:"中", type:"num",
   stem:String.raw`利用乘法公式計算 \(101^2-99^2=\)？`, ans:"400", unitWord:"",
   reasons:["沒有用平方差公式，直接硬算算錯","平方差公式記錯",String.raw`把 \(101+99\) 或 \(101-99\) 算錯`], key:0,
   exp:String.raw`\(101^2-99^2=(101+99)(101-99)=200\times 2=400\)。`},
  {id:"R10-6", tag:"R10", level:"難", type:"num",
   stem:String.raw`若 \(a+b+c=6\)，\(a^2+b^2+c^2=14\)，則 \(ab+bc+ca=\)？`, ans:"11", unitWord:"",
   reasons:[String.raw`忘了除以 \(2\)`,String.raw`\((a+b+c)^2\) 展開時漏了交叉項`,"移項時算錯"], key:0,
   exp:String.raw`\((a+b+c)^2=a^2+b^2+c^2+2(ab+bc+ca)\)，<br>\(36=14+2(ab+bc+ca)\)，所以 \(ab+bc+ca=11\)。`},
  {id:"R10-7", tag:"R10", level:"中", type:"mc",
   stem:String.raw`將 \((a+b-c)^2\) 展開後，\(bc\) 項的係數是？`,
   opts:[String.raw`\(-2\)`,String.raw`\(2\)`,String.raw`\(-1\)`,String.raw`\(0\)`], ans:[0],
   reasons:["交叉項的正負號弄錯","交叉項忘了乘 2","以為沒有這一項"], key:0,
   exp:String.raw`\((a+b-c)^2=a^2+b^2+c^2+2ab-2bc-2ca\)，\(bc\) 項的係數是 \(-2\)。`},

  // R11
  {id:"R11-3", tag:"R11", level:"易", type:"mc",
   stem:String.raw`\((x+1)(x^2-x+1)=\)？`,
   opts:[String.raw`\(x^3+1\)`,String.raw`\(x^3-1\)`,String.raw`\((x+1)^3\)`,String.raw`\(x^3+x+1\)`], ans:[0],
   reasons:["立方和與立方差的符號記反","把立方和公式和和的立方公式搞混","展開時漏乘"], key:0,
   exp:String.raw`立方和公式：\((a+b)(a^2-ab+b^2)=a^3+b^3\)，這裡 \(a=x\)、\(b=1\)，結果是 \(x^3+1\)。`},
  {id:"R11-4", tag:"R11", level:"中", type:"mc",
   stem:String.raw`因式分解 \(8x^3-27=\)？`,
   opts:[String.raw`\((2x-3)(4x^2+6x+9)\)`,String.raw`\((2x-3)(4x^2-6x+9)\)`,String.raw`\((2x+3)(4x^2-6x+9)\)`,String.raw`\((2x-3)(4x^2+12x+9)\)`], ans:[0],
   reasons:["立方差中間項的正負號記錯",String.raw`把 \(a^2+ab+b^2\) 寫成完全平方式`,String.raw`沒看出 \(8x^3=(2x)^3\)、\(27=3^3\)`], key:0,
   exp:String.raw`\(8x^3-27=(2x)^3-3^3=(2x-3)\left[(2x)^2+(2x)(3)+3^2\right]=(2x-3)(4x^2+6x+9)\)。`},
  {id:"R11-5", tag:"R11", level:"中", type:"mc",
   stem:String.raw`\((x-1)^3=\)？`,
   opts:[String.raw`\(x^3-3x^2+3x-1\)`,String.raw`\(x^3-1\)`,String.raw`\(x^3-3x^2-3x-1\)`,String.raw`\(x^3+3x^2+3x-1\)`], ans:[0],
   reasons:[String.raw`以為 \((a-b)^3=a^3-b^3\)`,"各項的正負號弄錯","係數 3 漏掉"], key:1,
   exp:String.raw`\((a-b)^3=a^3-3a^2b+3ab^2-b^3\)，所以 \((x-1)^3=x^3-3x^2+3x-1\)。`},
  {id:"R11-6", tag:"R11", level:"難", type:"num",
   stem:String.raw`若 \(a+b=4\)、\(ab=2\)，則 \(a^3+b^3=\)？`, ans:"40", unitWord:"",
   reasons:[String.raw`忘了減 \(3ab(a+b)\)`,"立方和公式記錯",String.raw`把 \((a+b)^3\) 算錯`], key:0,
   exp:String.raw`\(a^3+b^3=(a+b)^3-3ab(a+b)=64-3\times 2\times 4=40\)。`},

  // R12
  {id:"R12-3", tag:"R12", level:"中", type:"num",
   stem:String.raw`若 \(x-\dfrac{1}{x}=2\)，則 \(x^2+\dfrac{1}{x^2}=\)？`, ans:"6", unitWord:"",
   reasons:[String.raw`忘了 \(\left(x-\dfrac{1}{x}\right)^2\) 的中間項是 \(-2\)，要加回 \(2\)`,String.raw`直接把 \(2\) 平方得 \(4\)`,String.raw`以為要減 \(2\)`], key:0,
   exp:String.raw`\(\left(x-\dfrac{1}{x}\right)^2=x^2-2+\dfrac{1}{x^2}=4\)，所以 \(x^2+\dfrac{1}{x^2}=6\)。`},
  {id:"R12-4", tag:"R12", level:"中", type:"mc",
   stem:String.raw`若 \(x+\dfrac{1}{x}=4\)，則 \(\left(x-\dfrac{1}{x}\right)^2=\)？`,
   opts:[String.raw`\(12\)`,String.raw`\(14\)`,String.raw`\(16\)`,String.raw`\(8\)`], ans:[0],
   reasons:[String.raw`把 \(\left(x-\dfrac{1}{x}\right)^2\) 和 \(x^2+\dfrac{1}{x^2}\) 搞混`,String.raw`以為 \(\left(x-\dfrac{1}{x}\right)^2=\left(x+\dfrac{1}{x}\right)^2\)`,"中間項算錯"], key:0,
   exp:String.raw`\(\left(x-\dfrac{1}{x}\right)^2=\left(x+\dfrac{1}{x}\right)^2-4=16-4=12\)。`},
  {id:"R12-5", tag:"R12", level:"難", type:"num",
   stem:String.raw`若 \(x+\dfrac{1}{x}=3\)，則 \(x^4+\dfrac{1}{x^4}=\)？`, ans:"47", unitWord:"",
   reasons:[String.raw`最後一步忘了再減 \(2\)`,String.raw`直接把 \(3\) 四次方`,String.raw`第一步 \(x^2+\dfrac{1}{x^2}\) 就算錯`], key:0,
   exp:String.raw`先算 \(x^2+\dfrac{1}{x^2}=9-2=7\)，再平方：\(x^4+\dfrac{1}{x^4}=7^2-2=47\)。`},

  // R13
  {id:"R13-3", tag:"R13", level:"易", type:"mc",
   stem:String.raw`\(\sqrt{50}\) 化簡後為？`,
   opts:[String.raw`\(5\sqrt{2}\)`,String.raw`\(25\sqrt{2}\)`,String.raw`\(2\sqrt{5}\)`,String.raw`\(10\sqrt{5}\)`], ans:[0],
   reasons:[String.raw`提出來的是 \(25\) 而不是 \(\sqrt{25}=5\)`,"找錯完全平方因數","根號內外弄反"], key:0,
   exp:String.raw`\(\sqrt{50}=\sqrt{25\times 2}=5\sqrt{2}\)。`},
  {id:"R13-4", tag:"R13", level:"易", type:"mc",
   stem:String.raw`\(\sqrt{3}\times\sqrt{12}=\)？`,
   opts:[String.raw`\(6\)`,String.raw`\(\sqrt{15}\)`,String.raw`\(36\)`,String.raw`\(3\sqrt{2}\)`], ans:[0],
   reasons:["把根號相乘當成根號內相加","乘完忘了開根號","化簡時算錯"], key:0,
   exp:String.raw`\(\sqrt{3}\times\sqrt{12}=\sqrt{36}=6\)。`},
  {id:"R13-5", tag:"R13", level:"中", type:"mc",
   stem:String.raw`\((\sqrt{5}+\sqrt{2})^2=\)？`,
   opts:[String.raw`\(7+2\sqrt{10}\)`,String.raw`\(7\)`,String.raw`\(7+\sqrt{10}\)`,String.raw`\(10+2\sqrt{7}\)`], ans:[0],
   reasons:[String.raw`以為 \((a+b)^2=a^2+b^2\)，漏了中間項`,"中間項忘了乘 2","根號相乘算錯"], key:0,
   exp:String.raw`\((\sqrt{5}+\sqrt{2})^2=5+2\sqrt{10}+2=7+2\sqrt{10}\)。`},
  {id:"R13-6", tag:"R13", level:"難", type:"mc",
   stem:String.raw`\((2+\sqrt{3})^{10}(2-\sqrt{3})^{11}=\)？`,
   opts:[String.raw`\(2-\sqrt{3}\)`,String.raw`\(2+\sqrt{3}\)`,String.raw`\(1\)`,String.raw`\(-1\)`], ans:[0],
   reasons:[String.raw`沒發現 \((2+\sqrt{3})(2-\sqrt{3})=1\)`,"配對時次方數算錯，多出的那一項放錯","想要直接展開而算不下去"], key:1,
   exp:String.raw`\((2+\sqrt{3})(2-\sqrt{3})=4-3=1\)。<br>原式 \(=\left[(2+\sqrt{3})(2-\sqrt{3})\right]^{10}(2-\sqrt{3})=1\times(2-\sqrt{3})=2-\sqrt{3}\)。`},
  {id:"R13-7", tag:"R13", level:"中", type:"num",
   stem:String.raw`\((\sqrt{7}+\sqrt{3})(\sqrt{7}-\sqrt{3})=\)？`, ans:"4", unitWord:"",
   reasons:["沒有用平方差公式","把根號的平方算錯",String.raw`算成 \(7+3\)`], key:0,
   exp:String.raw`平方差：\((\sqrt{7})^2-(\sqrt{3})^2=7-3=4\)。`},

  // R14
  {id:"R14-3", tag:"R14", level:"易", type:"mc",
   stem:String.raw`\(\dfrac{6}{\sqrt{3}}=\)？`,
   opts:[String.raw`\(2\sqrt{3}\)`,String.raw`\(6\sqrt{3}\)`,String.raw`\(\dfrac{\sqrt{3}}{6}\)`,String.raw`\(3\sqrt{2}\)`], ans:[0],
   reasons:["有理化後忘了約分","分子分母乘的數不一樣","把分子分母弄反"], key:0,
   exp:String.raw`\(\dfrac{6}{\sqrt{3}}=\dfrac{6\sqrt{3}}{3}=2\sqrt{3}\)。`},
  {id:"R14-4", tag:"R14", level:"中", type:"mc",
   stem:String.raw`\(\dfrac{\sqrt{3}+1}{\sqrt{3}-1}=\)？`,
   opts:[String.raw`\(2+\sqrt{3}\)`,String.raw`\(1\)`,String.raw`\(4+2\sqrt{3}\)`,String.raw`\(\sqrt{3}\)`], ans:[0],
   reasons:[String.raw`忘了除以分母 \(2\)`,"分子展開時漏了交叉項","乘的共軛式符號弄反"], key:0,
   exp:String.raw`分子分母同乘 \(\sqrt{3}+1\)：<br>\(\dfrac{(\sqrt{3}+1)^2}{3-1}=\dfrac{4+2\sqrt{3}}{2}=2+\sqrt{3}\)。`},
  {id:"R14-5", tag:"R14", level:"中", type:"mc",
   stem:String.raw`\(\dfrac{1}{\sqrt{5}+2}=\)？`,
   opts:[String.raw`\(\sqrt{5}-2\)`,String.raw`\(\sqrt{5}+2\)`,String.raw`\(\dfrac{\sqrt{5}-2}{9}\)`,String.raw`\(2-\sqrt{5}\)`], ans:[0],
   reasons:[String.raw`分母算成 \(5+4\)`,"共軛式符號弄反",String.raw`把 \(\sqrt{5}-2\) 寫反成負數`], key:0,
   exp:String.raw`分子分母同乘 \(\sqrt{5}-2\)：\(\dfrac{\sqrt{5}-2}{5-4}=\sqrt{5}-2\)。`},
  {id:"R14-6", tag:"R14", level:"難", type:"num",
   stem:String.raw`\(\dfrac{1}{1+\sqrt{2}}+\dfrac{1}{\sqrt{2}+\sqrt{3}}+\dfrac{1}{\sqrt{3}+\sqrt{4}}+\cdots+\dfrac{1}{\sqrt{15}+\sqrt{16}}=\)？`, ans:"3", unitWord:"",
   reasons:["沒發現每一項有理化後會前後相消","有理化時正負號弄反","相消後剩下的首尾項算錯"], key:0,
   exp:String.raw`每一項 \(\dfrac{1}{\sqrt{k}+\sqrt{k+1}}=\sqrt{k+1}-\sqrt{k}\)。<br>相加後中間全部消掉：\(\sqrt{16}-\sqrt{1}=4-1=3\)。`},
  {id:"R14-7", tag:"R14", level:"易", type:"tf",
   stem:String.raw`\(\dfrac{1}{\sqrt{2}}=\dfrac{\sqrt{2}}{2}\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["不熟分母有理化","以為有理化會改變數值","分子分母乘的數不一樣"], key:0,
   exp:String.raw`分子分母同乘 \(\sqrt{2}\)：\(\dfrac{1}{\sqrt{2}}=\dfrac{\sqrt{2}}{2}\)，兩者相等。`},

  // R15
  {id:"R15-2", tag:"R15", level:"易", type:"mc",
   stem:`下列何者最大？`,
   opts:[String.raw`\(2\sqrt{3}\)`,String.raw`\(3\sqrt{2}\)`,String.raw`\(\sqrt{15}\)`,String.raw`\(4\)`], ans:[1],
   reasons:["沒有把每個數都化成根號形式再比較","以為根號外的數越大就越大","平方算錯"], key:0,
   exp:String.raw`都化成根號：\(2\sqrt{3}=\sqrt{12}\)、\(3\sqrt{2}=\sqrt{18}\)、\(\sqrt{15}\)、\(4=\sqrt{16}\)，最大的是 \(3\sqrt{2}\)。`},
  {id:"R15-3", tag:"R15", level:"難", type:"mc",
   stem:String.raw`設 \(a=\sqrt{3}-\sqrt{2}\)，\(b=\sqrt{5}-2\)，\(c=\sqrt{2}-1\)，則大小關係為？`,
   opts:[String.raw`\(b\lt a\lt c\)`,String.raw`\(a\lt b\lt c\)`,String.raw`\(c\lt a\lt b\)`,String.raw`\(a=b=c\)`], ans:[0],
   reasons:["看到每個數都是相鄰兩根號的差，就以為相等",String.raw`沒想到先有理化成 \(\dfrac{1}{\sqrt{n+1}+\sqrt{n}}\) 再比較`,"有理化後分母大小判斷錯"], key:1,
   exp:String.raw`有理化：\(c=\dfrac{1}{\sqrt{2}+1}\)、\(a=\dfrac{1}{\sqrt{3}+\sqrt{2}}\)、\(b=\dfrac{1}{\sqrt{5}+2}\)。<br>分子都是 \(1\)，分母越大值越小，所以 \(b\lt a\lt c\)。`},
  {id:"R15-4", tag:"R15", level:"中", type:"tf",
   stem:String.raw`\(\sqrt{2}+\sqrt{7}\lt\sqrt{3}+\sqrt{6}\)`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["根號內加起來都是 9，就以為相等","沒有先平方再比較","平方後交叉項比錯"], key:1,
   exp:String.raw`平方：左邊 \(9+2\sqrt{14}\)，右邊 \(9+2\sqrt{18}\)。<br>\(14\lt 18\)，所以左邊較小，敘述正確。`},

  // R16
  {id:"R16-3", tag:"R16", level:"易", type:"mc",
   stem:String.raw`\(\sqrt{5+2\sqrt{6}}=\)？`,
   opts:[String.raw`\(\sqrt{3}+\sqrt{2}\)`,String.raw`\(\sqrt{3}-\sqrt{2}\)`,String.raw`\(\sqrt{5}+\sqrt{6}\)`,String.raw`\(\sqrt{6}+1\)`], ans:[0],
   reasons:[String.raw`找錯兩數（和為 \(5\)、積為 \(6\)）`,"以為可以直接把根號拆開","正負號寫錯"], key:0,
   exp:String.raw`兩數和為 \(5\)、積為 \(6\)：\(3\) 和 \(2\)。\(\sqrt{5+2\sqrt{6}}=\sqrt{(\sqrt{3}+\sqrt{2})^2}=\sqrt{3}+\sqrt{2}\)。`},
  {id:"R16-4", tag:"R16", level:"中", type:"mc",
   stem:String.raw`\(\sqrt{9-\sqrt{56}}=\)？`,
   opts:[String.raw`\(\sqrt{7}-\sqrt{2}\)`,String.raw`\(\sqrt{2}-\sqrt{7}\)`,String.raw`\(3-\sqrt{56}\)`,String.raw`\(\sqrt{7}+\sqrt{2}\)`], ans:[0],
   reasons:[String.raw`沒先把 \(\sqrt{56}\) 寫成 \(2\sqrt{14}\)`,"大小順序寫反，結果變負數","找錯兩數"], key:0,
   exp:String.raw`\(\sqrt{56}=2\sqrt{14}\)。兩數和為 \(9\)、積為 \(14\)：\(7\) 和 \(2\)。<br>結果是 \(\sqrt{7}-\sqrt{2}\)（大的在前）。`},
  {id:"R16-5", tag:"R16", level:"難", type:"mc",
   stem:String.raw`\(\sqrt{2-\sqrt{3}}=\)？`,
   opts:[String.raw`\(\dfrac{\sqrt{6}-\sqrt{2}}{2}\)`,String.raw`\(\sqrt{3}-1\)`,String.raw`\(\sqrt{2}-1\)`,String.raw`\(\dfrac{\sqrt{3}-1}{2}\)`], ans:[0],
   reasons:[String.raw`沒想到要先湊出 \(2\sqrt{\ }\) 的形式（分子分母同乘 \(2\)）`,String.raw`湊完後忘了除以 \(\sqrt{2}\)`,"有理化時算錯"], key:0,
   exp:String.raw`\(\sqrt{2-\sqrt{3}}=\sqrt{\dfrac{4-2\sqrt{3}}{2}}=\dfrac{\sqrt{3}-1}{\sqrt{2}}=\dfrac{\sqrt{6}-\sqrt{2}}{2}\)。`},

  // R17
  {id:"R17-3", tag:"R17", level:"易", type:"tf",
   stem:String.raw`若 \(a\gt 0\)、\(b\gt 0\)，則 \(\dfrac{a+b}{2}\ge\sqrt{ab}\)。`,
   opts:["○ 正確","✕ 錯誤"], ans:[0],
   reasons:["不熟算幾不等式","以為不等號方向相反","以為要 a = b 才成立"], key:0,
   exp:String.raw`這就是算幾不等式：兩個正數的算術平均數 \(\ge\) 幾何平均數，\(a=b\) 時等號成立。`},
  {id:"R17-4", tag:"R17", level:"中", type:"mc",
   stem:String.raw`若 \(x\gt 0\)，則 \(x+\dfrac{9}{x}\) 的最小值為？`,
   opts:[String.raw`\(6\)`,String.raw`\(9\)`,String.raw`\(3\)`,String.raw`\(10\)`], ans:[0],
   reasons:[String.raw`算幾後忘了乘 \(2\)`,"把乘積 9 當成最小值",String.raw`代 \(x=1\) 就當成最小值`], key:0,
   exp:String.raw`\(\dfrac{x+\frac{9}{x}}{2}\ge\sqrt{x\cdot\frac{9}{x}}=3\)，所以 \(x+\dfrac{9}{x}\ge 6\)，當 \(x=3\) 時等號成立。`},
  {id:"R17-5", tag:"R17", level:"難", type:"mc",
   stem:String.raw`用 \(40\) 公尺長的籬笆圍一塊長方形菜園，其中一邊靠牆不用圍，其餘三邊都要圍。菜園的最大面積是多少平方公尺？`,
   opts:[String.raw`\(200\)`,String.raw`\(100\)`,String.raw`\(400\)`,String.raw`\(\dfrac{1600}{9}\)`], ans:[0],
   reasons:["把靠牆的那一邊也算進籬笆",String.raw`沒有把「\(x\)」和「\(2y\)」看成算幾的兩個數`,String.raw`等號條件用成 \(x=y\)`], key:1,
   exp:String.raw`設靠牆對邊長 \(x\)、兩側各 \(y\)，則 \(x+2y=40\)，面積 \(xy=\dfrac{1}{2}\cdot x\cdot 2y\)。<br>\(\dfrac{x+2y}{2}\ge\sqrt{x\cdot 2y}\Rightarrow x\cdot 2y\le 400\)，所以 \(xy\le 200\)，當 \(x=2y=20\) 時成立。`},
  {id:"R17-6", tag:"R17", level:"中", type:"mc",
   stem:String.raw`若 \(a\gt 0\)、\(b\gt 0\) 且 \(a+b=10\)，則 \(ab\) 的最大值為？`,
   opts:[String.raw`\(25\)`,String.raw`\(100\)`,String.raw`\(50\)`,String.raw`\(20\)`], ans:[0],
   reasons:["算幾不等式移項時忘了平方","把 a + b 直接平方當答案","等號成立條件用錯"], key:0,
   exp:String.raw`\(\sqrt{ab}\le\dfrac{a+b}{2}=5\)，所以 \(ab\le 25\)，當 \(a=b=5\) 時成立。`}
];
